### ISSUE TITLE
Demo server RSA-KeyGen-FIPS186-4 always return "infoGeneratedByServer": false

### ISSUE THREAD

**Issue by harrywangca** [usnistgov/ACVP-Server#10]
I have sent RSA-KeyGen-FIPS186-4  capabilities JSON string as below and got the vectors successfully. My request has "infoGeneratedByServer": true,  but the returned vectors contain only "infoGeneratedByServer": false for all trstGroups. 

Is it a server bug?

 [{"acvVersion":"1.0"},{"algorithms":[{"algorithm":"RSA","revision":"FIPS186-4","mode":"keyGen","prereqVals":[{"algorithm":"SHA","valValue":"same"},{"algorithm":"DRBG","valValue":"same"}],"infoGeneratedByServer":true,"pubExpMode":"random","keyFormat":"standard","capabilities":[{"randPQ":"B.3.3","properties":[{"modulo":2048,"hashAlg":[],"primeTest":["tblC2"]},{"modulo":3072,"hashAlg":[],"primeTest":["tblC2"]}]}]}]}]

**Comment by celic** [comment]
Do you have a particular vector set ID for this?

**Comment by harrywangca** [comment]
I've just made another request:

***ACVP [INFO][acvp_register:2000]--> [{"acvVersion":"1.0"},{"algorithms":[{"algorithm":"RSA","revision":"FIPS186-4","mode":"keyGen","prereqVals":[{"algorithm":"SHA","valValue":"same"},{"algorithm":"DRBG","valValue":"same"}],"infoGeneratedByServer":true,"pubExpMode":"random","keyFormat":"standard","capabilities":[{"randPQ":"B.3.3","properties":[{"modulo":2048,"hashAlg":[],"primeTest":["tblC2"]},{"modulo":3072,"hashAlg":[],"primeTest":["tblC2"]}]}]}]}]
***ACVP [INFO][log_network_status:1468]--> POST Registration...
        Status: 200
        Url: https://demo.acvts.nist.gov:443/acvp/v1/testSessions
        Resp: Recieved

***ACVP [INFO][acvp_parse_test_session_register:2336]--> Received vsid_url=/acvp/v1/testSessions/117003/vectorSets/334996
***ACVP [STATUS][acvp_register:2008]--> Successfully sent registration and received list of vector set URLs
***ACVP [STATUS][acvp_register:2009]--> Test session URL: /acvp/v1/testSessions/117003
***ACVP [STATUS][acvp_run:3294]--> Beginning to download and process vector sets...
***ACVP [INFO][log_network_status:1448]--> GET Vector Set...
        Status: 200
        Url: https://demo.acvts.nist.gov:443/acvp/v1/testSessions/117003/vectorSets/334996

**Comment by celic** [comment]
Thanks, it is helpful for us to look at everything the server generates. For B.3.3, `"infoGeneratedByServer"` is not relevant. These groups do not follow the same structure as other RSA KeyGen modes. This property will ALWAYS be false for B.3.3 groups, regardless of what is provided during the registration because it is not used. Test groups for B.3.3 are KATs and GDTs. The KATs are static and do not change. The GDTs require the client to generate a bunch of keys with no input from the server. There are no AFTs for B.3.3 which is what `"infoGeneratedByServer"` refers to.

**Comment by harrywangca** [comment]
Thank you for the clarification.

**Comment by celic** [comment]
Yup, sorry the answer is "confusing but intended". Perhaps we can remove that property from non-AFT test type groups.
