### ISSUE TITLE
ctrDRBG entropyInputLen not matching request

### ISSUE THREAD

**Issue by asant57** [usnistgov/ACVP-Server#101]
Environment: 
Demo

testSessionId: 
176985

vsId:
554441

Algorithm registration request data
{
    "algorithm": "ctrDRBG",
    "revision": "1.0",
    "predResistanceEnabled": [
      false
    ],
    "capabilities": [
      {
        "mode": "AES-256",
        "derFuncEnabled": true,
        "entropyInputLen": [
          1536
        ],
        "nonceLen": [
          128
        ],
        "persoStringLen": [
          128
        ],
        "additionalInputLen": [
          0
        ],
        "returnedBitsLen": 512
      }
    ],
    "reseedImplemented": false
  }

Endpoint in which the error is experienced 
Download of vectors for test session

Observed behavior: 
{
  "vsId": 554441,
  "algorithm": "ctrDRBG",
  "revision": "1.0",
  "isSample": true,
  "testGroups": [
    {
      "tgId": 1,
      "testType": "AFT",
      "derFunc": true,
      "reSeed": false,
      "predResistance": false,
      "entropyInputLen": 1024,
      "nonceLen": 128,
      "persoStringLen": 128,
      "additionalInputLen": 0,
      "returnedBitsLen": 512,
      "mode": "AES-256",
      "tests": [
        { .... <VECTORS PRESENT>

Expected behavior
The Expected behavior is that the entropyInputLen field in the vectors requested is 1536 matching the only supported value provided in the request JSON.

**Comment by Kritner** [comment]
We had an internal (arbitrary) limit to the amount of bits we'd pull from a domain of 1024 for this algorithm - I've upped that significantly for the next release (to 65536).  I'm kind of surprised this hasn't come up before 😅

**Comment by Kritner** [comment]
This change is on demo in release [v1.1.0.18](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.18)

**Comment by asant57** [comment]
Shouldn't the value be defined as the Max Entropy specified in Section 5.2 of the specification? or the specification updated to indicate the max supported value. 

since I could theoretically trip this bug again by defining a single value greater than the 65536 you configured but less than the max value defined as accepted?

**Comment by Kritner** [comment]
The specification will be updated to reflect the new value.

**Comment by Kritner** [comment]
This change has been released to prod in release [v1.1.0.18](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.18).
