### ISSUE TITLE
RSA KeyGen Ignoring InfoGeneratedByServer flag

### ISSUE THREAD

**Issue by asant57** [usnistgov/ACVP-Server#102]
**environment**
Demo

**testSessionId**
177486

**vsId**
557149

**Algorithm registration**
{
    "algorithm": "RSA",
    "revision": "FIPS186-4",
    "mode": "keyGen",
    "capabilities": [
      {
        "randPQ": "B.3.3",
        "properties": [
          {
            "modulo": 2048,
            "primeTest": [
              "tblC2"
            ]
          }
        ]
      }
    ],
    "infoGeneratedByServer": true,
    "pubExpMode": "fixed",
    "fixedPubExp": "010001",
    "keyFormat": "standard"
  }

**Endpoint in which the error is experienced**
Result of Download Vectors, the vectors requested by the server.

**Expected behavior**
It was expected that the infoGeneratedByServer flag in the Request file would be set to TRUE, as that is the value present in the request, however in the request the value is set to false.

**Additional context**
{
    "vsId": 557149,
    "algorithm": "RSA",
    "mode": "keyGen",
    "revision": "FIPS186-4",
    "isSample": true,
    "testGroups": [
      {
        "tgId": 1,
        "infoGeneratedByServer": false,
        "modulo": 2048,
        "fixedPubExp": "010001",
        "testType": "GDT",
        "keyFormat": "standard",
        "primeTest": "tblC2",
        "randPQ": "B.3.3",
        "pubExp": "fixed",
        "tests": [
          {
            "tcId": 1,
            "deferred": true
          },
          {
            "tcId": 2,
            "deferred": true
          },
          {
            "tcId": 3,
            "deferred": true
          }
        ]
      }
    ]
  }

**Comment by Kritner** [comment]
The [GDT test type](https://pages.nist.gov/ACVP/draft-celi-acvp-rsa.html#section-6.1-3) which is applicable to B.3.3, is not impact by the `infoGeneratedByServer` flag.

**Comment by asant57** [comment]
See #86 this seems to be another example of the Server appearing to accept irrelevant or invalid combination data without providing any indication to the user. 

Also please ensure that the specification document provides clear indication of which B.x.y sequences infoGeneratedByServer is relevant for.

**Comment by celic** [comment]
It's relevant for all of them depending on the other properties you can support. For B.3.2, 3.4, 3.5, 3.6, infoGeneratedByServer will provide the client with ALL the inputs and expect them to arrive at the same output the server has already arrived at. When it is false, the client will be provided with SOME of the inputs, like an already agreed upon fixed public exponent. The client will generate the inputs and outputs, and communicate ALL of those back to the server. The server will try to reach the same output key. 

For B.3.3, infoGeneratedByServer enables the KAT test groups if the client supports a random public exponent. The GDT are always enabled as a bare minimum test for B.3.3.
