### ISSUE TITLE
SP800-56a rev3 fullvalidation results

### ISSUE THREAD

**Issue by Nagarjuna-jantali** [usnistgov/ACVP-Server#103]
Hi 

I am trying to verify KAS-ECC full validation vector, but getting below errors for some of the test cases.

[
  {
    "acvVersion": "1.0"
  },
  {
    "vsId": 556974,
    "disposition": "failed",

      "tcId": 31,
        "result": "failed",
        "reason": "Incorrect TestPassed result. Test expectation: \u0022Failure - IUT should detect issue in ACVP server ephemeral public key.\u0022"
      },
      {
        "tcId": 32,
        "result": "failed",
        "reason": "Incorrect TestPassed result. Test expectation: \u0022Failure - IUT should detect issue in ACVP server ephemeral public key.\u0022"
      },
      {
        "tcId": 33,
        "result": "passed"
      },
      {
        "tcId": 34,
        "result": "passed"
      },
      {
        "tcId": 35,
        "result": "failed",
        "reason": "Incorrect TestPassed result. Test expectation: \u0022Failure - IUT should detect issue in ACVP server ephemeral public key.\u0022"
      },

What does this error mean?  IUT should detect the issue in both "ephemeralPublicServer key" and "ephemeralPublicIut key"
for "testType": "VAL"?

please let me know.

Regards,
Nag

**Comment by Kritner** [comment]
Yes, the error message indicates that the IUT should detect an issue in the ACVP server ephemeral public key.

The key is malformed, and likely not on the curve.  The IUT with the given registration should be able to detect this.

**Comment by smuellerDD** [comment]
Am Mittwoch, dem 12.05.2021 um 02:34 -0700 schrieb Nagarjun:
> Hi 
> 
> I am trying to verify KAS-ECC full validation vector, but getting below
> errors for some of the test cases.

Sorry, this is not the forum to debug your implementation. Look at the CAVP
ACVP certificate list, the vast majority of all OpenSSL certs are produced
with this tool - so, it works. If your old OpenSSL has an issue, you need to
analyze it yourself.

Ciao
Stephan
