### ISSUE TITLE
Is KAS-KDF SP800-56Cr2 supported on prod server?

### ISSUE THREAD

**Issue by dsikkema-atsec** [usnistgov/ACVP-Server#105]
**environment**
Prod

**testSessionId**

**vsId**

**Algorithm registration**
KAS-KDF-OneStep-Sp800-56Cr2 and KAS-KDF-TwoStep-Sp800-56Cr2

**Endpoint in which the error is experienced**
https://acvts.nist.gov:443/acvp/v1/testSessions
 HTTP method POST

**Expected behavior**
The request for test vectors was expected to return a set of vectors for KAS-KDF 56cr2 (one-step and two-step)

**Additional context**

Process following server response: [
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "Unable to map KAS-KDF-OneStep-Sp800-56Cr2 - index 0 to an internal algorithm id.",
      "Unable to map KAS-KDF-TwoStep-Sp800-56Cr2 - index 1 to an internal algorithm id."
    ]
  }
]

The same request worked fine on the demo server. I was able to request vectors and validate the responses on the demo server.

**Comment by Kritner** [comment]
They are not currently enabled on prod, though they can be.  I'll update once the algorithms are enabled on prod.

**Comment by Kritner** [comment]
Should be available on production now
