### ISSUE TITLE
DRBG Generation Issue

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP-Server#109]
**environment**
Demo

**testSessionId**
/acvp/v1/testSessions/177862
/acvp/v1/testSessions/178353

we’ve tried generating Hash DRBG vectors with an Entropy Input of 1920, however, the test vector generates at 1024 instead.

**Comment by Kritner** [comment]
Same issue as: https://github.com/usnistgov/ACVP-Server/issues/101

will be fixed in the next release.

**Comment by Kritner** [comment]
This change has been released to prod in release [v1.1.0.18](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.18).
