### ISSUE TITLE
AES-ECB MCT test with empty "pt" in excepted result

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP-Server#11]
**environment**
Demo

**testSessionId**
/acvp/v1/testSessions/100283

**vsId**
291188

There are three Monte Carlo tests, with "tgId" as 16, 17, and 18.
16 - keyLen = 128
17 - keyLen = 192
18 - keyLen = 256
In the expected response file, both cases 16 and 18 include an empty "pt" item before the "resultsArray".  For example:
"tgId": 16,
"tests": [
{
"tcId": 1070,
"pt": "",
"resultsArray": [
...
Case 17 (keyLen = 192) does not include this empty "pt" item.  Should all three cases be consistent in their inclusion or exclusion of the empty "pt"?  It seemed odd that only the 192 keyLen did not include it, while the other two cases did.

**Comment by Kritner** [comment]
Hmm... that is strange.  I have not had any luck reproducing this, but I do see the two empty `"pt": ""`s in the expected answer file for this VS.  I just tried a few vector sets myself with your registration and did not encounter the behavior.

There doesn't seem to be any relevant changes to the system in the time between when your vector set was generated, and today.  The only thing I can think of is our "precomputed values" process at some point was saving the `"pt": ""`.  It doesn't *hurt* anything by being there, but it is confusing.  That expected results file should still pass as far as I can tell, were you to POST it.

I'll try to identify if these sorts of precomputed values do exist on this environment, but you should still be safe to attempt to submit that file, it just has an extra property in it that will be ignored.

**Comment by Kritner** [comment]
This change is on demo (though it wouldn't have impacted your already existing test session)

**Comment by Kritner** [comment]
this change is now on production https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.12
