### ISSUE TITLE
Server returns error when downloading ACVP-AES-CBC-CS2 vectors

### ISSUE THREAD

**Issue by jbarnesweb** [usnistgov/ACVP-Server#112]
**environment**
Demo

**testSessionId**
181959

**vsId**
584495

**Algorithm registration**

```
      {
        "algorithm": "ACVP-AES-CBC-CS2",
        "revision": "1.0",
        "keyLen": [
          128,
          192,
          256
        ],
        "direction": [
          "encrypt",
          "decrypt"
        ],
        "payloadLen": [
          {
            "max": 65536,
            "min": 128,
            "increment": 8
          }
        ]
      },

```

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov/acvp/v1/testSessions/181959/vectorSets/584495 GET

**Expected behavior**
Downloaded vector set

**Additional context**
Server response
[{"acvVersion":"1.0"},{"error":"Failed to generate. Object reference not set to an instance of an object."}]

**Comment by Kritner** [comment]
I ran that registration through again and it succeeded. I'll have to dig a bit deeper as to why it failed the first time, but you should be able to grab the prompt file now.

**Comment by Kritner** [comment]
I didn't end up finding a reasoning for this, and it doesn't seem to have reoccurred, at least that we've been notified of, so I'll close this for now
