### ISSUE TITLE
Orleans Grain Error

### ISSUE THREAD

**Issue by GlennUL** [usnistgov/ACVP-Server#115]
**environment**  
Prod

**testSessionId** 
7965

**vsId** 
75616

**Algorithm registration** 
{
    "algorithms": [
        {
            "prereqVals": [
                {
                    "algorithm": "DRBG",
                    "valValue": ""
                },
                {
                    "algorithm": "SHA",
                    "valValue": ""
                },
                {
                    "algorithm": "SHA_OPT2",
                    "valValue": ""
                },
                {
                    "algorithm": "SHA_OPT3",
                    "valValue": ""
                },
                {
                    "algorithm": "DRBG_OPT2",
                    "valValue": ""
                }
            ],
            "algorithm": "ECDSA",
            "mode": "keyGen",
            "curve": [
                "P-256",
                "P-384"
            ],
            "secretGenerationMode": [
                "extra bits"
            ],
            "revision": "1.0"
        },
        {
            "prereqVals": [
                {
                    "algorithm": "DRBG",
                    "valValue": ""
                },
                {
                    "algorithm": "SHA",
                    "valValue": ""
                },
                {
                    "algorithm": "SHA_OPT2",
                    "valValue": ""
                },
                {
                    "algorithm": "SHA_OPT3",
                    "valValue": ""
                },
                {
                    "algorithm": "DRBG_OPT2",
                    "valValue": ""
                }
            ],
            "algorithm": "ECDSA",
            "mode": "keyVer",
            "curve": [
                "P-256",
                "P-384"
            ],
            "revision": "1.0"
        },
        {
            "prereqVals": [
                {
                    "algorithm": "DRBG",
                    "valValue": ""
                },
                {
                    "algorithm": "SHA",
                    "valValue": ""
                },
                {
                    "algorithm": "SHA_OPT2",
                    "valValue": ""
                },
                {
                    "algorithm": "SHA_OPT3",
                    "valValue": ""
                },
                {
                    "algorithm": "DRBG_OPT2",
                    "valValue": ""
                }
            ],
            "algorithm": "ECDSA",
            "mode": "sigGen",
            "capabilities": [
                {
                    "curve": [
                        "P-256"
                    ],
                    "hashAlg": [
                        "SHA2-256"
                    ]
                },
                {
                    "curve": [
                        "P-256"
                    ],
                    "hashAlg": [
                        "SHA2-384"
                    ]
                },
                {
                    "curve": [
                        "P-384"
                    ],
                    "hashAlg": [
                        "SHA2-256"
                    ]
                },
                {
                    "curve": [
                        "P-384"
                    ],
                    "hashAlg": [
                        "SHA2-384"
                    ]
                }
            ],
            "componentTest": false,
            "revision": "1.0"
        },
        {
            "prereqVals": [
                {
                    "algorithm": "DRBG",
                    "valValue": ""
                },
                {
                    "algorithm": "SHA",
                    "valValue": ""
                },
                {
                    "algorithm": "SHA_OPT2",
                    "valValue": ""
                },
                {
                    "algorithm": "SHA_OPT3",
                    "valValue": ""
                },
                {
                    "algorithm": "DRBG_OPT2",
                    "valValue": ""
                }
            ],
            "algorithm": "ECDSA",
            "mode": "sigVer",
            "capabilities": [
                {
                    "curve": [
                        "P-256"
                    ],
                    "hashAlg": [
                        "SHA-1"
                    ]
                },
                {
                    "curve": [
                        "P-384"
                    ],
                    "hashAlg": [
                        "SHA-1"
                    ]
                },
                {
                    "curve": [
                        "P-256"
                    ],
                    "hashAlg": [
                        "SHA2-256"
                    ]
                },
                {
                    "curve": [
                        "P-384"
                    ],
                    "hashAlg": [
                        "SHA2-256"
                    ]
                },
                {
                    "curve": [
                        "P-256"
                    ],
                    "hashAlg": [
                        "SHA2-384"
                    ]
                },
                {
                    "curve": [
                        "P-384"
                    ],
                    "hashAlg": [
                        "SHA2-384"
                    ]
                },
                {
                    "curve": [
                        "P-521"
                    ],
                    "hashAlg": [
                        "SHA2-512"
                    ]
                }
            ],
            "componentTest": false,
            "revision": "1.0"
        }
    ],
    "encryptAtRest": false,
    "isSample": false
}

**Endpoint in which the error is experienced** 
Vector results

**Expected behavior** 
Passing results

**Additional context** 
Results file contents:
{
    "error": "Orleans Grain did not fulfill expectations after retry attempts."
}

In addition to this error, vsId 75614 in this same test session returned the following:
"Unable to generate public key from private key d value"
On previous testing there was no issue with this test passing but now seems that only the true/false responses are being processed by the server which lends me to believe these are connected.

**Comment by Kritner** [comment]
@GlennUL your assumption appears to be correct about the things being connected.  There is seemingly something network related going on, will update once it's resolved.

We'll also be able to resubmit any jobs that failed due to the network issue.

**Comment by Kritner** [comment]
@GlennUL the issue is resolved and the vector sets that were impacted were resubmit through our internal processing.  75614 and 75616 now have validation files available for download - and actually in the case of 75614, there's a *new* validation file available for download - the vs passed once the connectivity issue was resolved.

Thanks for your understanding!

**Comment by GlennUL** [comment]
@Kritner Thank you for your quick resolution, it is greatly appreciated!
