### ISSUE TITLE
ECDSA SigVer - response mismatch

### ISSUE THREAD

**Issue by sowndar-raj** [usnistgov/ACVP-Server#117]
Hi,

The response generated by a vendor has failed in the ACVTS server, below are the algorithm/session details with error log:

**Algorithm:** ECDSA SigVer
**Session ID:** 8344
**vsId:** 78588

Error:

{
            "tcId": 602,
            "result": "failed",
            "reason": "modify key",
            "expected": {
               "testPassed": "False"
            },
            "provided": {
               "testPassed": "True"
            }
}

Two test cases failed in total, with same errors (602, 633)

Vendor believes that the response generated by the module is correct and claims that the same test cases has been executed against other cryptographic implementations and obtained the same result as the IUT. The vendor also confirmed that the point is on the curve, is valid and still appears to be in a normalised form. Can you please look into this and let us know what you think?

**Comment by Kritner** [comment]
We had a configuration issue in our "pool" (caching) system that was at fault, it has been corrected. I re-ran your response file against the system and the TS/VS are now in a passing state.

**Comment by sowndar-raj** [comment]
Thanks @Kritner !
