### ISSUE TITLE
Potential AES-GCM Issue with IV

### ISSUE THREAD

**Issue by woozypompanos** [usnistgov/ACVP-Server#118]
**environment**
Demo

**testSessionId**
186400

**vsId**
611791

**Algorithm registration**
{
	"algorithm": "ACVP-AES-GCM",
	"revision": "1.0",
	"direction": [
		"encrypt",
		"decrypt"
	],
	"ivGen": "internal",
	"ivGenMode": "8.2.1",
	"keyLen": [
		128,
		192,
		256
	],
	"tagLen": [
		32,
		64,
		96,
		104,
		112,
		120,
		128
	],
	"ivLen": [
		{
			"min": 96,
			"max": 1024,
			"increment": 32
		}
	],
	"payloadLen": [
		{
			"min": 128,
			"max": 1024,
			"increment": 32
		}
	],
	"aadLen": [
		{
			"min": 32,
			"max": 1024,
			"increment": 32
		}
	]
}

**Test Case**
{
	"tgId": 1,
	"testType": "AFT",
	"direction": "encrypt",
	"keyLen": 128,
	"ivLen": 96,
	"ivGen": "internal",
	"ivGenMode": "8.2.1",
	"payloadLen": 768,
	"aadLen": 32,
	"tagLen": 104,
	"tests": [
		{
			"tcId": 1,
			"pt": "EAA7966C2452F53FA8B23771D457258F8C1F5CAD3346F58156003598CC42AA7760BB76E2AA2791CADF9CC1439F14559D0D94F6E0F894B761894094B51CD5DC69F5D68529F4322483FF5541EAA87FC2EBB5516DA8ACA04EE5E46B15CEAA911F21",
			"key": "6E32697A4E1DBD556775C8B3358134FC",
			"aad": "8669C361"
		}
	]
}

**Issue**
I expected the test case to include the "iv" element. The first 315 test cases are all ""direction": "encrypt"" and DO NOT include "iv" element. The following 315 (316-630) test cases are all ""direction": "decrypt"" and DO include the "iv" element.

**Comment by Kritner** [comment]
Your registration signifies that the IUT generates the IV internally - for an "encrypt" operation, that means that the IUT needs to provide the IV within their responses.  If your intention is for the IUT to ***not*** generate the IV, then "external" `ivGen` should be used.

The internal IV generation is (I believe) intended for IUTs that ***cannot*** inject an external IV for encrypt operations, they can internally create the IV with no hooks for injection.

For an "internal" iv generation "decrypt" operation, the IV will be provided to the IUT.

**Comment by woozypompanos** [comment]
Just found an email from earlier this month regarding this change:

"•	GCM write out IV in prompt file only when "external" for encrypt operations, or always for decrypt"

so this isn't actually a bug.

Thank you @Kritner for your response. I guess vendor used the provided IV for encryption when we sent them sample vectors before this change took place so they were confused when the new request file was different.
