### ISSUE TITLE
Can't submit results due to vector set in "error" status

### ISSUE THREAD

**Issue by woozypompanos** [usnistgov/ACVP-Server#119]
**environment**
Demo

**testSessionId**
186400

**vsId**
611792

**Current Results**
When performing 'GET /acvp/v1/testSessions/186400/results' both 611792 and 611797 return "status": "error"

[
  {
    "acvVersion": "1.0"
  },
  {
    "passed": false,
    "results": [
      {
        "vectorSetUrl": "/acvp/v1/testSessions/186400/vectorSets/611791",
        "status": "passed"
      },
      {
        "vectorSetUrl": "/acvp/v1/testSessions/186400/vectorSets/611792",
        "status": "error"
      },
      {
        "vectorSetUrl": "/acvp/v1/testSessions/186400/vectorSets/611793",
        "status": "passed"
      },
      {
        "vectorSetUrl": "/acvp/v1/testSessions/186400/vectorSets/611794",
        "status": "passed"
      },
      {
        "vectorSetUrl": "/acvp/v1/testSessions/186400/vectorSets/611795",
        "status": "passed"
      },
      {
        "vectorSetUrl": "/acvp/v1/testSessions/186400/vectorSets/611796",
        "status": "passed"
      },
      {
        "vectorSetUrl": "/acvp/v1/testSessions/186400/vectorSets/611797",
        "status": "error"
      },
      {
        "vectorSetUrl": "/acvp/v1/testSessions/186400/vectorSets/611798",
        "status": "passed"
      },
      {
        "vectorSetUrl": "/acvp/v1/testSessions/186400/vectorSets/611799",
        "status": "passed"
      },
      {
        "vectorSetUrl": "/acvp/v1/testSessions/186400/vectorSets/611800",
        "status": "passed"
      }
    ]
  }
]

**Cause of Error**
The original response file had a bitstring variable with 63 characters which caused an issue since it's non-even

[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "BitStrings are expected to have an even number of hex characters. Value was \u00226A9F0446AF768D36D7BFE5A343F5816886B90EAB27561DF2BAA2E106963E6A8\u0022."
  }
]

**Current Issue**
when performing 'PUT /acvp/v1/testSessions/186400/vectorSets/611792/results' the result is:

[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "Vector set not in \u0027failed\u0027 status.",
      "Unable to submit results when vector set in \u0027error\u0027 status."
    ]
  }
]

**Expected Result**
I expected the new response file information to be uploaded and then continue into verification process.

**Additional Information**
If I do 'POST /acvp/v1/testSessions/186400/vectorSets/611792/results' I get the result:

[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "Vector set not in \u0027processed\u0027 status.",
      "Unable to submit results when vector set in \u0027error\u0027 status."
    ]
  }
]

**Comment by Kritner** [comment]
Ah thanks, we're currently only allowing `PUT`s against this endpoint when the vector set is in a "failed" state, where we seemingly be allowing it for both "failed" and "error" states.  I'll get this into the next release.

For this vector set, you could either resubmit the capabilities under a new registration. Otherwise I could have someone remove the previously submitted answers and set the state back to an unprocessed one.  The former option will be faster and doesn't require anything additional on our part; let me know!

I'll at least keep this ticket open tracking the API change around "failed" and "error" states for the `PUT` operation against the `/acvp/v1/testSessions/{tsId}/vectorSets/{vsId}/results` endpoint

**Comment by woozypompanos** [comment]
@Kritner Can you please have someone remove the previously submitted answers and set the state back to an unprocessed one? At least for the 611792 and 611797 vector sets. Thank you

**Comment by Kritner** [comment]
Both of those vector sets should be available to have their answers submitted again.
