### ISSUE TITLE
AES-XPN on demo: "error" disposition with zeroed out test responses instead of "fail"

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP-Server#12]
**environment**
Demo

**testSessionId**
117174

**vsId**
335684

**Algorithm registration**
[{"acvVersion":"1.0"},{"algorithms":[{"algorithm":"ACVP-AES-XPN","revision":"1.0","prereqVals":[{"algorithm":"AES","valValue":"same"},{"algorithm":"DRBG","valValue":"same"}],"direction":["encrypt","decrypt"],"ivGen":"internal","saltGen":"external","ivGenMode":"8.2.1","keyLen":[128,256],"tagLen":[128],"payloadLen":[16,128,136,256,264],"aadLen":[0,128,136,256]}]}]

**Endpoint in which the error is experienced**
/acvp/v1/testSessions/117174/results
/acvp/v1/testSessions/117174/vectorSets/335684/results

**Expected behavior**
Expected a "fail" disposition for VS 335684. Got "error" disposition.

**Additional context**
Working to add aes-xpn support to libacvp despite not having a crypto implementation to test with. So, am testing with zeroed out test responses. I would expect a fail disposition but am getting an error and am unable to retrieve the the results for the vector set as well - I get an error `    "error": "Object reference not set to an instance of an object."`

The previous session run as sample, 117173, had the expected "fail" disposition and reasoning, with the exact same algorithm registration. Compared the expected results to my output results and the objects within the test cases seemed to match up (with the exception that we include testPassed: true and the server only seems to require that value when testPassed: false)

Thanks,
Andrew

**Comment by celic** [comment]
One curious thing here is that the saltLen is 96, but an empty salt is given in the prompt.

**Comment by celic** [comment]
That piece is very suspicious to me and would suggest that your results file is fine as is. I'll dig into this today.

**Comment by celic** [comment]
A fix is in our pipeline and will go out to demo soon.

**Comment by celic** [comment]
This is out on Demo now.

**Comment by Kritner** [comment]
this change is now on production https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.12

**Comment by abkarcher** [comment]
Hello,

I just had an opportunity to retest this again and it seems to persist - test session 120324 (demo), which was marked as sample gives the expected "fail" output but test session 120317 gave the "error" disposition with the `"error": "Object reference not set to an instance of an object.` at the results endpoint for the vector set (VS 351790).

Thanks,
Andrew

**Comment by Kritner** [comment]
I see the issue. I'll put in a fix, thanks for following up!  I'll let you know when the change is on demo.

**Comment by Kritner** [comment]
This change is on demo in release [v1.1.0.13](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.13).

**Comment by abkarcher** [comment]
Hello,

Just ran through it again and it seems to fail as expected now. Thanks!

Andrew

**Comment by Kritner** [comment]
This change is now on prod in release https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.13
