### ISSUE TITLE
RSA sigGen verification issue

### ISSUE THREAD

**Issue by kwong-cygnacom** [usnistgov/ACVP-Server#120]
**environment**
Demo

**testSessionId**
186521

**vsId**
612903

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov/acvp/v1/testSessions/vectorSets/results\ GET

**Expected behavior**
The failure message: "Incorrect e, must be greater than 2^16, less than 2^256, odd" does not seem to point to the real cause of failure as the two values of e seem to match the criteria.

      {
        "tgId": 1,
        "n": "9FA2D1352739A4DBF4E002EA2EBB5A66704B7850D4611E7CC2660F9AA89A667E9DAAE5471F45F46542AC6C2BA5AFE169213AF46036BAF0D682C2D4BC7BB2569C61E49471BCCF30563FBCD188A3D2CB174B8D7DF65F97C536726B6D03FCF789979F0719D9737A45DD45C4F84E6E0B5C1BDF38D397BD4AD4844D596DB025767EFA8F1E11CC2CB4C1176E0BE2D9F8D265C65CD03239006E94BA6E2425CA81DB7C2B87464685EB022B0A854229E861F8DBE6385926B75E5D2005770963DF09CA6D63ECA63DE2F1EEB3DE4CD78E7DABB31B9DA8F86F1ACF8CF79E472AB3608A1217DCFD52A4E3B664845AF0C30BCBA8B4A1D83533D5BDD4EDCA9E0B4EEB1318318F7B",
        "e": "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000001",
        "tests": [
          {
            "tcId": 1,
            "signature": "03B5B5A39B24CF6C318F260940DDB2F13F87AF0714429928F8A31B85AC2B91237B7B418FCD05D10B41CAE351637665C3464408F424A5F28A8B2C1807732B6913B0D5F8351E8495BDCB5699757E1D5CDE5FE6C28E4C2B374D62513FA822B2FAE78A5AB08C2DA5FA8181F7BA587E851E279D3828D3148016D977E16AAD4F783AEDF2520488366D6F402554D0C26F48186C8FD663B906E987658121BBAF1C21988E7C24495A60CC5C60AF4821C72EA04D7555F90C5E6BE44234CE9798A463F436EC7C8EC4A3FBE3EC0C4317F57105073BC37CFCD7B20A992625FE254342242BEF1F29F7B06FCB42D8283BD1253F64DC5BFA9E7700B2919F5FB734850EAAF306F5BE"
          },
...
      {
        "tgId": 9,
        "n": "E41E78E1EE16559343A7EF74FB20C936D2367360CC782D5A5BBEF70EEF0699626F8F7D9F69BD9AC67EDA7D4E5CECDF80E4C2F023B101C3C229F94690370CFDCC005363F9E201606A34EF670A07A078DB3865A731FF1B882123CD0687B8FB7659C273099F4F014D12EF8871AFC555E474C74B9E4277B7EA7240EE75A9B62D641640F398B07AAACCCC305BDF06D984FA8D1A5296F63B53AF7BF5750F5197C3065B68E0B0546714E940CDF921B8D5B411DA72C5685AB70ADC7F02409A602D6998770F0836E9DCF838A569514C352A939907C7FA5BC54ABEE538B114D6002BF59409ABD6F1A58D917E288906DEB3995B6FAA5DC0661FAB4D7EDC2DB7F22C73F795E81C7F7CDDF0FC6933808103C02F749ECCAA81246E34C0B8C113D7415B08C83EA77E7D590EA2627763153F9FA7853CD8DF82029228E649387DBCE75EB5A125319A8B79B2968189759F40315C8406F5D2377EC0BCBEBF7B8B13A1AFD6275E74BAAFD9ABE02A21F40272E3BC082D00EBA12D029B845E80A2D1C065125232034D9F9D59166D257F3780F5E87CC5EEB0128E60C3C955B0507B0B53C78CC53157C35162A7C5779C64D7894CD609A2705F67B90B23137C77BE6B59DA102E3FA80983DC37B7373345497ADA817C8A20D952C724EAC2B8CD0DB44908A2D463A3E16BDDF7DB1EDD597E88D4331679442CA687094ED77FE53FFBF08ADCABE8D617E0B99C5989",
        "e": "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010001",
        "tests": [
          {
            "tcId": 81,
            "signature": "15386EDF2C5F64104FB18984EE51763948BD472134E8B5B7CA267F6E901E5AD896F964512820F05F2E5FC0BAEDADC7487447D3B8B52E834ADB84AB5D293E9B1FAC528480BE10EC62891462592557EF4BC04D96A5FFF29458D039A8B6C6957C880020D2EBBA3F59A7828A5427A85B74BB8E218894FB0E6F519888A0EA374BA8F83B3F9C08058D254FA0F85BBB828533061D4457DCBDDAFCFC5BD14F1AE4B172D5BEE9B565B20F260E2251E19160EF8377FDF3BA19360A04498E87E00188A4B0EA06AF4443CD49D825C34EAEC36247C5B5A2710F0859E413BC517E0103DBEFE686D8BA406F3B524BB55782B36CBF30B3A21D5849F913DF8F54080C796F786733AF7CCDDD012B17D9840B05A13DDA31678F3ECF0D458DF15C85DD8FCF6ABAA2643D1655977DD5A385D789A3BF0C8FE8D2261FB7ECCA4CB400063518E6FFEF216B9D0D4A094C5A13EF1D894DE6C83695DE382F87AC22A42F992C78FE3BF61AC529B14EE29E9AEAE29C04A07CCF8A890EB4C5FE72D53B55ECB6C7B1F76A4A3DD468A7D8372F118FB8B9DD8C35278CB80815653F52B5EF02EB567D7FB0BC52D24E3D7A6E6EB286A4DE1F49E9B909C1D88289EF3F3993524FD01AE4AA2721EC6C197A5A1E3730AAB85BB25CD7D743C2BE95B1EA143CFCAE7F866D2B97A1C66D198630101AA45D29428CDD6B703AF1CEF72DB715581E13AE5508BB5A1585A544BFB6D919"
          },
...

**Additional context**
The response file and error file are uploaded for reference.
[RSA-sigGen-response-612903.JSON.txt](https://github.com/usnistgov/ACVP-Server/files/6793675/RSA-sigGen-response-612903.JSON.txt)
[612903-validation-result-failed.json.txt](https://github.com/usnistgov/ACVP-Server/files/6793680/612903-validation-result-failed.json.txt)

**Comment by Kritner** [comment]
@kwong-cygnacom I just successfully ran the attached response file against that vector set in a local environment.  Additionally, this vector set is in a "passed" state on our demo system.  Was the same file attempted a second time, and it worked then?

Since I'm not seeing the issue locally, even with the GH attached response file from your comment: https://github.com/usnistgov/ACVP-Server/files/6793675/RSA-sigGen-response-612903.JSON.txt I'm not sure what should be next.

There is another vector set within the test session that is not yet in a passed state, could the issue be around that vector set instead?

612903 is in a passed state, and the subject of the posted issue.
612902 is in a state where it is awaiting a response file submission.

**Comment by kwong-cygnacom** [comment]
The second attempt was a different file. Submitting result for other vector set should not cause the issue as our client does not submit response if the vsId in a response file does not match the request. I would guess it may be user error on our side. Thanks for taking the time troubleshooting the issue.
