### ISSUE TITLE
PUT on testsession returned 400

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP-Server#122]
**environment**
demo

**testSessionId**
188767

**Algorithm registration**
N/A

**Endpoint in which the error is experienced**
PUT /acvp/v1/testSessions/188767 HTTP/1.1

**Expected behavior**
Request for certificate filed

**Additional context**
The server however returned:

```
: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request</h2>
<hr><p>HTTP Error 400. The request is badly formed.</p>
</BODY></HTML>
```

**Comment by Kritner** [comment]
Hey @smuellerDD what date/time was this `PUT` attempted, and with what payload?  This doesn't appear to be a request that would have even "gotten far enough" in the process to hit our code, as that looks to be more of a webserver response rather than a response that has been processed by our service.

**Comment by smuellerDD** [comment]
There is no data sent to PUT - just a PUT on the test session to get a certificate request.

The date / time the server responded was 09:57:04 MEST.

**Comment by Kritner** [comment]
According to our web server logs, that request is a being returned as a 403.7 (though it seems in the HTML you posted in the initial issue only a 400 is returned?).  403.7 is "missing client certificate" as details of that subcode.  Would something be excluding your client cert for that type of request only? I see there are other 200s from your client today.

**Comment by smuellerDD** [comment]
I would not see that the client cert is missing. Let me investigate further.

**Comment by smuellerDD** [comment]
Closing: the issue is that the client used HTTP 2.0 and then switched back to 1.1 as the server did not support it. Yet, the switch somehow caused some data to be not submitted. By forcing my client to use 1.1, the communication works.
