### ISSUE TITLE
KAS ECC/FFC noKdfNoKc got rejected

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP-Server#125]
**environment**
Both

**Algorithm registration**
` {
    "algorithms":[
        {
            "function":[
                "keyPairGen"
            ],
            "scheme":{
                "ephemeralUnified":{
                    "kasRole":[
                        "initiator",
                        "responder"
                    ],
                    "noKdfNoKc":{
                        "parameterSet":{
                            "ec":{
                                "hashAlg":[
                                    "SHA2-512"
                                ],
                                "curve":"P-256"
                            },
                            "ed":{
                                "hashAlg":[
                                    "SHA2-512"
                                ],
                                "curve":"P-384"
                            },
                            "ee":{
                                "hashAlg":[
                                    "SHA2-512"
                                ],
                                "curve":"P-521"
                            }
                        }
                    }
                }
            },
            "algorithm":"KAS-ECC",
            "revision":"1.0"
        }
    ]
}`

**Endpoint in which the error is experienced**
['KAS-ECC-1.0: At least one KAS mode must be provided.']

And if we changed it to "kdfNoKc", it's working fine.

**Comment by Kritner** [comment]
`noKdfNoKc` is only valid for `KAS-ECC` / `Component` / `1.0`.  "noKdfNoKc" is a "component style test" and needed to be separated from the root "algorithm name" for reasons of validations being issued if I'm remembering correctly.  I believe this has caused issues in the past, and is part of the reason the "component" style testing now has the label of "SSC" (shared secret computation) for Sp800-56Ar3 and Sp800-56Br2 testing - which I would recommend moving to if you are able.  The registrations are a bit simpler to work with as well (IMO) in comparison to the "1.0" revision of KAS testing.

**Comment by AndrewHYang** [comment]
Got you. Thanks
