### ISSUE TITLE
Vector set validations fail on Demo with "internal server error"

### ISSUE THREAD

**Issue by mmccarl** [usnistgov/ACVP-Server#126]
Demo System

beginning after the maintenance completed on July 19, we have been unable to do vector set validations on the Demo system.

two such examples are:

2021-07-20 01:52:03 tsId-187316 vsId-617570
2021-07-20 01:52:08 tsId-187316 vsId-617571

we received the following response to each attempt with http status 500:
[
            {
                "acvVersion": "1.0"
            },
            {
                "error": "Internal service error. Contact service provider."
            }
]

Further, attempting to access the testsessions endpoint for any tsId seems to result in http error 403 Forbidden.

validation requests to Prod seem to be working fine.

**Comment by Kritner** [comment]
@mmccarl I need to get the kids from school then get started on dinner, probably won't be able to get to this today, but a few clarifications:

> 

> Demo System
> 
> beginning after the maintenance completed on July 19, we have been unable to do vector set validations on the Demo system.
> 
> two such examples are:
> 
> 2021-07-20 01:52:03 tsId-187316 vsId-617570
> 2021-07-20 01:52:08 tsId-187316 vsId-617571
> 

What are these examples of? From which endpoints, and with what payloads?

I see the following requests in our webserver log:

```
2021-07-21 20:04:30 10.200.159.218 GET /acvp/v1/testSessions/187316 - 443 - 10.200.1.41 axios/0.21.1 - 403 0 0 202
2021-07-21 20:05:07 10.200.159.218 GET /acvp/v1/testSessions/187316/vectorSets/617570 - 443 - 10.200.1.41 axios/0.21.1 - 403 0 0 198
```

but nothing about the mentioned `617571` vector set within the past 3 days.

A 403 on the webserver level (never having reached out internal code) points to a client certificate issue.

> we received the following response to each attempt with http status 500:
> [
> {
> "acvVersion": "1.0"
> },
> {
> "error": "Internal service error. Contact service provider."
> }
> ]
> 
> Further, attempting to access the testsessions endpoint for any tsId seems to result in http error 403 Forbidden.
> 
> validation requests to Prod seem to be working fine.

Looking through our internal logs, I see several bad JWT verify attempts from the company associated with that test session.  Did you recently go through a certificate renewal, or something similar?  The JWT either is not verifying against the client certificate, or perhaps some additional characters were placed into it accidentally?

**Comment by Kritner** [comment]
I just doubled checked, and the certificate subject claims at the time of creating the JWT being used ***do not*** match the certificate subject that is being provided for the mTLS connection.  This is why the JWT is failing to verify - the subject claims between the client certificate and the JWT must match.

**Comment by jarnold01** [comment]
Yeah @Kritner , their cert was recently renewed (issued 7/19/21 @ ~6:40pm EDT)

**Comment by jarnold01** [comment]
I have just re-issued the renewal cert so that the JWTs will match and existing Test Sessions should be accessible. Please let me know if this corrects the issue. Thanks.

**Comment by jarnold01** [comment]
As there has been no further discussion on this issue for almost a week, I'm going to close it out. If there is still an issue that requires our attention with regard to this, please feel free to add a comment and re-open it. Thanks.
