### ISSUE TITLE
Unable to submit responses on Demo

### ISSUE THREAD

**Issue by dmomy** [usnistgov/ACVP-Server#127]
I am having issues trying to submit responses.    When the command is issued to submit responses I have no reply back from the demo acvp server.  Behavior not seen on production.  The session id is 191399.

**Comment by livebe01** [comment]
Hi @dmomy, is there any additional information that you can provide?

Looking through our logs, it looks like you were able to successfully download the vector set prompts along with the expected results on 7/21, but I don't see any POSTs to /acvp/v1/testSessions/191399/vectorSets/*/results (that would indicate attempts to submit responses). 

All of your 7/21 traffic shows up as "Go-http-client" in our IIS logs and then on 7/22 we see an attempt to get a vector set listing using "axios." That 7/22 attempt returned an HTTP 403 or forbidden.
![Screen Shot 2021-07-23 at 10 40 59 AM](https://user-images.githubusercontent.com/26742402/126798611-5dc1ff3f-f29a-49eb-ac89-00d42e583d95.png)

**Comment by livebe01** [comment]
Closed due to inactivity. Reopen this ticket if you have additional questions related to it.
