### ISSUE TITLE
KAS-FFC/ECC: key verification tests not always performed?

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP-Server#129]
In the distant past, I performed KAS-ECC/FFC tests with the Linux kernel which failed. This lead to the discovery that the ACVP testing has some tests verifying the presence of the key verification logic compliant to SP800-56A rev 2 section 5.6.2.3 (full/partial validation) because the Linux kernel did not have that support.

Fast forward to today: we successfully performed KAS-ECC/FFC tests on module implementation where we know for a fact that the key verification tests are not implemented. Yet, the ACVP testing succeeded. Note, I have observed such results also previously for other modules. But then, other ACVP tests (correctly) failed a DH/ECDH implementation due to the missing key verification tests.

Thus, my question: Is the ACVP testing not always generating vectors that can validate the enforcement of the key verification requirements? If so, may I suggest to change the ACVP behavior to always test for it? Note, CMVP requires that the FIPS validation must check the presence and effectiveness of the key verification functionality. This could be achieved with ACVP if we can rely on the fact that such test is always performed.

**Comment by livebe01** [comment]
Hi @smuellerDD, I asked around a bit on our end and there's a consensus that CAVS supported and 56A KAS 1.0 supports testing public key validation. We're not certain that we've ever included that functionality in KAS 56Ar3, but we can say that we do not currently offer support for testing it for KAS 56Ar3.

**Comment by livebe01** [comment]
PS I'll close this ticket for now, but feel free to reach out or reopen it if you have additional questions. Thank you!

**Comment by smuellerDD** [comment]
Allow me to ask whether such key check test would make sense even for SSC considering IG D.H which mandates that the validation shall verify that the module implements the key checks following 56A rev 3 section 5.6.2.

**Comment by livebe01** [comment]
Hi @smuellerDD, can you clarify: 
1) did you mean to refer to "SSC" in your recent comment? 
2) which IG are you referencing? FIPS 140-3 IG D.H pertains to vendor affirmation to SP 800-133.
