### ISSUE TITLE
Demo server RSA decryptionPrimitive returns "Incorrect number of failures"

### ISSUE THREAD

**Issue by harrywangca** [usnistgov/ACVP-Server#13]
Url: https://demo.acvts.nist.gov:443/acvp/v1/testSessions/117418/vectorSets/336834/results

I had a RSA decryptionPrimitive test, "totalFailingCases" is 10. I managed to generated the response with 10 failed cases, but the Demo server returns:

        "tcId": 1,
        "result": "failed",
        "reason": "Incorrect number of failures detected"

The return is the same if my response have 20 failed cases.

What could be wrong?

Harry

**Comment by harrywangca** [comment]
The results  in the last link may have some problem, please check this one:

Url: https://demo.acvts.nist.gov:443/acvp/v1/testSessions/117549/vectorSets/337966/results

**Comment by celic** [comment]
To start off, 337966 failed because the server expects exactly 10 failing cases to be provided. 

I'll say the RSADP tests are not ideal and are being discussed internally. 

For 338029, well both, you must include the `testPassed` property described in the RSA Specification. The response should look like this...

```
{
  "vsId": 0,
  "algorithm": "RSA",
  "mode": "decryptionPrimitive",
  "revision": "1.0",
  "testGroups": [
    {
      "tgId": 1,
      "tests": [
        {
          "tcId": 1,
          "resultsArray": [
            {
              "e": "60BDBEF656869D",
              "n": "8FA73CF9CAD37456B...",
              "testPassed": false
            },
            {
              "plainText": "009EDAE2D5934F...",
              "e": "D6AA5EF807",
              "n": "A86A73D47F605DCF...",
              "testPassed": true
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by harrywangca** [comment]
Oh, it's my oversight to this recent ""testPassed": true" change. Now everything works. Thank you.

Harry
