### ISSUE TITLE
DRBG test input and SP800-90B compliance

### ISSUE THREAD

**Issue by dghgit** [usnistgov/ACVP-Server#130]
We're currently working on a new module which incorporates the health tests in SP 800-90B section 4 for verifying it's entropy source.

Recently we had a failure on demo which turned out to be this vector:
{
    "vsId": 650868,
    "algorithm": "ctrDRBG",
    "revision": "1.0",
    "isSample": false,
    "testGroups": [
    
      {
        "tgId": 3,
        "testType": "AFT",
        "derFunc": true,
        "reSeed": true,
        "predResistance": true,
        "entropyInputLen": 320,
        "nonceLen": 320,
        "persoStringLen": 320,
        "additionalInputLen": 320,
        "returnedBitsLen": 512,
        "mode": "AES-192",
        "tests": [
          {
            "tcId": 34,
            "entropyInput": "850003557FE2617B03727B39CBE6E6E6E67633E2B40BBD894A13C1B39DE30DB2BA0B57F1B91B5D4B",
            "nonce": "07734E31FAD886BD85F494DF5222E09A378040710AD234E618123B52BA6835F17296DF732801E8DB",
            "persoString": "E1247C66FEB9CBC098E71863CCFCE2415D9343BC928DCA679B13F6312198C94E3FB0B81204DA7350",
            "otherInput": [
              {
                "intendedUse": "generate",
                "additionalInput": "A6F3C33F83EADAD9BC9A5D37C22186D552D600EB09C6669EB2A50733E2F012E87DE95AC0C9772986",
                "entropyInput": "87379B7C6001B9E2FEC852E0DF23FA01B48DB6AD7161105716BD397B03849DA4B7DF0E04C81B2B68"
              },
              {
                "intendedUse": "generate",
                "additionalInput": "F4F05D77F27F0434497D5735B4A2E7DDF1BD71DC2E556B60EA6DB8CF1A30633EABE7849BE8AF47BB",
                "entropyInput": "EFF0080944F82073DA72211D590933788B4526393AF42452869B2DD415C14F13DACAE562CEF6A611"
              }
            ]
          }
        ]
      }
    ]
  }

The issue is the 4 E6's in the entropyInput string are 1 too many for the Repetition Count Test (also known as the stuck test) in section 4.4.1 which is regarded as a catastrophic failure assuming the input source is produce 8 bits of entropy per 8 bit sample, so when the entropyInput is making it's way to the DRBG implementation the module falls over as it detects the problem.

We can configure our way around this for testing purposes, but I thought I should mention it as others may not be so fortunate. I think the solution is to just make sure the random entropy generated for the tests doesn't make an SP 800-90B stuck test fail (so no runs of more than 3 bytes).

**Comment by livebe01** [comment]
Hi @dghgit, that's an interesting scenario that you're describing. When we wrote the DRBG tests, I'm guessing that we were expecting the input values to be input directly into the DRBG vs being input into the DRBG via a module's 90B Continuous Health Tests. I'll close this ticket for now, but we can look into putting in a change for this if we hear back that this is becoming a common issue. Thank you!
