### ISSUE TITLE
ctrDRBG created fewer test groups

### ISSUE THREAD

**Issue by kwong-cygnacom** [usnistgov/ACVP-Server#131]
**environment**
Demo

**Algorithm registration**
[
  {
    "acvVersion": "1.0"
  },
  {
    "isSample": false,
    "publishable": true,
    "algorithms": [
      {
        "algorithm": "ctrDRBG",
        "revision": "1.0",
        "predResistanceEnabled": [
          true
        ],
        "reseedImplemented": false,
        "capabilities": [
          {
            "mode": "AES-128",
            "derFuncEnabled": true,
            "entropyInputLen": [
              128
            ],
            "nonceLen": [
              64
            ],
            "persoStringLen": [
              0,
              128
            ],
            "additionalInputLen": [
              0,
              128
            ],
            "returnedBitsLen": 512
          },
          {
            "mode": "AES-256",
            "derFuncEnabled": true,
            "entropyInputLen": [
              256
            ],
            "nonceLen": [
              128
            ],
            "persoStringLen": [
              0,
              256
            ],
            "additionalInputLen": [
              0,
              256
            ],
            "returnedBitsLen": 512
          }
        ]
      }
    ]
  }
]

**Expected behavior**
The server generated request with 8 test groups (ctrDRBG-request-528415.json.txt) in April.
Now the server only generated request with 4 test groups (ctrDRBG-request-657629.json.txt).

The 8 test groups covered 8 (persoStringLen/additionalInputLen) combinations for AES-128 mode and AES-256 mode:
AES-128: (0, 0), (0, 128), (128, 0), (128, 128)
AES-256: (0, 0). (0, 256), (256, 0), (256, 256)

The 4 test groups covered 4 (persoStringLen/additionalInputLen) combinations for AES-128 mode and AES-256 mode:
AES-128: (0, 128), (128, 0) 
AES-256: (0, 256), (256, 0) 

Some combinations were missing.

**Additional context**
[ctrDRBG-request-528415.json.txt](https://github.com/usnistgov/ACVP-Server/files/6941878/ctrDRBG-request-528415.json.txt)
[ctrDRBG-request-657629.json.txt](https://github.com/usnistgov/ACVP-Server/files/6941880/ctrDRBG-request-657629.json.txt)

**Comment by livebe01** [comment]
Hi @kwong-cygnacom, what you are observing is the expected behavior. Since April we made a change to the test such that it no longer tests the Cartesian product of those options. Please let us know if you have any further questions.

**Comment by kwong-cygnacom** [comment]
Thank you for the explanation.
