### ISSUE TITLE
Demo server not processing Vector Responses

### ISSUE THREAD

**Issue by mmccarl** [usnistgov/ACVP-Server#132]
**environment**
Demo

**testSessionId**
194591

**vsId**
664804, 664805, 664806

**Algorithm registration**
ACVP-AES-CBC, ACVP-AES-ECB, ACVP-AES-GCM

**Endpoint in which the error is experienced**
/acvp/v1/testSessions/194591/vectorSets/664804/results 

**Expected behavior**
return of the verdicts

**Additional context**
only returns "retry 30"

i submitted 3 vector set responses (listed above) on 2021-08-11 at 12:05 GMT.  as of 15:30 GMT the request for results still replies "retry 30".  The health check of the demo server has been reporting 'healthy'.

**Comment by jbarnesweb** [comment]
Same issue for me.

Also, vector download requests are similarly impacted.

**Comment by Kritner** [comment]
Someone is looking into it now, thanks!

**Comment by Kritner** [comment]
We had a problem with an internal system, at this point it looks like the queue of work is all caught up.  Closing, but let us know if you're still seeing anything amiss.

**Comment by jbarnesweb** [comment]
I still see the issue from vectors submitted last night. retry: 30

**Comment by mmccarl** [comment]
i still see the "retry 30" too

**Comment by Kritner** [comment]
Ok, taking another look. please stand by, and thanks for your patience!

**Comment by Kritner** [comment]
There was an issue with an internal queue where the posted files weren't persisted correctly, which left the test sessions in a bad state.  The state of the vector sets now should be reset to a point where they can accept the response files post again.  We'll be looking into changing our internal processes to avoid this in the future.

You should be good to attempt to *resubmit* your answers for the problem vector sets, as the previous submit files were not recovered in the bringing back up of the environment yesterday.  I'll leave this open until I hear back that you've been able to get through with a resubmission.

**Comment by mmccarl** [comment]
i re-submitted vector set 664804, but it appears to be back in the 'retry 30' state.

**Comment by Kritner** [comment]
Seems like we're still having some issues with data movement between our internal and public environments.  Not sure what the underlying cause is at the moment, but the file that wasn't being moved out to the public environment (in this case your, along several others) validation files are now there.  

Can you try again?  I'll continue leaving this issue open for now.

**Comment by mmccarl** [comment]
i can now get the results for vsId 664804.  i re-submitted 664805 and 664806 and got the verdicts.

i have a bunch of vector generation requests made during this period that i need to verify, so please keep this open for a bit longer.  i'll comment when i've completed my check. (i already know i get a 'retry 30' when i query testsessions/194848)

**Comment by Kritner** [comment]
Yeah I believe that all of the generation requests that came in during the environmental issue will need to be created as new test sessions unfortunately, the registration content itself never ended up making it to our internal queue.

**Comment by jbarnesweb** [comment]
Me too.

**Comment by Kritner** [comment]
Thanks all!
