### ISSUE TITLE
***ACVP [STATUS][acvp_login:2509]--> Logging in... segmentation fault

### ISSUE THREAD

**Issue by gmarkan** [usnistgov/ACVP-Server#133]
**environment**
The environment the issue was experienced - Demo 

**testSessionId**
None - login issues

**Endpoint in which the error is experienced**
root@123libacvp# app/acvp_app --verbose --aes

Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    /home/mchp/libacvp/libacvp/certs/mozzila_trust_anchors.pem
    ACV_CERT_FILE:  /home/mchp/standard_libacvp/certs/Microchip_Goutham_Markandeya_Demo.cer
    ACV_KEY_FILE:   /home/mchp/standard_libacvp/certs/Private_nopasscode.key

*****ACVP [STATUS][acvp_login:2509]--> Logging in...
***ACVP [INFO][acvp_http_user_agent_handler:483]--> HTTP User-Agent: libacvp/1.0;Linux;4.4.0-210-generic;x86_64;Intel(R) Xeon(R) CPU E5-2609 v3 @ 1.90GHz;GCC/5.3.1

Segmentation fault (core dumped)**

**Expected behavior**
I was expecting login to be successful

**Additional context**
I received the seed and .cer file from NIST and updated the nist_setup.sh file with correct path to CERT and KEY file, copied the seed I received. Am I missing something? why segmentation fault?
Thanks in Advance

**Comment by gmarkan** [comment]
I did single-stepping to see where execution is hitting segmentation fault, it failig in 
File : acvp_transport.c
Function: acvp_curl_http_post calls curl_easy_perform(hnd)

As soon as the execution reaches to curl_easy_perform, I get segmentation fault

curl version =curl 7.73.0 (x86_64-pc-linux-gnu) libcurl/7.73.0 OpenSSL/1.0.2g-fips zlib/1.2.8
openssl version = OpenSSL 1.1.1g  21 Apr 2020
libacvp commmit ID=  96326606965

**Comment by Kritner** [comment]
@gmarkan it sounds like you're describing an issue with the client you're attempting to use, not the actual ACVP service - you might be better off reading the documentation or opening an issue with the client repository [libacvp](https://github.com/cisco/libacvp/)

**Comment by gmarkan** [comment]
Hello, 
Looks like the app and library are both trying to link to two different versions of OpenSSL (libcrypto/libssl).
installed again and issue is resolved, thank you.
