### ISSUE TITLE
vectorset validation error "a task was canceled" on aes-ecb validation

### ISSUE THREAD

**Issue by mmccarl** [usnistgov/ACVP-Server#137]
**environment**
Prod

**testSessionId**
9421

**vsId**
90850

**Algorithm registration**
{
                "ptLen": [
                    128
                ],
                "keyLen": [
                    128,
                    256
                ],
                "direction": [
                    "encrypt"
                ],
                "revision": "1.0",
                "algorithm": "ACVP-AES-ECB",
                "prereqVals": []
            }

a response to vector set 90850 was submitted to Prod and received the message 'a task was canceled' instead of a verdicts response.  after manually reviewing the response, it was discovered that the vendor supplied only 3 entries in each 'resultsArray' for the monte-carlo tests instead of the required 100.  we're assuming that this is the problem, but the error response is not helpful.

rather than report 'a task was canceled', the system should report the offending test cases as 'failed' in the verdicts response.

**Comment by livebe01** [comment]
Thanks for letting us know about this. We'll make sure this gets fixed.

**Comment by livebe01** [comment]
This change is on Demo in release [v1.1.0.23](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.23)

**Comment by livebe01** [comment]
This change is on Prod in release [v1.1.0.23](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.23).
