### ISSUE TITLE
cSHAKE hexCustomization behavior doesn't match specification 

### ISSUE THREAD

**Issue by RKinsey** [usnistgov/ACVP-Server#141]
**environment**
Demo  

**testSessionId**
199236-199239 and 199325  

**vsId**
692695-692705 and 693227-693232

**Algorithm registration**
To save space, I'm going to only use one of the algorithms, the shared values were largely identical across the different capabilities registrations.

`[{ "acvVersion": "1.0" },{ "isSample": false, "algorithms": [{"algorithm": "KMAC-128", "revision": "1.0", "xof": [ true ], "hexCustomization": true, "msgLen": [{ "min": 256, "max": 512, "increment": 256 }], "keyLen": [{ "min": 256, "max": 512, "increment": 256 }], "macLen": [{ "min": 256, "max": 512, "increment": 256 }]}]}]`

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov/acvp/v1/testSessions/199238/vectorSets/[vsId] GET 

**Expected behavior**
`hexCustomization` was set true for all algorithms in all testSessions except the KMAC-128 in session 199238 (vsId 692704). This should only return hex strings by the spec,, but all provided both hex and ASCII customization strings.  
I'm not sure if the behavior is correct when `hexCustomization` is false, the spec isn't clear on whether that should return both ASCII and hex or just ASCII

**Additional context**
Doesn't seem to be impacted by whether or not the vector is a sample or in XOF mode

**Comment by Kritner** [comment]
I'm updating the specification in #1238, additionally here is some previous context into the explanation of the specification change:
https://github.com/usnistgov/ACVP-Server/issues/14#issuecomment-704370471.  The spec should have been updated at that time to make it a bit more clear, but hopefully this change does so.
