### ISSUE TITLE
ECDSA Signature Verification - Response mismatch (similar to #117)

### ISSUE THREAD

**Issue by sowndar-raj** [usnistgov/ACVP-Server#143]
Hi,

We have a few prod test vectors failing [similar to #117], below are the algorithm/session details with error log:

 Environment: PROD

 Algorithm: ECDSA SigVer

 Session ID: **9749, 9742, 9708**

 vsId: 

9749: 96668
9742: 96132
9708: 94798

Error [from session 9749]:

{
            "tcId": 871,
            "result": "failed",
            "reason": "modify key",
            "expected": {
               "testPassed": "False"
            },
            "provided": {
               "testPassed": "True"
            }
         }

 

All the vector IDs are failing with above mentioned error. We recently raised an issue #117 very similar to this. Although it is not failing for every prod session, we are getting this error for some of them and we have a handful of prod sessions (~16 sets) for which we are currently working on generating the responses.

 

Can you please recommend the next steps? Should we hold submitting the responses or keep submitting them and notify you with the failing vector IDs so that you can take a look at it from your side? Thanks!

**Comment by Kritner** [comment]
At a glance this does seem to be similar behavior. I'll look further into it shortly.  Can you provide the vsIds for all impacted vector sets?  We'll most likely be able to correct these specific ones, but I'll need to look into another root cause.

**Comment by Kritner** [comment]
ah reading again I see that you haven't necessarily submit responses for all of your ~16 sets that are ECDSA sigVer? 

* You could either go ahead and submit them all, and let me know if the issue presented in any of the sets (it seems that it's *most likely* to occur on b and k curves, but p curves should be pretty safe.) and we'll get them corrected on our side.
* We could regenerate the prompt files for the *potentially impacted sets*, which would give new x/ys, messages, r/s values for all of the sets, which may or may not have been impact by the problem.

**Comment by sowndar-raj** [comment]
Hi Kritner,

For the sessions which we have already submitted [3 sessions], can you please correct them on your side?


PROD Session ID | Status | Vector ID
-- | -- | --
9742 | Submitted   & Failed | 96132
9749 | Submitted   & Failed | 96668
9708 | Submitted   & Failed | 94798

Below are the session ID's for which we are yet to submit. We can regenerate responses, once the new prompts are made available for download:


PROD   Session ID |
--|
9723
9724
9725
9726
9727
9732
9735
9737
9743
9744
9745
9747

Also, can we please ask for an ETA for this? Thanks!

**Comment by Kritner** [comment]
> For the sessions which we have already submitted [3 sessions], can you please correct them on your side?
> 
> PROD Session ID	Status	Vector ID
> 9742	Submitted & Failed	96132
> 9749	Submitted & Failed	96668
> 9708	Submitted & Failed	94798

These three test sessions are now in a passing state.

> Below are the session ID's for which we are yet to submit. We can regenerate responses, once the new prompts are made available for download:
> 
> PROD Session ID
> 9723
> 9724
> 9725
> 9726
> 9727
> 9732
> 9735
> 9737
> 9743
> 9744
> 9745
> 9747
> Also, can we please ask for an ETA for this? Thanks!

The above test sessions are having their prompt files regenerated specifically for the ECDSA SigVer algorithms.  There's a fair amount of generation occurring between these vector sets and other activity, but new prompt files should becoming available shortly.  I'll update again once the generation has completed.

**Comment by Kritner** [comment]
I checked a handful of the test sessions in the above issue, and looks like they're published at this point, so I think the issue can be closed.  Let me know if there's anything else!
