### ISSUE TITLE
TLSv1.2: registration rejected

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP-Server#145]
The following is rejected:

```
      {
        "algorithm":"TLS-v1.2",
        "mode":"KDF",
        "prereqVals":[
          {
            "algorithm":"HMAC",
            "valValue":"same"
          },
          {
            "algorithm":"SHA",
            "valValue":"same"
          }
        ],
        "revision":"RFC7627",
        "hashAlg":[
          "SHA2-256",
          "SHA2-384"
        ]
      }
```

The error is:

```
[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "TLS-v1.2-KDF-RFC7627: No Hash Algs supplied."
    ]
  }
]
```

Could you please help me how the hash algs are to be supplied?

Small documentation update needed: the TLS specification uses the string "TLSv1.2" but it should be "TLS-v1.2".

**Comment by Kritner** [comment]
There is an issue open for this already, but I'll leave this open for the documentation update https://github.com/usnistgov/ACVP-Server/issues/139

**Comment by smuellerDD** [comment]
Am Montag, dem 13.09.2021 um 02:22 -0700 schrieb Russ Hammett:
> There is an issue open for this already, but I'll leave this open for the
> documentation update https://github.com/usnistgov/ACVP-Server/issues/139
> 

Thank you for the link.

Ciao
Stephan

**Comment by livebe01** [comment]
The documentation change has been made.
