### ISSUE TITLE
Purchasing Endpoint request format

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP-Server#147]
**environment**
Prod

We're getting an error while trying to submit a request to "POST /purchase".

And the example at https://github.com/usnistgov/ACVP-Server/wiki/ACVTS-Purchasing-Endpoints doesn't look like a valid JSON format.

**Comment by abkarcher** [comment]
Hello,

We ran into similar issues. The endpoint in our resolution was actually "/acvp/v1/purchase".

Hope this helps,
Andrew

**Comment by Kritner** [comment]
The opening and closing initial symbols should be start and end of array (`[` and `]`) rather than the current start object (`{` and `}`).

This should be similar to (I think) pretty much every other endpoint.  If the posted json is corrected does that solve your problem or has that already been tried?  

From the doc:

```
{
    {
        "acvVersion": "1.0"
    },
    {
        "items": [
            { 
                "purchaseOptionUrl": "/acvp/v1/purchase/options/2",
                "quantity": 3
            },
            { 
                "purchaseOptionUrl": "/acvp/v1/purchase/options/1",
                "quantity": 1
            }
        ]
    }
}
```

Should be:

```json
[
    {
        "acvVersion": "1.0"
    },
    {
        "items": [
            { 
                "purchaseOptionUrl": "/acvp/v1/purchase/options/2",
                "quantity": 3
            },
            { 
                "purchaseOptionUrl": "/acvp/v1/purchase/options/1",
                "quantity": 1
            }
        ]
    }
]
```

**Comment by AndrewHYang** [comment]
Hi @Kritner, I'm already using the edited format. Still, we're experiencing "Unable to deserialize body into two objects".
The only difference is we only have one item in the "items" array. Not sure if it's relevant.

And @abkarcher , we're using "/acvp/v1/purchase".

Thanks

**Comment by AndrewHYang** [comment]
Thanks, both. I found the root cause. It's because our end will automatically add the acvVersion again.
I will close this.
