### ISSUE TITLE
"SaltLen" missing from "kdfConfiguration" for HKDF (SP800-56Cr1)

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP-Server#150]
**environment**
Demo

**testSessionId**
205654, 205661

This appears to be a relatively recent development. saltLen was previously included in the kdfConfiguration object for HKDF and it is included in the spec ( https://pages.nist.gov/ACVP/draft-hammett-acvp-kas-kdf-hkdf.html, table 8.1.1). It does not seem to be present anymore. Is this an intentional removal? If so, is there a rule to follow as to what lengths to expect for salts for sake of input validation?

Thanks,
Andrew

**Comment by Kritner** [comment]
This change is on demo in release [v1.1.0.22](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.22)

**Comment by Kritner** [comment]
This change is on prod in release [v1.1.0.22](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.22)
