### ISSUE TITLE
[Feedback requested] Update TLS v1.3 testing to make better use of transcript hash with the given messages.

### ISSUE THREAD

**Issue by Kritner** [usnistgov/ACVP-Server#151]
**environment**
All environments

**testSessionId**
All test session IDs testing against TLS v1.3 KDF going forward (from time of release)

**vsId**
All vector sets that are testing the TLS v1.3 KDF going forward

**Algorithm registration**
Any `TLS-v1.3` / `KDF` / `RFC8446` registrations

**Expected behavior**
We received some feedback from a vendor around the TLS v1.3 KDF testing, specifically around the Transcript-Hash handling when it comes to deriving secrets for `clientApplicationTrafficSecret`, `serverApplicationTrafficSecret`, `exporterMasterSecret`, and `resumptionMasterSecret`.

Previously, we were doing the following method calls to calculate these values:

```cs
var clientApplicationTrafficSecret = DeriveSecret(masterSecret, "c ap traffic", clientHello, serverFinished);
var serverApplicationTrafficSecret = DeriveSecret(masterSecret, "s ap traffic", clientHello, serverFinished);
var exporterMasterSecret = DeriveSecret(masterSecret, "exp master", clientHello, serverFinished);
var resumptionMasterSecret = DeriveSecret(masterSecret, "res master", clientHello, clientFinished);
```

Where the above is not doing the intended "`first message` ... `last message`" but rather "`first message` || `last message`".  This is problematic as:

* It does not abide the RFC where the transcript hash is made up of all messages that are going back and forth between the parties
* Implementations can't "take out" messages that are already a part of the rolling hash that is the transcript hash, if that's how the internals of their implementation work.

I'm planning on moving forward with the following change to the above code for the calculation of the mentioned secrets:

```cs
var clientApplicationTrafficSecret = DeriveSecret(masterSecret, "c ap traffic", clientHello, serverHello, serverFinished);
var serverApplicationTrafficSecret = DeriveSecret(masterSecret, "s ap traffic", clientHello, serverHello, serverFinished);
var exporterMasterSecret = DeriveSecret(masterSecret, "exp master", clientHello, serverHello, serverFinished);
var resumptionMasterSecret = DeriveSecret(masterSecret, "res master", clientHello, serverHello, serverFinished, clientFinished);
```

Where the `DeriveSecret` function calls are now getting the first and last messages, with all other messages in between.  This seems to better fit the intention laid out in [RFC8446](https://datatracker.ietf.org/doc/html/rfc8446#section-7.1), with the caveat that we are still not making use of *all potential messages involved in the negotiation*.  Since the intention of the testing is to evaluate the implementation *of the KDF, and not the protocol itself*, I think we're still safe to go this route, though I'm curious on others thoughts.  Does this make sense to do? Is there anything glaringly obvious that is being missed?  

**Additional Context**
This will change the answer that was given in https://github.com/usnistgov/ACVP/issues/1237, as the testing is changing to be a "rolling total" of the messages, rather than the transcript hash just making use of the "first and last received" messages.

https://pages.nist.gov/ACVP/draft-hammett-acvp-kdf-tls-v1.3.html#section-9-9 does not seem to need an update, as the wording used already is indicative of a range `first||...||last`, not a concatenation of `first||last`.

**Comment by Kritner** [comment]
This change is on demo in release [v1.1.0.22](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.22)

**Comment by abkarcher** [comment]
Hello,

I'm definitely a bit late here giving feedback :) I will have to do a better job of keeping an eye on these issue pages. Anyway, I just had a thought or two for future reference.

I do understand the need to update the testing mechanisms in this particular case. However, it would be beneficial (as has been done once or twice previously) to have this communicated as potentially client breaking prior to release. Even though it does not necessarily create a change in the protocol or ACVP client itself,  it does require a change in the testing harnesses. Due to the low-level nature of most crypto handling code, it is not always the fastest process to get these changes on platforms being tested, especially in the middle of testing or when multiple platforms are being tested.

I wonder if there is some way the protocol could accommodate communicating things like this - changes to the test process/expectations but not the protocol itself (revisions are used for that). It is a rather rare case though.

Thanks,
Andrew

**Comment by livebe01** [comment]
@abkarcher, I wonder if it would be helpful to make use of our acvts-demo-users@list.nist.gov and acvts-prod-users@list.nist.gov mailing lists to draw more attention to test harness-breaking and client-breaking changes that we post here as issues?


trying to think abjout the best way to communicate client-breaking and test harness breaking changes.

**Comment by abkarcher** [comment]
hey @livebe01,

That would definitely be useful! It has been done once or twice before to do so if I recall. Any advance notice to get the change into the harness/client is beneficial. 
An extra bonus in a case like this would be if sample input/output test cases were provided to help us verify implementation correctness in advance; but its not really necessary.

Thanks,
Andrew

**Comment by livebe01** [comment]
Great, I think this is something we should be able to do. Thanks for the feedback!

**Comment by Kritner** [comment]
This change is on prod in release [v1.1.0.22](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.22)
