### ISSUE TITLE
Unable to submit certification request: "Test session must be in a passed state to be certified"

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP-Server#153]
**environment**
Prod

**testSessionId**
10552

**Endpoint in which the error is experienced**
acvp/v1/testSessions/10552 PUT

We are getting an "Test session must be in a passed state to be certified" error; however, retrieving the results indicates the session is in a passed status.

Thanks for any help in advance!
Andrew

**Comment by Kritner** [comment]
@abkarcher it looks like that test session was submit for certification, it's just currently in the queue to be certified.  We'll probably want to return a different message to the consumers in instances like this.

Basically the logic is:

```
if (testSession.Status != Status.Passed)
  return "Test session must be in a passed state to be certified"
```

where we'd probably want to ensure that the test session isn't *already submitted for certification* and return a message for that particular scenario.

**Comment by livebe01** [comment]
This change is on Demo in release [v1.1.0.23](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.23)

**Comment by livebe01** [comment]
This change is on Prod in release [v1.1.0.23](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.23).
