### ISSUE TITLE
"error": "A task was canceled."

### ISSUE THREAD

**Issue by GlennUL** [usnistgov/ACVP-Server#154]
**environment** 
Demo

**testSessionId**
209506

**vsId**
759282

**Expected behavior** 
Either a pass or fail result

**Additional context** 
After uploading the response file we receive the message: "error": "A task was canceled."

**Comment by Kritner** [comment]
Our side of things needs to have better validation on the response file side of things, but it's not yet something we've had time to tackle.

But it looks like your results array output for the MCT test is only returning 99 "checkpoints" (outer loop outputs) where the expectation is 100.  Also it's the *first* output that seems to be missing:

![image](https://user-images.githubusercontent.com/8814983/140731544-c7c97106-c145-4411-abaa-2e07c3a2f9fa.png)

**Comment by GlennUL** [comment]
Thanks for the explanation. That makes more sense now knowing where the issue is.
