### ISSUE TITLE
500 when trying most actions on demo

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP-Server#16]
**environment**
Demo

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
N/A

**Endpoint in which the error is experienced**
Most resource/meta endpoints that I tried
GET `https://acvts.nist.gov/acvp/v1/vendors?limit=20&offset=0`

It seems like trying to do most things (I didn't try making a new test session) is giving a 500 with the error:
```json
[
    {
        "acvVersion": "1.0"
    },
    {
        "error": "Internal service error. Contact service provider."
    }
]
```

This might be related to:
https://github.com/usnistgov/ACVP/issues/1029
and
https://github.com/usnistgov/ACVP/issues/1035

**Comment by Kritner** [comment]
@AlexThurston should be good now.  I have not had a chance to look into #1029 yet, but I'm assuming it's unrelated to this issue.

**Comment by AlexThurston** [comment]
I just checked and things seem to be working again.  I'll close this.
