### ISSUE TITLE
KAS-KDF twostep, kdfConfiguration occasionally missing from test group.

### ISSUE THREAD

**Issue by mwcw** [usnistgov/ACVP-Server#162]
**environment**
Demo

**testSessionId**
"/acvp/v1/testSessions/220520/vectorSets/824310"

**vsId**
"/acvp/v1/testSessions/220520/vectorSets/824310"

**Algorithm registration**
Included in zip file, capabilities.json

**Endpoint in which the error is experienced**
https://[acvpUrl]/acvp/[endpoint] GET

**Expected behavior**
Test Group number 1568 to have a "kdfConfiguration" 

**Additional context**
I have observed this twice now in testing, this is the first time I have been able to grab a set of vectors exhibiting the issue. It seems that we get back a test group that is missing the kdfConfiguration. However using the same set of capabilities the next time around we get a kdfConfiguration and everything completes as expected.

I have attached the failing set, along with all requests and responses.
[failing_twostep.zip](https://github.com/usnistgov/ACVP-Server/files/7742726/failing_twostep.zip)

Please let me know if you need any more information.

MW

**Comment by Kritner** [comment]
This seems pretty strange, but on our side of things, this prompt file *does* contain the `kdfConfiguration`, in fact 1568 ***isn't*** the last "test group" in the file.  I'll do some digging from our end, but fwiw the last test group in the file is 1632 according to our internal state.

With the file being as large as it is, one might expect there to be some potential transfer "issue" - however your attached prompt file from https://github.com/usnistgov/ACVP-Server/issues/162#issue-1084371108 looks to be valid JSON, but somehow not including all test groups.  Would there be anything on your side of things that could be "ending" the test group and vector set prematurely, but somehow correcting the json?  I don't *think* anything like that would exist on our end, but I'll take a look.

Attached is the full prompt file as persisted in our system
[824310_Prompt.zip](https://github.com/usnistgov/ACVP-Server/files/7747427/824310_Prompt.zip)

**Comment by mwcw** [comment]
Thanks,

I'll will investigate if there is a transfer issue at our end.

MW

**Comment by mwcw** [comment]
Hi,

After many attempts I have managed to capture a chunked transfer that terminates mid test vector with no trailing 0 length chunk. I have included the all the other exchanges relevant the the session. I have manually removed the access tokens.
The dump files in the attached zip file were recorded at the output of the secure socket. 

The file "truncated_1640179293362.dump" is the truncated one.
The file "ok_1640208938622.dump" I captured this morning for completeness. 

[post_socket_captures.zip](https://github.com/usnistgov/ACVP-Server/files/7765383/post_socket_captures.zip)

Please let me know if you need any more information.

MW

**Comment by Kritner** [comment]
@mwcw nothing is jumping out as something to really dig into on our side of things, but i'm curious if you can try to get the truncated prompt file a few more times and determine if you get cut off at the same point in the file, or if you're able to get the full file after another attempt.

Not sure if this could just be something transient or not... but even if it is just transient, not sure if we'll need to think about some sort of integrity check on the files being sent/received.  The most obvious one would be just attempt to parse the blob as JSON, which the truncated file would fail assuming strict checking.  I'll be interested in hearing back if you can get any sort of consistent behavior from this particular prompt file.

Sorry this isn't more helpful, but I'll keep digging to try to find more information.

**Comment by livebe01** [comment]
Hi @mwcw, I'm going to close this ticket out. Please let us know if you have any further questions related to this. Thanks!
