### ISSUE TITLE
SHA2-256 validation fails with "Could not find any recognizable digits."

### ISSUE THREAD

**Issue by dsikkema-atsec** [usnistgov/ACVP-Server#166]
**environment**
Demo Server

**testSessionId**
220804
220804

**vsId**
826500 - for 220804
826501 - for 220805

**Algorithm registration**
SHA2-256

**Endpoint in which the error is experienced**
* URL https://demo.acvts.nist.gov:443/acvp/v1/testSessions/220804/vectorSets/826500/results
* HTTP method GET

**Expected behavior**
expected all results to pass

**Additional context**
I am not sure what the error message means
 "error": "Could not find any recognizable digits."
This could be something in the response file that is incorrect, but I did not see any types of problems.

**Comment by Kritner** [comment]
Here's the problem in the response file:

```json
{
"md": "[INTMGR]",
"tcId": 361
},
```

**Comment by dsikkema-atsec** [comment]
Thank you for the find, I did not see it while scrolling through. Both response files have that in them.
I am closing the issue.
