### ISSUE TITLE
FFC-SSC: some primes missing

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP-Server#17]
**environment**
Prod

**testSessionId**
2718, 2720, 2728

**vsId**
N/A

**Algorithm registration**
```
       "revision":"Sp800-56Ar3",
        "algorithm":"KAS-FFC-SSC",
        "scheme":{
          "dhEphem":{
            "kasRole":[
              "initiator",
              "responder"
            ]
          }
        },
        "domainParameterGenerationMethods":[
          "MODP-2048",
          "MODP-3072",
          "MODP-4096",
          "MODP-6144",
          "MODP-8192",
          "ffdhe2048",
          "ffdhe3072",
          "ffdhe4096",
          "ffdhe6144",
          "ffdhe8192"
        ]
      }
```

The request returned only a subset of the requested primes. E.g. 2718 did not have MODP2048 and FFDHE2048.

Yet, the certificate at https://csrc.nist.gov/projects/cryptographic-algorithm-validation-program/details?validation=33303 shows that all ciphers are tested.

I am not sure that is intended.

**Comment by Kritner** [comment]
It's not unintended that you don't get a cartesian product of all capabilities for all algorithms, especially with one like this SSC testing where there's a prerequisite on the SafePrime keyGen coupled with that fact that the `z` computation doesn't change depending on the group you're using.

All that being said, I can take a look at making sure the IUT gets groups for every registered safe prime group. Adding or removing additional groups is something that we can do on our side without having any impact to the IUT (as long as we aren't introducing new test types), as the cartesian product of the registration capabilities *should* be supported, that doesn't necessarily mean we will hit the IUT *with* that cartesian product of capabilities.

**Comment by smuellerDD** [comment]
Am Dienstag, 6. Oktober 2020, 14:39:28 CEST schrieb Russ Hammett:

Hi Russ,

If what I see is the intention, then let us close the issue. I just wanted to 
make sure we are not miss anything.

Ciao
Stephan

**Comment by Kritner** [comment]
It's no problem to keep it open, we've sort of come up with some new ways to sample from the registered capabilities, it hasn't been applied to this particular algorithm.  I'll make a change to it for the next release.

**Comment by Kritner** [comment]
This change is on demo in release [v1.1.0.13](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.13).

**Comment by Kritner** [comment]
This change is now on prod in release https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.13
