### ISSUE TITLE
Request for a submit for validation do not change it status

### ISSUE THREAD

**Issue by tomstom** [usnistgov/ACVP-Server#18]
**environment**
Demo

**testSessionId**
/testSessions/118682

**Endpoint in which the error is experienced**
PUT on /testSessions/118682

**Expected behavior**
The testsession is "publishable": true, "passed": true, "isSample": false. And I also got a request link: requests/14679 as answere for the PUT. But the request never change it statuts, its now for some hours on "initial". I would expect that the status changed to "approved" and that I get a validationID at the received URL, like described in https://usnistgov.github.io/ACVP/draft-fussell-acvp-spec.html 10.16.4 or that I get a error Message, why the submit is failed.

**Additional context**
I dont know if its concerning to that issue, but in https://usnistgov.github.io/ACVP/draft-fussell-acvp-spec.html 10.16.4 it is written that the prerequisites can be specified during the submit for validation, but for example in https://usnistgov.github.io/ACVP/draft-celi-acvp-symmetric.txt 7.1 it is written that the prerequisites have to be specified during the request for testVectors. Do I have to specify them in both cases? 
In my case I only specify the prerequisites during the submit for validation.

**Comment by Kritner** [comment]
What currently exists in the specification regarding prerequisites needs work. For the moment, you should be able to submit the certify operation with `null` prerequisites.
