### ISSUE TITLE
Failure in attempt to put vector results to server

### ISSUE THREAD

**Issue by dsikkema-atsec** [usnistgov/ACVP-Server#180]
**environment**
Production

**testSessionId**
11475

**vsId**
115456

**Algorithm registration**
AES-ECB 

**Endpoint in which the error is experienced**
https://acvts.nist.gov:443/acvp/v1/testSessions/11475/vectorSets/115456/results PUT

**Expected behavior**
The expected behavior would be the results to be put (posted) and a validation response to be given.
Instead a 404 error is returned and a message of results not received.
Server error response: {
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.4",
  "title": "Not Found",
  "status": 404,
  "traceId": "00-090e13f1dbe677458a7a5012ddf880d1-60f3a9957cdcc149-00"

**Additional context**
I had just recently (like a few hours prior) done a put for other responses and got the validations.

**Comment by livebe01** [comment]
Hi @dsikkema-atsec, I notice that you are doing a  "PUT" to /results. A "PUT" is used to update results (see https://pages.nist.gov/ACVP/draft-fussell-acvp-spec.html#name-update-results-submission) that have previously been submitted. Have you tried POSTing the results? A POST should be used for the initial submission (as opposed to resubmission) of results, see https://pages.nist.gov/ACVP/draft-fussell-acvp-spec.html#name-submit-results. From our records, it does not appear that an initial submission has been made for this vector set.

**Comment by dsikkema-atsec** [comment]
Thanks for pointing that out. I had attempted to post but the response file was name incorrectly. The client had cached some info that a post had been done. I deleted the cached files and just did a post and not resubmit. It now works.
