### ISSUE TITLE
Algorithm/<ID> to return usable algorithm data

### ISSUE THREAD

**Issue by asant57** [usnistgov/ACVP-Server#181]
**environment**
Demo

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
N/A

**Endpoint in which the error is experienced**
https://[acvpUrl]/acvp/v1/algorithms/0 GET

**Expected behavior**
The expectation is that the server returns information specific to the algorithms ACVP-AES-GCM that presumably would be different from the information found at /acvp/v1/algorithms. i.e. the expected/supported fields for a request and their limits. as currently there appears to be no purpose to the algorithms/{algorithmId} endpoint

**Additional context**
Referenced expectations are along the lines of https://pages.nist.gov/ACVP/draft-fussell-acvp-spec.html#name-algorithms

**Comment by celic** [comment]
We've thought about serving an example registration on that endpoint, but it is a bit moot now that we publish them here on this repo. 

See https://github.com/usnistgov/ACVP-Server/blob/gh-master/gen-val/json-files/ACVP-AES-GCM-1.0/registration.json for an example. It does not state the limits though. That can be found here: https://github.com/usnistgov/ACVP-Server/blob/gh-master/gen-val/src/generation/src/NIST.CVP.ACVTS.Libraries.Generation/AES_GCM/v1_0/ParameterValidator.cs.

**Comment by asant57** [comment]
if I remember correctly there used to be an API that returned an XML of the supported fields and their valid values for the algorithm. Am I remembering correctly and just not finding the correct API in any documentation or was that never a thing?

**Comment by celic** [comment]
It may have existed in the past but was only correct for small algorithms.
It was impossible to make correct for anything complex like RSA or KAS. We
did not keep the feature when we rewrote our backend system in early 2020.

**Comment by asant57** [comment]
Would it be possible to return the capabilities registration data back for each algorithm in JSON? I am including a proposed architecture/structure here and how it would look. My viewpoint would be adding the ability for the server to return the capabilities of the supported algorithms would be beneficial to inputting the data to the server, I think the previous file I was thinking of also had the TestCase structure in it (which I do not believe is needed for this purpose since that could be considered a raw JSON file that no interaction is needed when downloading/verifying)

Schema basic
{
	"algorithm": "<AlgorithmName>",
	"revisions":[
		"revision": "<RevisionNumber>",
		"properties": [
			{
				"name": "<PropertyName>",
				"type": "<PropertyType<int, string, bool, domain>",
				"array": "bool",
				"limits": {"Varries by type"},
				"note":"<AnyNotes"
			}
		]
	]
}

Some Example Proposals
{
	"algorithm": "ACVP-AES-CBC",
	"revisions": [
		"revision": "1.0",
		"properties": [
			{
				"name": "direction",
				"type": "string",
				"array": true,
				"limits": [ "encrypt", "decrypt" ]
			}
			{
				"name": "keyLen",
				"type": "int",
				"array": true,
				"limits": [ 128, 192, 256 ]
			}
		]
	]
},
{
	"algorithm": "ACVP-AES-CBC-CS1",
	"revisions": [
		"revision": "1.0",
		"properties": [
			{
				"name": "direction",
				"type": "string",
				"array": true,
				"limits": [ "encrypt", "decrypt" ]
			}
			{
				"name": "keyLen",
				"type": "int",
				"array": true,
				"limits": [ 128, 192, 256 ]
			},
			{
				"name": "payloadLen",
				"type": "domain",
				"array": false,
				"limits": { "min": 128, "max": 65536, "inc": -1 }
			}
		]
	]
},
{
	"algorithm": "ACVP-TDES-CBC",
	"revisions": [
		"revision": "1.0",
		"properties": [
			{
				"name": "direction",
				"type": "string",
				"array": true,
				"limits": [ "encrypt", "decrypt" ]
			}
			{
				"name": "keyingOption",
				"type": "int",
				"array": true,
				"limits": [ 1, 2 ],
				"note": "2 is only available for decrypt operations"
			}
		]
	]
}

**Comment by celic** [comment]
It's a good idea but would take too much time to implement for every single algorithm in my mind. There are other features and priorities for the team right now. By "team" I mean the one lone developer we have working full-time on the project at the moment. It's unfortunate we can't implement everything. 

It may not be as easy to use, but users can now open up the code we use to check registrations on this repository to either suggest the change or build it in their own environments. We try to make sure the specifications cite all the limitations and dependencies between properties.
