### ISSUE TITLE
Counter-mode KBKDF / Middle fixed data missing deferred in test case

### ISSUE THREAD

**Issue by cipherboy** [usnistgov/ACVP-Server#182]
**environment**
Demo

**testSessionId**
225801

**vsId**
852333

<details>
<summary><b>Algorithm registration</b></summary>

```json
      {
        "algorithm": "KDF",
        "revision": "1.0",
        "prereqVals": [],
        "capabilities": [
          {
            "kdfMode": "counter",
            "macMode": [
              "HMAC-SHA-1",
              "HMAC-SHA2-224",
              "HMAC-SHA2-256",
              "HMAC-SHA2-384",
              "HMAC-SHA2-512",
              "HMAC-SHA3-224",
              "HMAC-SHA3-256",
              "HMAC-SHA3-384",
              "HMAC-SHA3-512"
            ],
            "supportedLengths": [
              {
                "min": 8,
                "max": 4096,
                "increment": 8
              }
            ],
            "fixedDataOrder": [
              "after fixed data",
              "before fixed data",
              "middle fixed data"
            ],
            "counterLength": [
              8,
              16,
              24,
              32
            ],
            "supportsEmptyIv": false
          }
        ]
      }
```

</details>

**Endpoint in which the error is experienced**

GET /acvp/v1/testSessions/225801/vectorSets/852333

**Expected behavior**

Per footnotes on [8.2. Test Case JSON Schema](https://pages.nist.gov/ACVP/draft-celi-acvp-kbkdf.html#name-test-case-json-schema):

> NOTE 1: If the "middle fixed data" option is used for the 'counterLocation', then the test case is deferred from the server. In this case, the client MUST provide a 'breakLocation' integer value which is the length of the fixed data before the counter is inserted.
> 
> NOTE 2: If the 'deferred' property is not present, it MAY be assumed to be 'false'.

I'd expect the `deferred` property to be set to `true` on this test case because it is of `middle fixed data` counter location, but it is instead elided by the server (and thus should be implicitly `false`):

```json
      ...
      {
        "tgId": 855,
        "keyOutLength": 768,
        "kdfMode": "counter",
        "macMode": "HMAC-SHA3-512",
        "counterLength": 32,
        "counterLocation": "middle fixed data",
        "testType": "AFT",
        "tests": [
          {
            "tcId": 1709,
            "keyIn": "CACE82D2C8B61EBDA4463FB372552FA944E8D60426966960BECF412A2CBE96110F58B2B5C3505200DEFA61C55B667244B266C87E6A348E7C8445231AB6FCB705"
          },
          {
            "tcId": 1710,
            "keyIn": "71D613743F545FAA1F862A1CBE9D4614D79F4FDDA33B00C3005C399A405D7AD8C83707369F064938468D9FE6542CE0CDC9EAB6DFBA5FA3790CB37A898DA538BE"
          }
        ]
      }
      ...
```

**Additional context**

This can be easily worked around, by detecting if the counter location is middle and manually setting deferred in the client. But I just thought it was curious and worth mentioning. :-)

**Edit**:

Is this even really a "deferred" use case? The given definition of deferred is:

> Indicates the client is required to provide additional input values to complete the test case.

But isn't this always? The only exception I can think of is when fixed data is omitted by the client (which the server wouldn't know about as the registration does not indicate requirements around fixed data -- hence, cannot indicate deferred/not on the test case specification itself). The fixed data is (from my perspective) an additional input the client must provide for the server to finish computing the test case... 

Perhaps it is cleaner to simply remove deferred and make it implied based on `middle fixed data`, as to whether or not the client must _also_ return `breakLocation`? Or simply always set `deferred` because the client must be returning `fixed data` anyways... My 2c. :-)

Additionally, maybe it makes sense for the server to specify a desired total length (and negotiate bounds up-front in the registration) for fixed data?

**Comment by livebe01** [comment]
Thanks @cipherboy, we'll take a closer look at this.

**Comment by livebe01** [comment]
Hi @cipherboy, thanks for dropping us this note. You're correct about all SP800-108 KDF test cases being deferred. They are. "deferred" is a concept that's mostly meaningful within the context of ACVTS development in that a deferred test case is one that we have to wait to compute the results for vs computing the results upfront. But, from the stand point of a client, I'm not sure that it's super important to know. Knowing that a test case is deferred lets the client know that it will need to return something else in addition to the answer, e.g., a breakLocation or fixedData. But, from the spec you already know that fixedData is always required in a test case response and providing breakLocation is tied to whether or not you're dealing with "middle fixed data". So, instead of updating ACVTS to include "deferred":true for every SP800-108 KDF test case, I thought it made more sense to just remove "deferred" from the test case JSON schema.

Cheers!

**Comment by cipherboy** [comment]
Great, thanks @livebe01! :)
