### ISSUE TITLE
Test session failed but all vector sets passed -- potential server race

### ISSUE THREAD

**Issue by cipherboy** [usnistgov/ACVP-Server#183]
**environment**
Demo

**testSessionId**
226493

**vsId**
856109

<details>
<summary><b>Algorithm registration</b></summary>

```json
      {
        "algorithm": "ACVP-AES-GCM",
        "revision": "1.0",
        "direction": ["encrypt", "decrypt"],
        "keyLen": [128, 192, 256],
        "payloadLen": [{
          "min": 0, "max": 256, "increment": 8
        }],
        "aadLen": [{
          "min": 0, "max": 320, "increment": 8
        }],
        "tagLen": [32, 64, 96, 104, 112, 120, 128],
        "ivLen": [96],
        "ivGen": "external"
      },
```

</details>

**Endpoint in which the error is experienced**

```
GET /acvp/v1/testSessions/226493/results HTTP/1.1
... other request and response headers elided ...
Date: Fri, 21 Jan 2022 16:41:16 GMT

[
  {
    "acvVersion": "1.0"
  },
  {
    "passed": false,           ////// <-- mismatch here
    "results": [
      {
        "vectorSetUrl": "/acvp/v1/testSessions/226493/vectorSets/856109",
        "status": "passed"     ////// <-- and here
      }
    ]
  }
]
```

**Expected behavior**

As seen above (and perhaps related to #56 and/or #63, though against the Demo server and not Prod and immediately during testing instead of after the fact), the test session reported `passed == false` despite all (one) contained vector sets having passed. This happened after a 10 second delay from the previous fetch of the endpoint, in which `status == "incomplete"` was returned for the vector set (causing my client to retry the fetch). I'm wondering if perhaps there's still a race condition, wherein the vector sets will have their results reported but the test session isn't yet updated? I've seen a few intermittent failures like this (3 out of ~120 runs) that makes me suspicious of this.

Updating my client to mimic Stephan's client's behavior (allowing me to fetch existing test session's results after the fact), shows better results and supporting my theory of a race condition:

```
GET /acvp/v1/testSessions/226493/results HTTP/1.1
... other request and response headers elided ...
Date: Fri, 21 Jan 2022 17:46:20 GMT

[
  {
    "acvVersion": "1.0"
  },
  {
    "passed": true,
    "results": [
      {
        "vectorSetUrl": "/acvp/v1/testSessions/226493/vectorSets/856109",
        "status": "passed"
      }
    ]
  }
]
```

**Comment by livebe01** [comment]
Hi @cipherboy, sorry, I know you asked this ages ago. Thanks for letting us know about this. What you describe is certainly possible as we don't have atomicity between the updating of vector set and test session statuses. We also have database replication occurring between our internal and external systems that could be throwing something into the mix.

**Comment by cipherboy** [comment]
\o Hey there @livebe01 

Good to know I'm not going crazy (yet!) :D

I've already added retry logic if I find funny results from polling, so I'm fine closing this out as a known limitation. Do you suggest updating [the docs](https://pages.nist.gov/ACVP/draft-fussell-acvp-spec.html#testSession_results_get) to add a note about this? If so, I can go ahead and file a PR.
