### ISSUE TITLE
Problem with local SSL certificate

### ISSUE THREAD

**Issue by nssathyan** [usnistgov/ACVP-Server#185]
**environment**
Demo

**testSessionId**
Login isn't successful.  So a testSessionId isn't available.

**vsId**
The vsId processing hasn't been reached yet

**Algorithm registration**
hash

**Endpoint in which the error is experienced**
Url: https://demo.acvts.nist.gov:443/acvp/v1/login

**Expected behavior**
Successful login to the ACVTS demo server

**Additional context**
***ACVP [ERR][acvp_curl_http_post:726]--> Curl failed with code 58 (Problem with the local SSL certificate)

**Comment by jarnold01** [comment]
hi @nssathyan - i will be happy to work with you directly to help you troubleshoot the issue. Would you send me an email, referencing this issue please (#185) to jason.arnold@nist.gov? thanks.
