### ISSUE TITLE
Issue with AES XTS expected data

### ISSUE THREAD

**Issue by stepriza** [usnistgov/ACVP-Server#187]
**environment**
Demo

**testSessionId**
231120

**vsId**
891990

**Algorithm registration**
{
                "algorithm": "ACVP-AES-XTS",
                "revision": "2.0",
                "direction": [
                    "encrypt",
                    "decrypt"
                ],
                "keyLen": [
                    128
                ],
                "payloadLen": [
                    128,
                    4096,
                    8192,
                    16384,
                    32768
                ],
                "dataUnitLen": [
                    128,
                    4096,
                    8192,
                    16384,
                    32768
                ],
                "tweakMode": [
                    "number"
                ],
                "dataUnitLenMatchesPayload": false
            }

**Endpoint in which the error is experienced**
{
                "expected": {
                    "cipherText": "A3F933A3B6B2525F64F711A4F800BFE4DFAF88F022A4412FD845AFCEBA23F256AD1E8222EC4542AC19D4BD7BE477786B2A9620C896FAC7D0909FCBE485D705B5462B77887292A5D7AF8A3B616A2C97F2580A4F27674EA517A2DEDCEEEEF35B4CDD310F027CD68F9EC79019842535F1FCFE32E20AE855677C7A4D8F749C6470B6652204F1A323AB3C8E8F5F42B6DF78AC556B907B08EEF7D84FE9CD3C433347E79DF635CF15E14BC192E6404228EF920B987424620F0690228F34A0C380A2D4FAE109D5F5C3F001F39F8FC0059271EB41D699437CF9EB91250733CF2C7305E45F6C980A839F1CCDD955460C04313BFE3EAEDB59F1949E15416B658B6D80100F6BEF64744F63A9F29BB2FEA11CB8FD32AA8AC483773D1ABDA22FE827484230D3DCE0A0D3B148D4418AD23FA9BF44C40180107A769CC6F9D2A90321DC310FDD6E497AED93FF7E5B760B613F8011936DD03324C33BC809DCC5C11987FB2FA514043EB3B749DF2AE569E80EE49360E39C62D24CEF67C4B8AE5A8EEE877E057F7B86F067527507BD8FC5BD7D4EE3C00B713ED6E8B0474F5F097D30B543BAD790B2C58DD33D4754D033286977D436658F9046F1E67D10FB0FBCC81D7F06EA4D00CF265A1489DC9570FAF61B7A2059CF175EFA44E0D37BAF2F7224B1F2F28FA6C269958586F2CF50F715AE54F4DAC981A77E9705F00F4EECC0599EA5AC5C05E2856BE55144D4CFA181BB6BD410906991EDA0F8C66107A752E03D6DC3BD783D9CFF90C62C4517061D4774BC6B41AA1F8AA5A2F7521B3D49A017C9127CA01937C0D0A6EE02A0596EBCBDB3B863D9043EFA04EB1174EFE1D94E1C083899DA3ED2530B8BFAF7E2A19CD2D04C212736A999E35B90780DD0200D762BAECEA9F766C935E39ECD2828B9967CA64AAB3481B05600682294C41E5232C95306E1EB79E5245968B20B0A56F72EAB4EEB24F8AEEF2E556072E2A881F71D1F0418D296DDD3F1AD6DCDAD4FD5EE1E76FCFA1389E1D0B2920AD7456A8934E71BBB997044E6CBA96F640BF2F0E2BE03C16A305771DC293F87BF060214D0B40E8F399CDB7D85B680DE9743A87B4B60C43A9AE75D9FD810D2DBDC1204A37DB2880A7B2185DA066563ECB231C4272AB0FB817C5C4CE1B7462237E2E7711B3DE2612CC7EB6E63E85F69B613C010623D16698150E46482F8AF816F27ED1209AE9775D12CABEEF2701DE91F642221D003E40CDD8A3947885B9CF38E72DD8A277022DC919199DFF6D3DA22833DA431CC3ECE8FC736208E74B0D6E5E75DF444C7E780D5A69C8005DFDA2CAE37CDA41A39D558CBBE74FBC9A8E289C219E243258B04AB041C14E90FF0E2986FC0EF7B017781A2AE584CFFD78EF8A0C4112CCC6695F99EBE8DEC1EBF48C2896BF830BCE7FF7E85B0B595DF0559B9A1A452A8D86425D88F20D79B7DD044F826FDFA6BFBD7E1C097654A5084C585AB34537E9AD2AB317C8F9489022272783FD73164BB30DFBF33AA352B3E28785AEFEE8EB223852AE9E8421D502086697CDB0D424DCB666F98AC2E40A3BF9F151B952731484989E8C09C9EBEFB8EC98869187925CD3C73D4FC11E3CB97E718A8046ED3202BC8A2A275884FD708CBB7CEFF836CDFD1B72730C49AFD58CDEDF90151F7B55C443E4515A7D3CB4C3F50CF88EEA9CE6978FB3F3F16770F79D0E85BD8B3A1190B7707AE791A8E76EB2607DFEDAD6CC096648446C7698D6DA67DFD75842CFCF0089C26BBD2EC5EE0DBDD76D9D7F695D6425A35FF0C855A30FEFB8B7912570C548F1690B22FCA5B2B633C72B68B8F2D611A05E8F39320765FA24C8EB66D10CDCD32F2D3A935543C59E68F3DC82B4121AA772F57756BCF8A6E99AA8D2250047A5AD772159F4E1F864A166FFD375315194DB0179520C71E43206892691E1ADD6030820C590E9C195A2EE67ED90CA10A9E9FF84539C4ECE0463D42CABB78964EBDD393DC99004FA864E4424269538E9103D583958C433524A1FA0BC38C8EDAE2F61BDC80D1F51C71D1B7AACBA3A9FCD498F1E6A8B7D5F360C99EC3DB3A9FD241FF5E7D574CC719F1613E55D49CD8CD2509006E4A310788B1A95BEE73B07871E4EE0268DC6CFA65A2CB774052B35A2ACE3B81D8365637E7B3B1C748505A125F9FE0D5DAB6BA75130AB70D4514E73AA76EAC58E803F6894C16A51F2530F662A325AB21ECCC2CF8AF9C98A0B3D547BE9F6CF10B2CC3596EA9918C680D07B91FB5E2C6A474CA7C5B009B27D6687AC717C6AB81959F75C18267937C5B0DB5D4BA1E706A8BF676ACC6D2A4019E93F2247897FF83E7212DEEC0FBF5AAF9B9E953D65D02214F3EF2C02AE1E1AE6434F5A20596C65A4944602D92FD5435E1A840A8216FC4A0E70C4E0E3E50F01601F0DD936C77EC41CA85495EDDEA4823BEE626C454003796E386F0DB26B459C038652BE792A36188632D75EDCAE07776A455200193EE137CB40A93991C509126D5887785500829B6129322851778405D8336D090AC431B23FDD4CF2CDC9C490BA9F945C61B8A57E0BA39AC9643E0B443A4548FCC5282B0BBB383FC077CF73159FA5FA93A2047D3BA6D22D991995B49771E3B4F37ECC6ACB15E43DFEE0C59925CC4E7EF2E370F80AE9EF09CB470812CF53F02209D943FCAF9377E170513BD01172AAB389650AB40F6CC95E8FFC974313602E1E8F321031510B3CC85A2AAEEE99325A52025404A83BC8EC91008E9AE3A2D036352EC5A144AC23EC4E0DE8BAB35DA545CCEDDDA13DBA7A7D3EA5C269115F7915E3AEED40740B7FA8938B6C7E8D08E91E707F5076F1A9E8CCDC1476BF89CCF762221190CFF4F14204F125D2AE99A2D161FD265DB44AD5F3C1DCB851D5D4012313A938DB938D8BF4679498A8414A95AF0C14440C569A202F6509F4B9FA47F"
                },
                "provided": {
                    "cipherText": "A3F933A3B6B2525F64F711A4F800BFE4DAC30F5F131058E3DC9F692A6F3458B5B361199C321565191C30691D1F5EE99E8C42F75D84AB1491E49A562CA48EB47B1AE0DFE463D81292BAA190E3B15063F09893272FF02BCB7D85811E84F6ADEEBE398276D139B2B6A885C3BD4AEF91B82F1BB078D7243EA286E03D9BF2A805651A30176C2ADCFF1AC32343FC3098C0A487D58D88D5630D86DB81CCBA243B8688E0BA21BB62D6B84829D22B5FB4C5551C0ED28594CD23E8AABDCD5022414AF6D15F8306DC59DE6B3852E81228DB53D15B8B39AF2EDFBBBE85CCA0A78DCC84251B871F9D18C34B387C1DF0AD5AF8C81429F44EE9380CA771D1933CA6D2D1C5083B2D77DADF9F979C75243BAFCB7BB1D0DD337E67BAAA073041448687F4EF3BF7CE059AE3C140ABD41F58E3D884D5E1A7328A0519951B6373379931548373D3D384047A5EBE9AD1239A8A221009A0BB93AE2C30ADD522AEB2ADE40251E94D9AD2092B6E9EB2915C157A10F72D83E710742AF13DDD64A5BD1062C97BDD43E6CC3A3FC8A7B407D24CF925EC2C0BB21A31C29E802D1E333D1E587F4A23422E68BAD5FAF5486083159E77108BB9EC44FE1D6F0C95B8580B0AC8F3857C63C9C770FB3BA304340330E63B47B745CD2C09328CA35560A0B7DDB4EF7E0921F674E0E663A414B285E0C827AD6A3AECD704BEC3B92B89858D17563A74CB03EE85A1F2A7AF3649F2B02D7D53B447B796CB0C0BCEF3CAE80FF86910159D77FC41962C1CD07CF7D8668F18B8F3A5A0B2EA98D0A6F38F4BE3B816D46BDDFD2082FCB5B500783876CBFE5C815B1F040792FC53DC93F537ECDB6D2DD91AEAA628AAC270FAE6EB15EBF794437BF02FEBB049E8090FCC4985C284E1DFE24286A2E12C9D475E7021B42172B44B417428904B46DC7A3C03F9A985159EF89A74535AFE2705F43B24D4B028238DE7565B64CB603186CE0F29C5715472A860A5F0B4911FD7090CD29B772ECC93EB8466F74FC53735902CAC37CADBD30183F26BDE556BB999F480333D287A24E4FA74ADA5B754EC4F150D8D63C340F60BFD37E84E88D01E1DD90316DCAE81C924CF95419698762EB6A87B2DC2F43F61F46D23B8920FCBA882B3925217D32B1A561DC042FAA9338F02B3C5BB99F58AF391EE68DE794125CDAF97E4070F8C3AD5B684CAF6A95DBE1281D865E974BE966942E2D736FCD4D2373782B071A52F4BA2B6F64DE9A82462C00C07F8BCB503845125309BA6D225D37F848A7127ACD584CF170685C5AD08C3F647DFA26EF00FAA0F33EC79B2785B984CE9D596DCE840A2B229A4C289117E1EE0AB337ED1D50E4100D4214B029E85BA9B065DD6E85FBF4BD9B5B90B2486F1562B77078B20A4A663DC95E6D4E398CC85E4DEF2BAB40054C2858E63CE0A7610A1553A528C2E8D978DC1CCFDF8FE9946A3D59FDB121CD1270972F8A3999759E83A4EE9329217FA10004019D89F81ED3022936BF1948F278ECE1A601CBC9E6775341D40122DE73A407BC2724D70787C9AC54C6E88237AD3DAE42428503E0298508F0EC679595636A8F774CC4DE246BACFB86EC64FF8C61BEC18DC5ECCBF21FB7D4D44EE2FBB30C91CBC48D3495E6924965877097D03B831B671810B1444B44270FE6F080FECAF1A1FFDB8B7F6D6DEE891593556A74948998A18DF6A60BF54AEE587BFAE8C610411C4EBC5DFE7A0101B79B81FE0BCCED860AC41261B4281568EE209DE2C020835278A68E72806DADDB392B809DA238EA5A5755AC3D7F46BAE49C8AE4B27391186E36920D7AC885C0096C2B22DC0201FF08B04A565D06885184E0F7998186813AFAC844F553A7E794014A0E6EB8C5B1811A7704F575DB8D50AB1C6783FEAFEC8B6EACACF0CA66BCFA3BA23F453CEA42310C06CEBE07ADD856F6B714C45E46CAD72D4CB4EADDCB365409F9650FA27D73A2927256EBB1DAFFE6DC568F9B7CFEF4721DB7F3BF7547515F28A984D0A72348C6FD668C3DED15A231AC2BA3A574DF0269392C1D386B102D1482728D21E0180E10602A7FCD6F99F5F3FD60EB81F887FD5AD348A4E72C1D7A92C3C4FDC1759558780090C3D4768BE9D2CC2809BB70544327D46E0C6C7E45FACA3E1666EF73689563D8F47F24A07F46A4FA06701FAEDF68BAF4EBBE850B3B2E5B0C8627364C057BA30DC045E288DBD05BFB1C7F90BC011DC64C090742846CE05F98339785E202C0D0C4ED2E372627C408F9437E5BCD0A3514C5E39E4CEE80C0D2A32D5990EC55CEA0E06912129CC12B63FCC58E3229BBFF354066C62D2F23B867402E0EEC9A083801990CC704C081D4C2E770EF1323EE7C51E0B37C4B10BFEDDC22A0440F991315DBDBECE87CBD99E1E67FE1E9C2EC5504F64EF58FBEB5BC528F5A7E89CE2EEDF38DEF96D49F0BE0A663119355FA174C0C2EF913AE38DB7DA16BEE8DB5C5CB800090927ED9D4F89AEC0512B5E523A9CE87FE71F6B9B6D450579557EC33EDF9A4E3EB9DDEA368A483C2539E4C82F0FB35FABF88F5C1619EE24F606C062E81761562CD0BD9890C2BBCED8AC77689A5DE015375AC23A60287A42A2515949F1AF18A2A67F1A3DC1CDDE997E8CC9BA2DF2ABA205E7E5A8BA22670BB065164B0A91C0127856C00B6E3821826BB4E0680D1E652B3D864228B549604505F2B0C5F4D1655B0D091882D9ECAFD606975C0322CACB4D383C5273FEB013B0CA19B6903DC1733F166E34F1F25253213A40D058186006FD184D4646816AFC33D3EF3AD3B7667E6EDA36A71B7D28EF743F4C11B6E6DC0785F5DB2B01D28DA3081801103C130009186C7CB46871443CF3B70537E41CC9EE6074639042091C0DAD122625CE646C47F008A94DFACC2E02ACAECCA0099D3A5A05433F0B35DD7A9AC73EA33CACE75A35121EBE4F8A3919D4A9"
                },
                "reason": "Cipher Text does not match",
                "result": "failed",
                "tcId": 8
            },

**Expected behavior**
In this test case we have "dataUnitLenMatchesPayload": false set in the capabilities file and in the vector set we have "dataUnitLen":128 and payloadLen":16384. However in our result we got a mismatch after 128 bits. When I rerun this test case with the data unit len in our implementation set to 16384 bits instead then we get the answer that matches the output file. So it seems like despite having "dataUnitLenMatchesPayload": false set and the vector set listing a smaller dataUnitLen than payloadLen it is still treating it like data unit len is the payload len when generating the results. Did I misinterpret something in how that works, or is there a problem in my capabilities entry?

**Additional context**
here is the relevent entry from the vector set

{"direction":"encrypt","keyLen":128,"testType":"AFT","tests":[{"dataUnitLen":128,"key":"E29AB8839547007A761AC9F83E7083AAF6F35AB1CEC45DDDFED8DF0675E9B5E3","payloadLen":16384,"pt":"2D649F14C1B9DAA5555672AC4C1AA43226D3E51B69904F82AF7A3C6FED55D0E9C71613E3A2A97DDC0FC4411E470C583B48CC5C46D27CFA404842BE3F95E9699774B9B9A555EDFE8219B89863D197C46DBAD25956EC45A280BB69D1A02C9794A72812B60C7A120DA222498B75FDB6AA19E3EBD7299192AA2BC634B7639021CCA52D961A7BB1A85992FCEAE9967068B473CD61C2F93CC13D428E67B4D3A50A8C0CDFFBDEB229777AA5E414EBCED438927A075D6D1C2DACA00C4844F32B4D3DA6E7B9BECF02E3BCD03B7EEFA5DDCE8686819302114BF246CAAFFEC26EFAB2F89489F1B9555BBA257D18A85F63F75B9FCEB73EA624E2C698A10E198A2861D5799BE1E7007D9C3EC527B7E5D7E39354E339272344734DD97C8A6F569321E2DC62F08BF3B8DB94C7F1FBB2F3FD5E5007F7A23A6C05C3C6048E99C295448D3A771BB44428EA8BF71EA52CE60A78DC723E1FB3E3CD99FE91A619767FAFFA3AF3D8062BD06F9D70BADB6FD36A966ADF7B0D48BCD0386640A3EC24E199A56667F210C351E9F3EABAFBEFEB490D3CEAB588B31BE516ED4BB729F01EBA2A9960A6257D0F554CF29296F35FAA1BEF8F30C1A64F7AF94B8CE502650F437C8ADE19A50BDAD93EFD910503AD6772FBF0B1C76D6DA998443E6C81FEBB0DE651F540FD655A9ACDB6FC9D6A3F93B966CC8BA1104C6139BD8844743FD991D6DB68D199BC1333FD9C00FE29A72A31DCB97E4512D59776B7EBB2533162F79ACBDFA3C79C1C4D38ABDF603887044DEC10BAA66CDAA4707AA304EEE6F4BE135DD5870276933BEB832559E9824F3B7BA6D1A71245C0CD22CD55370387A072929562AF7402AA1E9323FF6739FD72C5B1A68C8E598654750C498AAD94265EEAEB5E575C4800E207352A2E66BACC16AC7BEA5D61718BD1E9F1ABB0560ADF49C18AB93350AAEDB00F08FE1A2A6F4520BC9F948CDEE8E8A41FAF0149F90FEA064F559EABDB89B64107C8454A16AA80EA3BA4C040102F9E5F3594BD07EBF578555314C5AA5A80C57DE0A4BC7C481E39DCB6EC3E72643E1A15FFF82CA00697E5C3458D694F8736D67916257F2A459E586235C49ED0B9BEE2BD634DE130FADBA25FCF011AA0806EA154BDF83047FB7E63E028267CA8F7B5C5602EEABD298A9372466D7AA8A87F8088B16D95867E1E11A721766BC46C220FD978AA9A20091F0EE943774E59A29FDA4CEC939EB8D02D70FA4EF4DD3874D7E995C61D4783CB6D1B502566B3EE18609BFEAEE09B55B7D5F7C02D658E256F3450F66567B93E9D892D88E8558DC8ED9D60DD194D6CC4CD4FFC7F5BE50CF8F504A6B32EA08C783DB54C1BA569A4B35452A53A5E842915E77E97F2DFF6F4E9A5D2F18D09E11A93D8BE61436354436541DC754FCFB1CBE691AF95493464379FF8AF70E8CEE68FCAA275EC296BBBC57DC7CB571796EC9915BBC07399ACBD08C4E8CDFE29D10B3198F30B3C69C786A7054941063D291F6CF7D841F3007F82D6DFDEB3AF12C00EBECE09803602E47157AFC0F21C829DE77797DFBF3790D93A19290E21DB1E3568F765C4A424A0B64BB610D2CD3B98ACE400B9D1E47AB87482722D21ED4E9B82297CFC8BC8679DA1497C5977AC124C683A165CBC5D47B264822E2B41C6E933A52EBCE51AA3D3C241BD171996DE3BA2ADB4F30B20F4C93F0E979F5E8BA85BB8621338B24EC0015C453751869D564903E1B9D49C7F4C46DEE10BA51CFF19FA9343B470E0E21C5B8251725767D2AB4BB4B39F77853B9E6DD3F41BCEAA4252CF9D9F2431E80BFDA3583E103BEC1F3BF9B0B6E86FCEB799B7749D7BDE86749A928D5F77A2CC5B029D226E2E1EF3130A4ED2A14345D5E02E1542F08CEAA82012875D034EF76E0D9BF4FCBE4FFDCCDBA7018824FE98FCF895DB56E5B0674FFF5B716BFBFA9A149273D0393F3E6BBB85FBF258DCE904927E82579E628AE1DED4333B290A82C7CDFFDD712990167E50333EE0C78F3C833A857CEEC2C89AF2049C6150BE8E9FF966C281945F238A0E6C451F38558E7E4024F2C9C804E88A4F943C95B39E83C3706C936F45CF6175044D80D74D172E2F9A4F00D382FF0B8DD50750F5D428D78F449237678429CE40F874C8D391BE92A08911BD8B2EC756A7D31798130F59E9CC211296DFB8B84058DB2E9BD8A6DFA46E1B604FBEF5F9A1DA71EF1FC481A96F944C6FB3362CAD00D9D0B284D0A2C797F3DC1ABC7EED353CD449C28CB891100B5FFE3E9F3ED28188D8DF3DF431CEEB9DFEA8B0D58C086DD2EBAD85B8B585DF16C4E452BB40C53FA3B1A7C5ECBF21EA5A01781298A7D4EFB2BA7E657E75332F9DCBFD151C28ED16104157AA7CBB2750502CFAEBE523AB13D9017BA856D680FB5C24811410721655ED5D3544BAAEF12D62D43BFE718F531EE00D87337DDA73468512596EE98A258C2A6C7B38428C206134F883C91C060EB5926A9F35FE41C1689677D0DB102526E69E57057F45E5897F4286743E430ABD56EE69931071C3E330EBC11ECC0B63E8A937C7D3DA5DFC1F257B10F9E272AC2AB543DC3FF8CE5DAD7231637B650B058F3C68E7EB6DBF01332D62626D1E36159366262AD19BA05090223493DB90298188E92E2FF7061350DF1478DF495F7FE2060DF4A5E693EEBE6C60EDFEBE9F16AC0CABC1ED003C22880C0DBDBF5A0CB17E20F332F23D362D4AD62F6C1A8E1F5E9DD4D3EBFBDEA0D538FF31DB13DDC4EDD87B7C1E1C3CEA7FF8A6A08DD67422B9E8219B8448E42DFA3E106EDDBC2FD3EA6405E13D47077F38581BCF28D8DFE5A7DCEE0BE7C728F3B9B9C3269C75439BC8CF786CBC1CFFA7F30962AC3B9DE7BE64ACE42058F7A362D0C1FD3CEFFB889B05576D0F9743928BFD46028A2AF9B4B6F6B321251148F235DF10B04EA8FCEEF5948DA6EF","sequenceNumber":231,"tcId":8}],"tgId":2,"tweakMode":"number"}

**Comment by locksmithone** [comment]
It may also be related to this one:
https://github.com/usnistgov/ACVP/issues/1224

**Comment by livebe01** [comment]
The fix for this is now on Demo, v1.1.0.25.

**Comment by livebe01** [comment]
The fix for this is now on Prod in release [v1.1.0.25](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.25).
