### ISSUE TITLE
Exception running generator. Contact Service Provider

### ISSUE THREAD

**Issue by YasuhikoK** [usnistgov/ACVP-Server#189]
**environment**
Prod

**testSessionId**
12117 

**vsId**
125684,125685,125686 

**Algorithm registration**
HMAC response upload 

**Endpoint in which the error is experienced**
POST /acvp/v1/testSessions/12117/vectorSets/125684

**Expected behavior**
We expect the result is passed of failed. 

**Additional context**
We think that some error on server during some vector sets.

Please let us know how to recover.

**Comment by livebe01** [comment]
Hi @YasuhikoK, when the server created the 125684, 125685, and 125686 vector sets, it failed to create some of the data that we need to check your answers. That is the source of the error you encountered. We don't have a simple way to correct this, so we regenerated the 125684, 125685, and 125686 vector sets. Can you download the new prompt files, run the tests, and submit your new answers? Sorry for the difficulty.

**Comment by YasuhikoK** [comment]
Hi @livebe01, thanks. 
We downloaded the new prompt files, ran the tests, and submitted our new answers.

**Comment by livebe01** [comment]
Great! Sorry again for the difficulty.
