### ISSUE TITLE
KAS response/expected issue

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP-Server#19]
**environment**
Demo

**testSessionId**
118302

**vsId**
340867

After we uploaded the results of vector sets. We can some response in the result like

> "incorrect TestPassed result. Test expectation: \Failure - IUT should calculate different tag due to OI value changed."

> 

So, we said "false" and the expected result was "false", but we failed the test. There are several of these instances.
Any idea what it's about? Or any document that we may follow?

**Comment by Kritner** [comment]
Thanks @AndrewHYang sorry I missed this one come in.  I'll put in a correction for this on our side, we weren't properly manipulating these "expected failure" test cases to make them fail "as expected".  I'll let you know when the change is on demo.

**Comment by Kritner** [comment]
This change is on demo in release [v1.1.0.13](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.13).

**Comment by AndrewHYang** [comment]
Thanks, @Kritner. I will close this issue now. Will let you know if we come across something similar again.

**Comment by Kritner** [comment]
This change is now on prod in release https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.13
