### ISSUE TITLE
Vector generation taking forever

### ISSUE THREAD

**Issue by DiptanilDRoy** [usnistgov/ACVP-Server#190]
I have been trying to generate vectors from 20th Feb but it keeps on running forever and doesnot end. Tried today as well from its still the same. Only AES ECB and AES CBC are there in the regJSON. Session ID - 232634

ITS IN DEMO SERVER

**Comment by Kritner** [comment]
Both of those vector sets appear to have been generated since more or less immediately after the registration came in.  Can you please provide the endpoints you're hitting, as well as the response you're getting?

**Comment by AlexThurston** [comment]
I am having a similar experience.  I am registering some simple algorithms to test something, but continue to receive as a response from the endpoint:
```
[
  {
    "acvVersion": "1.0"
  },
  {
    "retry": 30
  }
]
```

The endpoint for me is: `https://demo.acvts.nist.gov/acvp/v1/testSessions/232605/vectorSets/901890`

**Comment by livebe01** [comment]
@DiptanilDRoy, @AlexThurston, we think we've resolved the issue on our end. Can you try to retrieve your vector sets and let us know if things are working on your end?

**Comment by AlexThurston** [comment]
Huzzah!  Looks like things are working for me again.  Thanks.

**Comment by jarnold01** [comment]
There was a network issue that occurred over the weekend which I addressed this morning, so Demo should be processing normally again. Thanks for letting us know.
