### ISSUE TITLE
Prod Server hasn't given results (Over 24 hours)

### ISSUE THREAD

**Issue by Umayrkaleem** [usnistgov/ACVP-Server#193]
Prod
The environment the issue was experienced (Demo or Prod)

12230
The test session ID

entire set almost
126852: INCOMPLETE
126853: INCOMPLETE
126854: INCOMPLETE
126855: INCOMPLETE
126856: INCOMPLETE
126857: INCOMPLETE
126858: INCOMPLETE
126859: INCOMPLETE
126860: INCOMPLETE
126861: INCOMPLETE
126867: INCOMPLETE
126868: INCOMPLETE
126869: INCOMPLETE
126870: INCOMPLETE
126871: INCOMPLETE
126872: INCOMPLETE
126873: INCOMPLETE
126874: INCOMPLETE
126875: INCOMPLETE
126876: INCOMPLETE
126877: INCOMPLETE
126878: INCOMPLETE
126879: INCOMPLETE
126880: INCOMPLETE
The vectorSet ID displaying the issue

**Algorithm registration**
The pertinent algorithm registration pieces (algorithm tested, capabilities, etc) in json format

**Endpoint in which the error is experienced**
https://[acvpUrl]/acvp/[endpoint] GET

Expected behavior
Just want to know if the submitted resonses passed or not, its been over 24 hours.

**Comment by livebe01** [comment]
Sorry about that. We had a hardware failure over the weekend and one of our services didn't restart properly. All of your vector sets have now been processed.
