### ISSUE TITLE
RSA result 'retry 30'

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP-Server#20]
**environment**
Demo

**testSessionId**
118146

**vsId**
340251

After vector set is uploaded, the result keeps showing as 

>  "retry": 30
>

**Comment by smuellerDD** [comment]
Am Freitag, 9. Oktober 2020, 01:54:42 CEST schrieb Andrew H. Yang:

Hi Andrew,

> **environment**
> Demo
> 
> **testSessionId**
> 118146
> 
> **vsId**
> 340251
> 
> After vector set is uploaded, the result keeps showing as
> 
> >  "retry": 30

This is the expected behavior as the server needs to crunch the numbers to 
return a verdict. So, wait and keep retrying until you get your verdict.

Ciao
Stephan

**Comment by Kritner** [comment]
@AndrewHYang it doesn't look like we've received a POST of results for the specified vector set.  I saw a PUT on this vector set, but results have not yet been posted an initial time.  I can't say I know off hand what the system would do for a PUT when a POST was never received, but I would say start with trying a POST again and see where it lands.
