### ISSUE TITLE
Issue with AES KWP expected payloadLength

### ISSUE THREAD

**Issue by afazio2** [usnistgov/ACVP-Server#200]
**environment**
Demo

**testSessionId**
240064

**vsId**
947110

**Algorithm registration**
{
  "revision":"1.0",
  "algorithm":"ACVP-AES-KWP",
  "direction":[
    "encrypt",
    "decrypt"
  ],
  "keyLen":[
    128,
    192,
    256
  ],
  "payloadLen":[
    8,
    72,
    136,
    240,
    376,
    568,
    712,
    808,
    888,
    1000
  ],
  "ivLen":[
    64
  ],
  "kwCipher":[
    "cipher"
  ]
}

**Expected behavior**
Expect to receive Test Groups with different payloadLen values selected from  [ 8, 72, 136, 240, 376, 568, 712, 808	, 888, 1000 ]

Received 6 test groups with the same payloadLen = 1000.

**Comment by livebe01** [comment]
Thanks @afazio2. I've identified the issue on our end. We'll get a fix out for this in the next release. In the interim, using the payloadLen restrictions defined for [AES-KW](https://pages.nist.gov/ACVP/draft-celi-acvp-symmetric.html#name-key-wrap-block-cipher-algor) should get you better results.

**Comment by afazio2** [comment]
Thank you for your support @livebe01. From [AES-KW](https://pages.nist.gov/ACVP/draft-celi-acvp-symmetric.html#name-key-wrap-block-cipher-algor) payloadLen restrictions, the increment is 64. If I needed to avoid multiples of 64 in my AES-KWP test vectors requests, could you please describe how to do it ?

**Comment by livebe01** [comment]
If you need to avoid multiples of 64 in your testing, you will need to wait until we get a fix out in our next release.

**Comment by livebe01** [comment]
The fix for this is now on Demo, v1.1.0.25.

**Comment by livebe01** [comment]
The fix for this is now on Prod in release [v1.1.0.25](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.25).
