### ISSUE TITLE
"Internal service error. Contact service provider." when logging in

### ISSUE THREAD

**Issue by jvdsn** [usnistgov/ACVP-Server#203]
**environment**
Demo

**testSessionId**
244904, 244905, 244906, 244907, 244908, 244909

On April 27, at 10:22:22 CEST I logged in to the ACVP server to register six test sessions (listed above). This registration was successfully completed at 10:22:24 CEST. I then closed the connection, and waited ~8 minutes for the server to generate the vectors.

When I re-opened the connection at 10:30:48 CEST, I got the following message from the ACVP server while authenticating:
```
HTTP return code 500: [
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Internal service error. Contact service provider."
  }
]
```

Then, at 10:35:54 CEST, I again manually requested the generated vectors for the same test sessions, which completed successfully at 10:36:01 CEST. My login certificate did not change at any point between/during these requests.

**Comment by jvdsn** [comment]
I encountered this error again on April 28, 15:41:41 CEST while trying to `post` some vector responses.

**Comment by jarnold01** [comment]
Hi @jvdsn - we went and looked in the server logs, and what we are seeing is a JWT mismatch between your cert and Quentin's cert... any thoughts as to why Quentin's cert is involved at all with these test sessions?

**Comment by jvdsn** [comment]
> Hi @jvdsn - we went and looked in the server logs, and what we are seeing is a JWT mismatch between your cert and Quentin's cert... any thoughts as to why Quentin's cert is involved at all with these test sessions?

I'm not sure. I was requesting test vectors for a project where we already requested some test vectors in the past, but we do this quite often and normally there should be no interference between the old vectors and the new ones. I will discuss this internally to try to figure out where something went wrong.

**Comment by jarnold01** [comment]
Okay, sounds good. I'll close this ticket out, but feel free to re-open it if you need to based on your findings.
