### ISSUE TITLE
Update submission of vector sets-404 error

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP-Server#21]
**environment**
Prod

**testSessionId**
2406

**vsId**
23992, 23993

We submitted the results for these two vector sets before. And when we're trying to update the submission,
we receive 404 error as below,

> "type": "https://tools.ietf.org/html/rfc7231#section-6.5.4",  "title": "Not Found",  "status": 404,  "traceId": "|3339d5f2-43598afa0c5cd6a7."

**Comment by smuellerDD** [comment]
Am Freitag, 9. Oktober 2020, 04:32:54 CEST schrieb Andrew H. Yang:

Hi Andrew,

> **environment**
> Prod
> 
> **testSessionId**
> 2406
> 
> **vsId**
> 23992, 23993
> 
> We submitted the results for these two vector sets before. And when we're
> trying to update the submission, we receive 404 error as below,

Updates are only supported for Demo to prevent misuse and guessing of 
Production results.
> 
> > "type": "https://tools.ietf.org/html/rfc7231#section-6.5.4",  "title":
> > "Not Found",  "status": 404,  "traceId": "|3339d5f2-43598afa0c5cd6a7."


Ciao
Stephan

**Comment by AndrewHYang** [comment]
Hi Stephan,

Do you mean for Production server we have to create another test session and generate new vector sets to test again?

Cheers,
Andrew Y

**Comment by Kritner** [comment]
@AndrewHYang Yes, the intention is that any "kinks" with the crypto and communication between the ACVP server and client should be worked out in demo.  Obviously there could be some exceptions to that "rule", but that is the basic idea.  

To use the most extreme example of why we don't allow a  `PUT` of answers on demo is with an algorithm like *-SigVer.  The entire vector set would be comprised of `true`/`false` responses, if you get an answer wrong, you 100% know what the correct answer is for your second attempt.

Hopefully that all makes sense, closing this issue for now.
