### ISSUE TITLE
GET /dependencies/properties doesn't work

### ISSUE THREAD

**Issue by mmccarl** [usnistgov/ACVP-Server#215]
demo and prod

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov:443/acvp/v1/dependencies/properties

**Expected behavior**
a list of valid dependency properties as described in https://pages.nist.gov/ACVP/draft-fussell-acvp-spec.html

**Additional context**
accessing the following url fails:
https://demo.acvts.nist.gov:443/acvp/v1/dependencies/properties
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": "400",
  "traceId": "00-e4b4b7a6ba1a5e4182a570c122ff88ad-4873a0ed7f149d4d-00",
  "errors":
    {
      "id":
        [
          "The value 'properties' is not valid."
        ]
    }
}

i also tried the following urls with different failure:
https://demo.acvts.nist.gov:443/dependencies/properties
https://demo.acvts.nist.gov:443/acvp/dependencies/properties

{
  "status": "404",
  "statusText": "Not Found",
  "data": ""
}

the following urls do work:
GET Url: https://demo.acvts.nist.gov:443/acvp/v1/dependencies
GET Url: https://demo.acvts.nist.gov:443/acvp/v1/dependencies/2

**Comment by livebe01** [comment]
Hi @mmccarl, /dependencies/properties is an endpoint that's defined in the ACVP, but we haven't implemented it. We don't have plans to implement this in the near term.
