### ISSUE TITLE
TupleHash MCT lacks feedback of data 

### ISSUE THREAD

**Issue by blackbird1999** [usnistgov/ACVP-Server#216]
"The main problem here, though, is that the line:

    workingBits = Left(T[i-1][0] || ZeroBits(288), 288);

in the TupleHash MCT pseudocode (see [draft-celi-acvp-xof.html#name-tuplehash-monte-carlo-test](https://pages.nist.gov/ACVP/draft-celi-acvp-xof.html#name-tuplehash-monte-carlo-test)) should be

    workingBits = Left(Output[i-1] || ZeroBits(288), 288);

with Output[0] properly initialized to the input tuple (rather than putting that in T[0][0])!

As the pseudocode stands, there is no feedback between the output of the hash function and _workingBits_ -- in fact, its first 9 bytes and those of _T[i][0]_ remain invariant, so _tupleSize_ is also invariant. Clearly that is not what the server is executing.

_Originally posted by @markowitz-isc in https://github.com/usnistgov/ACVP-Server/issues/211#issuecomment-1146751667_"

**Comment by livebe01** [comment]
Sorry we haven't had a chance to get to this yet. Just letting you know that we haven't missed it.

**Comment by jbrock24** [comment]
I am currently investigating this and will get back to you shortly.

**Comment by markowitz-isc** [comment]
thanks, joel. to be clear, this is just a problem with the _draft document_... the latest sample test vectors we received produced the expected outputs when the feedback i suggested above was performed, so the current _software_ appears to be correct.

**Comment by blackbird1999** [comment]
Hi Joe,

The issue isn't with the code, it's with the draft documentation. The documentation needs to be updated.
Thanks!
