### ISSUE TITLE
Internal service error after server update

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP-Server#219]
On demo after 1.0.25 update,

POSTing to /acvp/v1/login gives 500 error:

internal service error, contact service provider

Thanks,
Andrew

**Comment by jarnold01** [comment]
Checking into this...

**Comment by jarnold01** [comment]
Should be good now; please confirm @abkarcher ?

**Comment by abkarcher** [comment]
@jarnold01  I am now getting an "Access denied. Reason: user not authorized to access this application" error.

**Comment by jarnold01** [comment]
care to give it another go please @abkarcher ?

**Comment by abkarcher** [comment]
@jarnold01 I am still getting the same error. Thanks for looking into it so promptly!

**Comment by abkarcher** [comment]
@jarnold01 it looks like it is letting us login now. Thanks!

**Comment by jarnold01** [comment]
Excellent. Yeah, this was baffling for us, but it ended up being an intermittent network problem causing the issue in the end. Thanks again for helping us test this out.
