### ISSUE TITLE
Error in posting SHA-1 result on production server

### ISSUE THREAD

**Issue by dsikkema-atsec** [usnistgov/ACVP-Server#22]
**environment**
Production  server

**testSessionId**
The test session ID - 2767

**vsId**
The vectorSet ID - 26507

**Algorithm registration**
SHA-1

**Endpoint in which the error is experienced**
https://acvts.nist.gov:443/  PUT

**Expected behavior**
Expected the SHA-1 results to verify with no failures

**Additional context**
All other algorithms were validated without error. I compared the SHA2-256 response file with SHA-1 and first segment looked the same with exception of vector ID and algorithm.
The error seen is this:
"error": "Error converting value \u0022SHA-1\u0022 to type \u0027NIST.CVP.Crypto.Common.Hash.ShaWrapper.ModeValues\u0027. Path \u0027testGroups[0].function\u0027, line 9, position 25."

**Comment by Kritner** [comment]
@dsikkema-atsec I re-ran that particular validation through the system, you should now be able to receive the results.
