### ISSUE TITLE
A task was canceled error message

### ISSUE THREAD

**Issue by jonahmvp** [usnistgov/ACVP-Server#223]
**environment**
Demo

**testSessionId**
279495

**vsId**
1116032

**Algorithm registration**
{
    "mode": "sigVer",
    "revision": "FIPS186-4",
    "algorithm": "RSA",
    "prereqVals": [
        {
            "valValue": "same",
            "algorithm": "SHA"
        },
        {
            "valValue": "same",
            "algorithm": "DRBG"
        }
    ],
    "pubExpMode": "fixed",
    "fixedPubExp": "010001",
    "capabilities": [
        {
            "sigType": "pkcs1v1.5",
            "properties": [
                {
                    "modulo": 2048,
                    "hashPair": [
                        {
                            "hashAlg": "SHA2-256"
                        }
                    ]
                },
                {
                    "modulo": 3072,
                    "hashPair": [
                        {
                            "hashAlg": "SHA2-256"
                        }
                    ]
                },
                {
                    "modulo": 4096,
                    "hashPair": [
                        {
                            "hashAlg": "SHA2-256"
                        }
                    ]
                }
            ]
        }
    ]
}

**Endpoint in which the error is experienced**
![error_logs](https://user-images.githubusercontent.com/62976962/187341558-f1733bb5-0d4c-4bd5-bfff-0e4820160c99.PNG)

**Expected behavior**
Pass or fail. 

**Additional information**
Received error message "A task was canceled."

**Comment by livebe01** [comment]
Hi @jonahmvp, can you take a look at the results you submitted? They don't seem to align with the prompt file that was provided for this vector set. For example, the results submitted include results for test cases 57 through 63 in test group 9 whereas the prompt file defines test group 9 as having test cases 49 through 54.

**Comment by livebe01** [comment]
@jonahmvp, I'll close this out as completed, but reach out if you have further questions.
