### ISSUE TITLE
"Failed to generate. Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP-Server#224]
env: Prod

vsID: 169781

Error:

```
[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Failed to generate. Object reference not set to an instance of an object."
  }
]
```

**Comment by livebe01** [comment]
Hi @smuellerDD, not sure what the cause of the error was. But I reran the generation process and you should be able to retrieve your vector set now!

-Ben
