### ISSUE TITLE
Prod server inaccessible after upgrade (internal service error)

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP-Server#226]
Hello,

We seem to be unable to access the prod server after the update.

***ACVP [STATUS][acvp_login:2939]--> Logging in...
***ACVP [ERR][log_network_status:1341]--> error received from server. Message:
***ACVP [ERR][log_network_status:1342]--> [{"acvVersion": "1.0"}, {"error": "Internal service error. Contact service provider."}]
***ACVP [STATUS][acvp_login:2966]--> Login Send Failed
***ACVP [ERR][acvp_run:3684]--> Failed to login with ACVP server

I can get more log details if necessary, just will take a bit.

PS - would it be best to open an issue like this, or email the team when something like this occurs?

Thanks,
Andrew

**Comment by jarnold01** [comment]
Hey @abkarcher , thanks for reporting this error. Should be fixed now; please give it another go and feel free to close this out if it has been resolved.

**Comment by jarnold01** [comment]
Opening a ticket is best; it tracks it and hits all of our emails anyway. :)

**Comment by abkarcher** [comment]
We are back up and running. Thank you!

Andrew
