### ISSUE TITLE
Cannot create new Person object on Prod Server - request hangs in status "initial"

### ISSUE THREAD

**Issue by nvcasey** [usnistgov/ACVP-Server#229]
**environment**
Prod

When I request creation of a new Person object to /acvp/v1/persons the request stays in status 'initial' and no object is created.
It works ok on the Demo server.

Example:

Request JSON:

[
    {
        "acvVersion": "1.0"
    },
    {
      "fullName": "Neil Casey",
      "vendorUrl" : "/acvp/v1/vendors/9810",
      "emails": ["neilcasey@google.com"]
    }
]

Request Status:
{"url":"/acvp/v1/requests/50432","status":"initial"}

Request hangs in this status.

**Comment by livebe01** [comment]
Hi @nvcasey, Step 2 of https://github.com/usnistgov/ACVP/wiki/ACVTS-End-User-Documentation should clear up what's going on. Long story short, you need to send an out of band email to us listing the requests that need approving. We review each request on Prod as part of quality control.

**Comment by celic** [comment]
Hi. This is intentional. Submissions to Prod need manual approval because this is the text that will show up on the NIST website. Please email acvts-prod@nist.gov with your request ID asking for the item to be approved.

**Comment by nvcasey** [comment]
Thanks greatly for the clarifications. I was not aware of the needed approval stage.
