### ISSUE TITLE
Fail to fetch OE list

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP-Server#23]
**environment**
Prod

When trying to fetch the list of OE, it returns

> [
	{
	"acvVersion": "1.0"
	},
	{
	"error": "Internal service error. Contact service provider."
	}
]

And it's working fine in the demo server.

**Comment by Kritner** [comment]
That is most likely due to this issue https://github.com/usnistgov/ACVP/issues/1029

What is the actual URL you're hitting?  If you're able to narrow your query down with filter parameters you may be able to get around the issue until the prod release makes it out.

**Comment by AndrewHYang** [comment]
I was hitting /acvp/v1/oes?offset=0&limit=100.  So what kinda narrow down I can do?

**Comment by Kritner** [comment]
Oh hmm... there was an issue with pulling OEs w/o dependencies from the "query" endpoint.  That is what is fixed on demo through https://github.com/usnistgov/ACVP/issues/1029.  You should be able to go *directly* to a specific oe `/oes/{id}`, but any queries (currently) that would happen to return an OE that did not have dependencies will fail until the change makes it out to prod.

Is there a specific OE id I could try to help you find?

**Comment by AndrewHYang** [comment]
Thanks, @Kritner. We can still access those OE we created ourselves. Can I ask when this fix will be applied to Prod?

**Comment by Kritner** [comment]
https://github.com/usnistgov/ACVP/issues/1029#issuecomment-715421134

Should have been fixed in this release/issue.  Let me know if not, it doesn't seem like I "for sure" knew what the problem was as described by this issue.
