### ISSUE TITLE
SHAKE: input/output length restrictions not applied

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP-Server#234]
**environment**
Demo

**testSessionId**
321960

**vsId**
1237210, 1237211

**Algorithm registration**
SHAKE 128:
```
"messageLength":[
          {
            "min":1344,
            "max":13440,
            "increment":1344
          }
        ],
        "outputLen":[
          {
            "min":1344,
            "max":13440,
            "increment":1344
          }
        ]
```

SHAKE256:
```
"messageLength":[
          {
            "min":1088,
            "max":10880,
            "increment":1088
          }
        ],
        "outputLen":[
          {
            "min":1088,
            "max":10880,
            "increment":1088
          }
        ]
```

Returned data:

- message length has no relationship to the requested message length
- output length is a multiple of the increment size, but max value is not applied

**Comment by livebe01** [comment]
Hi, @smuellerDD, per [Table 3](https://pages.nist.gov/ACVP/draft-celi-acvp-sha3.html#name-sha3-and-shake-capabilities) of the spec, messageLength is not a valid registration property for SHAKE.

I'm not seeing the issue with the output length. See tcId 217 for 1237210 and tcId 197 for 1237210 to see the max output lengths being tested for the respective vector sets.

**Comment by smuellerDD** [comment]
Am Montag, 21. November 2022, 18:25:29 CET schrieb livebe01:

Hi livebe01,

> Hi, @smuellerDD, per [Table
> 3](https://pages.nist.gov/ACVP/draft-celi-acvp-sha3.html#name-sha3-and-shak
> e-capabilities) of the spec, messageLength is not a valid registration
> property for SHAKE.

Thanks for the note
> 
> I'm not seeing the issue with the output length. See tcId 217 for 1237210
> and tcId 197 for 1237210 to see the max output lengths being tested for the
> respective vector sets.

The request contains the outlen to be 

"outputLen":[
          {
            "min":1088,
            "max":10880,
            "increment":1088
          }

but I see other outlens like 128 bits.

Ciao
Stephan

**Comment by livebe01** [comment]
Take a look at the [Test Types and Test Coverage](https://pages.nist.gov/ACVP/draft-celi-acvp-sha3.html#name-test-types-and-test-coverag), the VOT bullet in particular.

**Comment by smuellerDD** [comment]
Am Montag, 21. November 2022, 19:10:44 CET schrieb livebe01:

Hi livebe01,

> Take a look at the [Test Types and Test
> Coverage](https://pages.nist.gov/ACVP/draft-celi-acvp-sha3.html#name-test-t
> ypes-and-test-coverag), the VOT bullet in particular.

Yes, the VOT vectors do provide the right sizes. But the others do not. So, if 
you have a specific SHAKE use case where SHAKE is dedicated to this use case 
and will only generate output for this use case (e.g. in rate chunks), it will 
pass VOT, but fail AFT and MCT.

Ciao
Stephan

**Comment by livebe01** [comment]
Sure, that makes sense @smuellerDD. Do you have such an implementation/such a need? @celic, do you have any additional thoughts on this case?

**Comment by livebe01** [comment]
That makes sense. Thanks @smuellerDD.
