### ISSUE TITLE
ECDSA SigGen Primitive Samples Error 404 Not Found

### ISSUE THREAD

**Issue by afazio2** [usnistgov/ACVP-Server#238]
**environment**
Demo

**testSessionId**
334077

**vsId**
1322756

**Algorithm registration**
[
  {
    "acvVersion":"1.0"
  },
  {
    "isSample":false,
    "operation":"register",
    "certificateRequest":"no",
    "debugRequest":"yes",
    "production":"no",
    "encryptAtRest":"yes",
    "algorithms":[
      {
        "algorithm":"ECDSA",
        "mode":"sigGen",
        "revision":"1.0",
        "componentTest":true,
        "capabilities":[
          {
            "curve":[
              "P-224",
              "P-256",
              "P-384",
              "P-521"
            ],
            "hashAlg":[
              "SHA2-224",
              "SHA2-256",
              "SHA2-384",
              "SHA2-512"
            ]
          }
        ],
        "prereqVals":[
          {
            "algorithm":"SHA",
            "valValue":"same"
          },
          {
            "algorithm":"DRBG",
            "valValue":"same"
          }
        ]
      }
    ]
  }
]

**Expected behavior**
Expect to receive the vector request + expected results for the requested test vector. 
Received only the vector request and no expected results, an Error 404 Not Found from the server is returned.

**Comment by livebe01** [comment]
Hi @afazio2, expected results cannot be retrieved when `"isSample":false,` as in your registration above.
