### ISSUE TITLE
DEMO Server is not downloading vectors

### ISSUE THREAD

**Issue by ehanson12** [usnistgov/ACVP-Server#240]
**environment**
The environment the issue was experienced (Demo or Prod)
DEMO

**testSessionId**
The test session ID
ALL but also 352339

**vsId**
The vectorSet ID displaying the issue
ALL but 1416490

**Algorithm registration**
The pertinent algorithm registration pieces (algorithm tested, capabilities, etc) in json format

**Endpoint in which the error is experienced**
https://[acvpUrl]/acvp/[endpoint] GET

**Expected behavior**

In downloading vectors the following is OK and then the vectors never download:
 /acvp/v1/testSessions response content received

**Additional context**
Add any other context about the problem here. Thank You!

**Comment by livebe01** [comment]
Hi @ehanson12, can you share what client you are using to create the new test sessions and to attempt to retrieve the resulting vector sets? The test sessions and vector sets are being created successfully on our end. Have you tried to retrieve the vector sets using a different client? From our logs, it looks like a test session is created and the client you're using immediately tries to retrieve the associated vector set three times, but does not try back later. These vector sets take time to generate and are not available instantaneously. I suspect that what is going on is that your client just isn't waiting long enough for the vector sets to be created. Clients need to be able to poll until the vector sets are ready to be retrieved.

**Comment by ehanson12** [comment]
Thanks for looking into this. Normally the client request multiple vectorsets for retrieval later. However, I read reports from another user, that the server was under heavy load and killed the process. The vectorsets would have been retrieved had I not killed the process. Here is a session that ran Sunday that shows the normal flow: 353554.
