### ISSUE TITLE
Demo Server is slow or down.

### ISSUE THREAD

**Issue by ehanson12** [usnistgov/ACVP-Server#248]
**environment**
Demo

**testSessionId**
session 374584
as well as all others we have tried...

**Expected behavior**
Vectors to download in a normal amount of time or three - five times longer. However, some vectors do not download at all.

**Comment by jarnold01** [comment]
hi @ehanson12 - is this still an issue for you? I've had a look this morning and I'm seeing that all services are operating as expected. Please let me know; thanks.

**Comment by ehanson12** [comment]
Jason,

Thank You. I ran a few tests and the sever does indeed look to be back up and running. Thank you for reaching out. - Eric

________________________________
