### ISSUE TITLE
DEMO Server is slow or down (VectorSet download impacted, CreateSession is fine...)

### ISSUE THREAD

**Issue by ehanson12** [usnistgov/ACVP-Server#251]
environment
Demo

Test Session are easily created. However, download of VectorSets is not working...

testSessionId:
session 376866
as well as all others we have tried...

Expected behavior
Vectors to download in a normal amount of time or three - five times longer. However, some vectors do not download at all.

**Comment by celic** [comment]
The queue is pretty backed up. Everything is working, there's just a lot going on.

I see you had a previous question on this a couple days ago. You can check the `https://acvts.demo.nist.gov/health` endpoint to get a general idea for the condition of the server.

**Comment by ehanson12** [comment]
Thank You!
