### ISSUE TITLE
Character Limit

### ISSUE THREAD

**Issue by GlennUL** [usnistgov/ACVP-Server#254]
We have a vendor who's implementation has a version length of 204 characters. When we submit the version on both Demo and Production it gets cut off at 128 characters. We checked things on our end and can see that our system is submitting the full 204 characters but when we receive the approval back it is updated to only the first 128 characters. Is it possible to have the character limit increased or is 128 characters a hard limit?

**Comment by livebe01** [comment]
That is a hard limit. I believe that's the size of the field in our database.

**Comment by GlennUL** [comment]
Thanks Ben! I'll work with our vendor to shorten it.
