### ISSUE TITLE
Add support for the updated algorithm from SHA2 to SHA3.

### ISSUE THREAD

**Issue by jbrock24** [usnistgov/ACVP-Server#259]
In reference to #237, we need to add support for the updated algorithm to SHA3.

**Comment by jbrock24** [comment]
Currently in testing.

**Comment by livebe01** [comment]
The fix for this is now on Demo in release v1.1.0.29.

**Comment by livebe01** [comment]
The fix for this is on Prod in release [v1.1.0.29-hotfix-1](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.29-hotfix-1).
