### ISSUE TITLE
RSA Upload Error on Demo

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP-Server#26]
**environment**
Demo

**testSessionId**
/acvp/v1/testSessions/122000

**vsId**
362043, 362045, 362046

Result of these vector sets is, "error": "Responses for vsId 362043 not received by the server."

And we are trying to submit the result we got rejected as,

> Upload failed. Validation error(s) on JSON payload. : ["Vector set not in 'failed' status.", "Unable to submit results when vector set in 'passed' status.", 'Unable to submit results when vector set has been archived']

It is confusing whether the result was received or not.

**Comment by celic** [comment]
The result you recently submitted was not received. If the vector set has not been touched in 30 days, it gets archived and is no longer available. Also if the vector set has already received a response that passes, it will not accept a new response, as that also triggers an archive. It seems like the latter case applies here. A valid, passing response.json was already submitted. No updates may be made after that.

**Comment by AndrewHYang** [comment]
If a valid response was submitted, then why its result still showing as "Responses for vsId 362043 not received by the server."?

**Comment by AndrewHYang** [comment]
Can I ask any finding of this case? Our lab user reported another test session (/acvp/v1/testSessions/124420) having the same issue. We failed to submit the response, and the result is showing as "error": "Responses for vsId 371298 not received by the server."

**Comment by Kritner** [comment]
@AndrewHYang I'm still looking through, but if you can share more information on the vector set in question 371298, that may be helpful.  

In a quick run through of our logs, I see:

```
2020-11-04T14:28:24.2308912-05:00 [INF] (WebPublic//) HTTP "POST" "/acvp/v1/testSessions/124420/vectorSets/371298/results" responded 400 in 3.2887 ms
2020-11-04T14:28:24.9543691-05:00 [INF] (WebPublic//) HTTP "PUT" "/acvp/v1/testSessions/124420/vectorSets/371298/results" responded 400 in 3.4100 ms
```

It looks like a `POST` was attempted with results (and failed, a 400 was returned), then an almost immediate `PUT` was attempted, which also failed.  `PUT` is only valid after a successful `POST` and subsequent processing of said post.

The only `POST` I'm seeing for vector set 371298 was a failed one.  I don't have specifics as to the nature of the failure, but a 400 would *seemingly* indicated it wasn't a server side error.  Do you have the JSON handy that you attempted to POST?

**Comment by AndrewHYang** [comment]
Our end will retry with PUT if the POST was failed, as we're not certain whether the POST was rejected because it was submitted before. If we can get a specific reject code for that will be perfect.

And I attached the JSONs that we are trying to submit here. Pls check.

[RSA_Response_Files.zip](https://github.com/usnistgov/ACVP-Server/files/5497874/RSA_Response_Files.zip)

**Comment by celic** [comment]
The vsId in the file I checked is not correct. I looked at `acvp-v1-testSessions-124420-vectorSets-371301-response.json` which the name suggests the vsId should be 371301, which as I look up, is your vector set. Inside the file though the vsId is 327732, which is an entirely different vector set, that is not yours. 

Double check to make sure the file you are uploading has the correct vsId as the URL you are uploading it to.

**Comment by celic** [comment]
Yeah confirmed in the code. I have a patch that will give a proper error message when this happens, but you need to double check and make sure the vsID matches in the file and the URL.

**Comment by AndrewHYang** [comment]
Thanks, @celic. I will work with our lab users to check and try again.

**Comment by AndrewHYang** [comment]
@celic Yes, it's our bad. We messed up the vsID. It's working fine now. Thanks.

**Comment by celic** [comment]
A fix is in progress to better report this error message too.

**Comment by Kritner** [comment]
this change is on demo and prod
