### ISSUE TITLE
Prod test session stuck waiting 20+ hrs

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP-Server#261]
**environment**
Prod

**testSessionId**
20422

Created yesterday morning (ET); still waiting on vector sets. We are fine with waits, just wanted to open this in case its a technical glitch and not just an unusually large backlog.

Thanks,
Andrew

**Comment by jbrock24** [comment]
Hi @abkarcher. Currently the Task Queue is just bogged down and has been running requests for probably 24 hours straight. Just a FYI, you can use the Health Status Endpoint to check! Thanks!

**Comment by jbrock24** [comment]
Also, just another FYI, you are currently pretty far down on the list for your first VS. I'm not sure the timeframe, but there are 245 vector sets before yours.

**Comment by abkarcher** [comment]
Thanks for the update!

**Comment by celic** [comment]
Just a heads up, our internal Task Queue Processor (that processes vector set generation) suddenly and quietly died yesterday. Thanks for the ping on this, we were able to start it back up to continue generating.
