### ISSUE TITLE
Unable to log in to Demo server

### ISSUE THREAD

**Issue by geegeea** [usnistgov/ACVP-Server#262]
**environment**
Demo

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
N/A

**Endpoint in which the error is experienced**
login

**Expected behavior**
successful login

**Additional context**
We (Google) get the following error when trying to log in:
Failed to login: acvp: HTTP error [
DEFAULT 2023-05-19T17:03:24.702266Z {
DEFAULT 2023-05-19T17:03:24.702271Z "acvVersion": "1.0"
DEFAULT 2023-05-19T17:03:24.702275Z },
DEFAULT 2023-05-19T17:03:24.702279Z {
DEFAULT 2023-05-19T17:03:24.702292Z "error": "Internal service error. Contact service provider."
DEFAULT 2023-05-19T17:03:24.702295Z }
DEFAULT 2023-05-19T17:03:24.702299Z ]

**Comment by jarnold01** [comment]
@geegeea please email me regarding this error - jason.arnold@nist.gov 

Thanks!

**Comment by jarnold01** [comment]
Emailed with Gurleen and resolved the issue.
