### ISSUE TITLE
Failed to generate. Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by jvdsn** [usnistgov/ACVP-Server#264]
**environment**
Prod

**testSessionId**
21160

**vsId**
236801

**Additional context**
```
[
  {
    "acvVersion": "1.0"
  },
  { 
    "error": "Failed to generate. Object reference not set to an instance of an object."
  }
]
```

I got this strange error again. Do you know what causes this?

**Comment by livebe01** [comment]
Sorry. Not sure. I re-queued the generation process and you can now retrieve the vector set.
