### ISSUE TITLE
MCT message length out of the bound of algorithm properties

### ISSUE THREAD

**Issue by agusanchez86** [usnistgov/ACVP-Server#266]
**environment**
Demo v1.1.0.29

**testSessionId**
402546

**vsId**
1644207 

**Algorithm registration**
`{
			"algorithm": "SHA-1",
			"revision": "1.0",
			"messageLength": [{"min": 0, "max": 65528, "increment": 8}]
}`

**Expected behavior**
The MCT shall be generated with a message length between the given algorithm properties

**Additional context**
The demo server generates a MCT with a message length of 540, which is no between the algorithm properties.

**Comment by AlexThurston** [comment]
We just encountered this issue as well.  

Registration: 
```
{"revision": "1.0", "algorithm": "SHA-1", "messageLength": [{"max": 51200, "min": 0, "increment": 8}]}
```

Server: `Demo`
Test Session ID: `417440`
Vector Set ID:  `1705108`

The MCT test has a message length of `540` which is not divisible by the increment set of 8.

**Comment by null0link** [comment]
I have similar issue for `"vsId": 1656790` (please see attachment) obtained from demo server. 
My interpretation is as follows:
`msg` have 544 bits length, but is should be trimmed as `len` is equal to 540.
Then message for the first hash operation have 3*540 = 1620 bits. With registered `min` value equal to 0, `step` 8 is not an integer divisor of 1620.
 
[406182.zip](https://github.com/usnistgov/ACVP-Server/files/11903109/406182.zip)

**Comment by livebe01** [comment]
This issue has been resolved. Thank you for reporting this!
