### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by jvdsn** [usnistgov/ACVP-Server#269]
**environment**
Demo

**testSessionId**
412260 *and* 412292

**vsId**
1684814 *and* 1685199

**Additional context**
```
[
  {
    "acvVersion": "1.0"
  },
  { 
    "error": "Object reference not set to an instance of an object."
  }
]
```

**Comment by jbrock24** [comment]
Hi @jvdsn, I've re-queued this for you, if it fails again I will debug further.

**Comment by jvdsn** [comment]
@jbrock24 did you requeue 1685199 as well? That one still has the error.

**Comment by jbrock24** [comment]
Apologies, just did. They both seem to have been completed, sorry for that!
