### ISSUE TITLE
The production server is down or very slow

### ISSUE THREAD

**Issue by dsikkema-atsec** [usnistgov/ACVP-Server#271]
**environment**
Prod

**testSessionId**
Several:
21921 - 21936

**vsId**
Several: to list a few 244682, 244675, 244784

**Algorithm registration**
Trying to request official vectors

**Endpoint in which the error is experienced**
https://acvts.nist.gov:443/acvp/v1/testSessions/21927/vectorSets/244673 GET

**Expected behavior**
Expected to get production vectors within an hour.
No vectors have been received.
It has been almost 2 hours.

**Additional context**
Another person from our team has attempted to post production responses but has been unable to do so.
Attempts started over 20 hours ago.

**Comment by livebe01** [comment]
Thanks for letting us know @dsikkema-atsec. We're working on it.

**Comment by livebe01** [comment]
It looks like a part of Prod died Monday AM. It's running again, but is working through a backlog of ~1300 tasks. It may take an hour or two to work through that.
