### ISSUE TITLE
Unable to map KTS-IFC-Sp800-56Br2

### ISSUE THREAD

**Issue by GlennUL** [usnistgov/ACVP-Server#281]
**environment**
Demo and Prod

**Algorithm registration**
{
    "algorithms": [
        {
            "prereqVals": [
                {
                    "algorithm": "CMAC",
                    "valValue": ""
                },
                {
                    "algorithm": "DRBG",
                    "valValue": ""
                },
                {
                    "algorithm": "ECDSA",
                    "valValue": ""
                },
                {
                    "algorithm": "HMAC",
                    "valValue": ""
                },
                {
                    "algorithm": "SHA",
                    "valValue": ""
                },
                {
                    "algorithm": "KMAC",
                    "valValue": ""
                },
                {
                    "algorithm": "SP800-108",
                    "valValue": ""
                },
                {
                    "algorithm": "RSA",
                    "valValue": ""
                },
                {
                    "algorithm": "RSADP",
                    "valValue": ""
                }
            ],
            "algorithm": "KTS-IFC",
            "revision": "Sp800-56Br2",
            "mode": "",
            "iutId": "A1B2C3D4E5",
            "keyGenerationMethods": [
                "rsakpg1-basic"
            ],
            "modulo": [
                2048,
                3072,
                4096,
                6144,
                8192
            ],
            "function": [
                "keyPairGen",
                "partialVal"
            ],
            "scheme": {
                "KTS-OAEP-basic": {
                    "kasRole": [
                        "initiator",
                        "responder"
                    ],
                    "keyGenerationMethods": {},
                    "ktsMethod": {
                        "hashAlgs": [],
                        "supportsNullAssociatedData": true,
                        "associatedDataPattern": "l||uPartyInfo||vPartyInfo",
                        "encoding": [
                            "concatenation"
                        ]
                    },
                    "macMethods": {},
                    "l": 512
                }
            },
            "fixedPubExp": "010001"
        }
    ],
    "encryptAtRest": false,
    "isSample": false
}

**Expected behavior**
Successful generation of vectors.

**Additional context**
When trying to create a test session for KTS-IFC we receive the following error message: Validation error(s) on JSON payload. : ['Unable to map KTS-IFC-Sp800-56Br2 - index 0 to an internal algorithm id.']

**Comment by livebe01** [comment]
Hi Glen, can you try setting mode to null instead of setting it to the empty string? Or omitting mode altogether?

**Comment by GlennUL** [comment]
Hi Ben, Thanks for that! I was able to generate vectors once the mode field was removed.
