### ISSUE TITLE
Large number of vectors failed to generate

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP-Server#283]
**environment**
Prod

**testSessionId**
24067
24070
24071
24072
24073
24074
24075
24076
24077
24078
24080
24081
24082
24083
24084
24086
24087
24088
24089
24090
24091

**vsId**
267108
267122
267124
267131
267134
267136
267138
267139
267140
267142
267153
267155
267157
267160
267170
267177
267182
267183
267184
267197
267199
267203
267205
267207
267222
267224
267226
267227
267229
267233
267240
267271
267272
267275
267285
267287
267289
267291
267312
267334
267337
267338
267349
267350
267351
267354
267355
267356
267381
267382
267384
267406
267407
267408
267409

The test vectors in there contain 

```
[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Failed to generate. Object reference not set to an instance of an object."
  }
]
```

**Comment by livebe01** [comment]
Thanks for letting us know. I'm looking into this.

**Comment by livebe01** [comment]
We've resolved the issue and your test vectors are now available.
