### ISSUE TITLE
Demo Health Route giving 503

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP-Server#284]
**environment**
Demo

**Endpoint in which the error is experienced**
`https://demo.acvts.nist.gov/health` GET

**Expected behaviour**
The route would return a 200 with the information

**Additional context**
Right now it seems to be returned a 503 with some of the information in the JSON:
```
{
    "serverVersion": "v1.1.0.30",
    "details": [
        {
            "key": "testSessionProcessing",
            "description": "The TestSession internal processing load status.",
            "data": {
                "healthStatusDefinitions": {
                    "Healthy": "Oldest pending TestSession is < 1 hours old.",
                    "Degraded": "Oldest pending TestSession is > 1 hours old.",
                    "Unhealthy": "Oldest pending TestSession is > 4 hours old."
                }
            }
        }
    ]
}
```

The `serverVersion` key is there, but not the `status`

**Comment by livebe01** [comment]
Thanks @AlexThurston. We should be able to resolve this shortly.

**Comment by livebe01** [comment]
We're churning through a backlog of tasks from last week at the moment, but this issue is resolved.

**Comment by AlexThurston** [comment]
It looks like DEMO is giving 503 again for the health route.  It seems like this becomes an issue each time there is maintenance.  Could it be that it's related to that in some what since I think there was some maintenance over the weekend.

**Comment by jarnold01** [comment]
Hi @AlexThurston - there was an unexpected issue with the TQP that occurred over the weekend. We discovered and resolved it upon logging in this morning. It is currently working through the backlog and should be caught up shortly. That being said, appreciate you highlighting the /health endpoint 503 error.

**Comment by AlexThurston** [comment]
No worries.  Thanks for the prompt response.
