### ISSUE TITLE
requesting help or documentation for "Expected EphemeralKeyIut but was not supplied"

### ISSUE THREAD

**Issue by ehanson7** [usnistgov/ACVP-Server#286]
**environment**

DEMO

**testSessionId**

437462

**vsId**

1822672

**Expected behavior**

We are requesting KAS-FFC-SHA2-256 and looking for help or description on how to fix: "Expected EphemeralKeyIut but was not supplied"

      {
        "tcId": 71,
        "result": "failed",
        "reason": "Expected EphemeralKeyIut but was not supplied"
      },
      {
        "tcId": 72,
        "result": "failed",
        "reason": "Expected EphemeralKeyIut but was not supplied"
      },
      {
        "tcId": 73,
        "result": "failed",
        "reason": "Expected EphemeralKeyIut but was not supplied"
      },
      {
        "tcId": 74,
        "result": "failed",
        "reason": "Expected EphemeralKeyIut but was not supplied"
      },
      {
        "tcId": 75,
        "result": "failed",
        "reason": "Expected EphemeralKeyIut but was not supplied"
      },
      {
        "tcId": 76,
        "result": "failed",
        "reason": "Expected EphemeralKeyIut but was not supplied"
      },
      {
        "tcId": 77,
        "result": "failed",
        "reason": "Expected EphemeralKeyIut but was not supplied"
      },
      {
        "tcId": 78,
        "result": "failed",
        "reason": "Expected EphemeralKeyIut but was not supplied"
      },
      {
        "tcId": 79,
        "result": "failed",
        "reason": "Expected EphemeralKeyIut but was not supplied"
      },
      {
        "tcId": 80,
        "result": "failed",
        "reason": "Expected EphemeralKeyIut but was not supplied"
      },
      {
        "tcId": 81,
        "result": "failed",
        "reason": "Expected EphemeralKeyIut but was not supplied"
      },
      {
        "tcId": 82,
        "result": "failed",
        "reason": "Expected EphemeralKeyIut but was not supplied"
      },
      {
        "tcId": 83,
        "result": "failed",
        "reason": "Expected EphemeralKeyIut but was not supplied"
      },
      {
        "tcId": 84,
        "result": "failed",
        "reason": "Expected EphemeralKeyIut but was not supplied"
      },
      {
        "tcId": 85,
        "result": "failed",
        "reason": "Expected EphemeralKeyIut but was not supplied"
      },
      {
        "tcId": 86,
        "result": "failed",
        "reason": "Expected EphemeralKeyIut but was not supplied"
      },
      {
        "tcId": 87,
        "result": "failed",
        "reason": "Expected EphemeralKeyIut but was not supplied"
      },
      {
        "tcId": 88,
        "result": "failed",
        "reason": "Expected EphemeralKeyIut but was not supplied"
      },
      {
        "tcId": 89,
        "result": "failed",
        "reason": "Expected EphemeralKeyIut but was not supplied"
      },
      {
        "tcId": 90,
        "result": "failed",
        "reason": "Expected EphemeralKeyIut but was not supplied"
      },

**Comment by Kritner** [comment]
The FFC schema you're testing against requires the IUT (you) to provide an ephemeral public key for this test case/schema.  

I can't look at your vector set, but just as the general idea, for a schema where both parties contribute a keypair to the diffie hellman calculation, the server would provide to the IUT an ephemeral public key where the server has the private.  Similarly, the expectation is that the IUT would provide to the server its ephemeral public key, so that both parties can perform the diffie hellman calculation, and potentially subsequent KDF against the same shared secret.

**Comment by jbrock24** [comment]
@ehanson7 Can this be closed? Do you still require further help?

**Comment by ehanson7** [comment]
Yes, Please do close out. Thank You!
