### ISSUE TITLE
Production server seems down or slow

### ISSUE THREAD

**Issue by dsikkema-atsec** [usnistgov/ACVP-Server#288]
environment
Prod

testSessionId
24607 and 24608

vsID
several

Algorithm registration
Trying to request official vectors

Endpoint in which the error is experienced
GET

Expected behavior
Expected to get production vectors within an hour.
No vectors have been received.
It has been almost 1 hour.

**Comment by livebe01** [comment]
Thanks @dsikkema-atsec. The Prod environment is alive and processing tasks, but it is working through a backlog. 

Ps see https://github.com/usnistgov/ACVP-Server/wiki/Health-Check---Server-Version-Endpoint
