### ISSUE TITLE
"Decryption Failed" when retrieving KTS-IFC validation results

### ISSUE THREAD

**Issue by tobyp** [usnistgov/ACVP-Server#29]
**environment**
Demo

**testSessionId**
123980

**vsId**
369802, 369803

**Algorithm registration**
```
  {
    "algorithm": "KTS-IFC",
    "revision": "Sp800-56Br2",
    "prereqVals": [{"algorithm":"DRBG","valValue":"same"},{"algorithm":"RSA","valValue":"same"},{"algorithm":"SHA","valValue":"same"}],
    "function": ["keyPairGen", "partialVal"],
    "iutId": "012345678",
    "keyGenerationMethods": ["rsakpg1-crt"],
    "modulo": [2048, 3072, 4096],
    "fixedPubExp": "010001",
    "scheme": {
      "KTS-OAEP-basic": {
        "kasRole": ["initiator","responder"],
        "ktsMethod": {
          "hashAlgs": ["SHA2-256"],
          "supportsNullAssociatedData": true,
          "associatedDataPattern": "label",
          "encoding": ["concatenation"]
        },
        "l": 256
      }
    }
  }
```
and the same with `"hashAlgs": ["SHA2-384"]` and `"l": 384`

**Endpoint in which the error is experienced**
`GET acvp/v1/testSessions/123980/vectorSets/369802/results` and `GET acvp/v1/testSessions/123980/vectorSets/369803/results`

**Expected behavior**
Information about the pass/fail state of each test case

**Additional Context**
- The response is merely `[{"acvVersion": "1.0"}, {"error": "Decryption failed."}]`
- POST-ing the responses did not return any errors

**Comment by Kritner** [comment]
I'll need to put in a fix for this on our end.  Basically I was taking what the SP stated and when an "Decrypt Failure" occurred, stopping all processing.  While that works for the crypto implementation itself, it doesn't work out so great when the test case responses cause a decrypt failure 😅

**Comment by Kritner** [comment]
This change will be on demo from release [v1.1.0.14](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.14) after the scheduled maintenance.

**Comment by Kritner** [comment]
This change is on production in release [v1.1.0.14](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.14)
