### ISSUE TITLE
Is Demo Currently Having Difficulties

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP-Server#290]
The health route is returning 503s and it seems like vector sets for test sessions are not being created.

I have a slew of them that are still waiting for certain vectors sets to be generated.

Other resource APIs seems to be responding correctly.

**Comment by AlexThurston** [comment]
It also seems like submitted vector set responses aren't being processed either.

**Comment by livebe01** [comment]
Thanks Alex. Demo is back up and running and processing through a backlog.
