### ISSUE TITLE
GET VectorSet, ExpectedVectorSet and TestSession returns 'retry 30'

### ISSUE THREAD

**Issue by mmccarl** [usnistgov/ACVP-Server#292]
**environment**
Demo

**testSessionId**
439493

**vsId**
1830888

On about 2023-09-24 18:22:30 GMT I submitted the following algorithm registration:

`   [
      {
            "acvVersion": "1.0"
        },
        {
            "isSample": true,
            "algorithms": [
                {
                    "keyLen": [
                        128,
                        192,
                        256
                    ],
                    "kwCipher": [
                        "cipher"
                    ],
                    "revision": "1.0",
                    "algorithm": "ACVP-AES-KWP",
                    "direction": [
                        "encrypt",
                        "decrypt"
                    ],
                    "payloadLen": [
                        {
                            "max": 4096,
                            "min": 8,
                            "increment": 8
                        }
                    ],
                    "prereqVals": []
                }
            ]
        }
    ]
`
For which i received the following test session response:

`    [
        {
            "acvVersion": "1.0"
        },
        {
            "url": "\/acvp\/v1\/testSessions\/439493",
            "createdOn": "2023-09-24T18:22:31Z",
            "expiresOn": "2023-10-24T18:22:31Z",
            "vectorSetUrls": [
                "\/acvp\/v1\/testSessions\/439493\/vectorSets\/1830888"
            ],
            "publishable": false,
            "passed": false,
            "isSample": true,
            "accessToken": "eyJhbGciOiJIUzI..."
        }
    ]`

From that point forward, requests for the vector set and expected vector set have returned 'retry 30'.   Also, subsequent attempts to GET test session 439493 return 'retry 30' -- quite unexpected since i did get a good response from the registration.

**Comment by livebe01** [comment]
Hi @mmccarl, we're not 100% on what went wrong with that test session. We see where an error occurred as part of creating that test session, but not sure why. Can you start over/create a new test session and let us know if you run into any further issues?

**Comment by mmccarl** [comment]
i was able to run it today (tsid 447982).  at the time of the original attempt, i had submitted quite a few requests -- many for the same aes-kwp algorithm but with slightly different options selected -- but only one had this problem.  i noticed it because the 'getvector' requests ended up on our retry queue where they were retried approximately every 2 minutes.

sounds like gremlins.

you can close this or keep it -- your choice.

thanks

**Comment by jbrock24** [comment]
We'll close it, thanks for rerunning and your patience.
