### ISSUE TITLE
Error generating key

### ISSUE THREAD

**Issue by GlennUL** [usnistgov/ACVP-Server#296]
**environment**
Demo

**testSessionId**
456883

**vsId**
1964249 and 1964251

**Expected behavior**
Generated vectors.

**Additional context**
vsId 1964249 has the following error: "error": "Error generating key: Index and length must refer to a location within the string. (Parameter 'length')"

vsId 1964251 has the following error:  "error": "Unable to generate key"

**Comment by livebe01** [comment]
Hi @GlennUL. We've fixed the issue and your vector sets have been generated.

**Comment by livebe01** [comment]
Hi @GlennUL. We've fixed the issue and your vector sets have been generated.
