### ISSUE TITLE
RSA Decryption Primitive (SP800-56Br2) failures

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP-Server#299]
**environment**
demo

**testSessionId**
459660

**vsId**
1987254

Hello,

When testing RSA Decryption Primitive with its newer revision on OpenSSL, I am hitting some failures where the ACVP server expects the IuT to fail a decryption operation, but the IuT passes. Is there anyway I can find out what failures were injected on the server side that cause these failures to be expected? (If not, can someone point me to where in the gen/val code these failures are injected if it is publicly visible?)

Thanks!
Andrew

**Comment by jbrock24** [comment]
Hi @abkarcher, I believe this is what you're asking for, but if not, please let me know. The failures we check for are what is listed inside the spec sheet in section [7.1.2.1](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Br2.pdf). They can be found within GenVals code [here](https://github.com/usnistgov/ACVP-Server/blob/master/gen-val/src/generation/src/NIST.CVP.ACVTS.Libraries.Generation/RSA/SP800_56Br2/DpComponent/TestCaseExpectations/TestCaseExpectationsProvider.cs). Hope this helps, let me know if you have questions.

**Comment by abkarcher** [comment]
Thank you, that was extremely useful!

I have a general question about RSA DP that I am not sure if best for this forum but I will pose it anyway.  RSA DP testing does not seem like its required for every validation that still use RSA in other systems like KAS-IFC. Was curious if it would be possible to get some reasoning for this; will it be a stricter requirement in the future with the new revision?

I also am unable to determine if these bounds rules for ct, specifically `1 < ct < n - 1`, apply to RSA usage outside of RSADP. Should the regular OpenSSL RSA pkey decrypt operation be checking these bounds, or would these bounds only apply to a implementation specifically adhering to the RSADP definition?

No worries if answers can't be provided here. 

Thanks!
Andrew
