### ISSUE TITLE
Demo Server Version is Invalid/Incorrect

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP-Server#304]
**environment**
Demo

**testSessionId**
N/A

**vsId**
N/A

**Endpoint in which the error is experienced**
`https://demo.acvts.nist.gov/health` `GET`

It looks like something wrong with the data returned for the `serverVersion`.

```
{
  "status": "Healthy",
  "serverVersion": "jrb-make-pubexpmode-random-default",
  "details": [
    {
      "key": "testSessionProcessing",
      "status": "Healthy",
      "description": "The TestSession internal processing load status.",
      "data": {
        "healthStatusDefinitions": {
          "Healthy": "Oldest pending TestSession is < 1 hours old.",
          "Degraded": "Oldest pending TestSession is > 1 hours old.",
          "Unhealthy": "Oldest pending TestSession is > 4 hours old."
        }
      }
    }
  ]
}
```

**Comment by livebe01** [comment]
Thanks @AlexThurston. The serverVersion for Demo should be v1.1.0.32. This is something we know about and will look into/fix. It cropped up when we deployed a hotfix to Demo last Tuesday.

**Comment by livebe01** [comment]
The correct serverVersion should now appear via the health endpoint.
