### ISSUE TITLE
Unable to generate Signature Primitive 2.0 vectors

### ISSUE THREAD

**Issue by LReed-ldos** [usnistgov/ACVP-Server#306]
**environment**
Production

**Algorithm registration**
{
        "algorithms": [
        {
                "algorithm": "RSA",
                "mode": "signaturePrimitive",
                "revision": "2.0",
                "pubExpMode": "fixed",
                "fixedPubExp": "010001",
                "keyFormat": [
                    "standard"
                ]
                ,
                "modulo": [
                    2048,
                    3072,
                    4096
]
}
] 
}

**Expected behavior**
Successful generation of vectors.

**Additional context**
When trying to generate RSA signaturePrimitive 2.0 vectors on the production server, we receive the following error message: "Unable to map RSA-signaturePrimitive-2.0 - index 11 to an internal algorithm id."  We can generate without issue on the demo server.

**Comment by jbrock24** [comment]
Hi @LReed-ldos, that error is due to the algorithm not being enabled on Production, but as you said, it's working fine on Demo. Just waiting to find out if we can enable it, will let you know when I find out. Sorry for the inconvenience, but we'll get this handled shortly.

**Comment by jbrock24** [comment]
Go ahead and give it another try @LReed-ldos, let me know if you have any issues.
