### ISSUE TITLE
Production vector sets are not being generated and health route seems to be giving 503

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP-Server#307]
**environment**
Prod

**testSessionId**
27588 (but also a bunch of others)

It seems as though while the test session was able to be created, the vectors sets are not being generated.

It might not be related, but it also seems that the health route for **production** is returning a 503.

**Comment by jbrock24** [comment]
Hi @AlexThurston, double checked and they all appear to have been Processed upon restart. There was an error at that time on Prod and it needed a restart to fix. Can you double check that your VS are't available? Thanks!
