### ISSUE TITLE
ECDSA - Add B and K Curves

### ISSUE THREAD

**Issue by jbrock24** [usnistgov/ACVP-Server#309]
Return B and K curves back to Deterministic ECDSA and ECDSA FIPS 186-5.

**Comment by jbrock24** [comment]
Completed as part of *.34 release. Tested and merged, will go out next.

**Comment by livebe01** [comment]
The fix for this is on Demo in release [v1.1.0.34](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.34).

**Comment by livebe01** [comment]
The fix for this is now on Prod as part of the [v1.1.0.34](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.34) release.
