### ISSUE TITLE
RSA 56Br2 decryption primitive

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP-Server#310]
**environment**
Demo

**vsId**
2082972

The test vector contains data that can be successfully decrypted, but the server expects a failure. Looking at the vector, it truly looks odd as you see below. But can you please refer to the particular requirement in the standard where such data is expected to be rejected?

```
"ct": "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001",
...
```

Thanks a lot.

**Comment by jbrock24** [comment]
This is something obtained from the [RsaDpDisposition](https://github.com/usnistgov/ACVP-Server/blob/master/gen-val/src/oracle/src/NIST.CVP.ACVTS.Libraries.Oracle.Abstractions/DispositionTypes/RsaDpDisposition.cs), which matches one of the failure conditions for the CT found in section [7.1.2](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Br2.pdf) of the documentation.

`If the ciphertext c does not satisfy 1 < c < (n – 1), output an indication that the ciphertext is out of range, and exit without further processing.`

Hopefully this helps, please let me know if there's anything else I can help with.

**Comment by smuellerDD** [comment]
That helps, thanks a lot!
