### ISSUE TITLE
EdDSA - Add contextLength as registration property

### ISSUE THREAD

**Issue by jbrock24** [usnistgov/ACVP-Server#311]
Add the ability for users to specify an emtpy context string based on 7.6 and 7.8 of FIPS 186-5.

**Comment by livebe01** [comment]
The fix for this is on Demo in release [v1.1.0.34](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.34).

**Comment by livebe01** [comment]
The fix for this is now on Prod as part of the [v1.1.0.34](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.34) release.
