### ISSUE TITLE
When building ACVP_Server,  Package Microsoft.Orleans.Client 1.0.0 is not compatible with net6.0

### ISSUE THREAD

**Issue by JerryDevis** [usnistgov/ACVP-Server#316]
Hello, 
I am building ACVP_Server. when I build GenValAppRunner, I suffer from some problem. The log is as follows. How I can build ACVP_Server. Thanks.
`NIST.CVP.ACVTS.Generation.GenValApp.csproj : error NU1202: Package Microsoft.Orleans.Client 1.0.0 is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Package Microsoft.Orleans.Client 1.0.0 does not support any target frameworks.`

**Comment by Kritner** [comment]
From the readme: https://github.com/usnistgov/ACVP-Server?tab=readme-ov-file#sym-links

ACVP doesn't use Microsoft.Orleans.Client 1.0.0 - this is likely just the first package version found.  This seems to be indicative of now having set up the sym link between the root folder and `_config` folder

**Comment by JerryDevis** [comment]
> From the readme: https://github.com/usnistgov/ACVP-Server?tab=readme-ov-file#sym-links
> 
> ACVP doesn't use Microsoft.Orleans.Client 1.0.0 - this is likely just the first package version found. This seems to be indicative of not having set up the sym link between the root folder and `_config` folder

OK. Thanks a lot. When I finish compiling, I execute 
` dotnet run --project  ACVP-Server-1.1.0.33/gen-val/samples/GenValAppRunner/src/bin/Debug/net6.0/  -g ACVP-Server-1.1.0.33/gen-val/json-files/ACVP-AES-CBC-1.0/registration.json`
I got the following error:
`Couldn't find a project to run. Ensure a project exists in  ACVP-Server-1.1.0.33/gen-val/samples/GenValAppRunner/src/bin/Debug/net6.0/, or pass the path to the project using --project.`
How I can run ACVP_Server?
