### ISSUE TITLE
RSA 186-5 KAT Tests

### ISSUE THREAD

**Issue by GlennUL** [usnistgov/ACVP-Server#317]
**environment**
Demo & Prod

**Additional context**
We have a vendor who needs to test RSA KeyGen 186-5 however they are only able to run the GDT tests and not the KAT tests. In section  8.1 of the ACVP documentation it states that setting the test session to 'infoGeneratedByServer' true enables the KAT tests but when we set it to false with a random public exponent it still includes the KAT tests. I came across an older ticket (https://github.com/usnistgov/ACVP/issues/660) where Chris makes it seem that in order to test without the KAT tests that it has to be a fixed public exponent. Is it not possible to test only the GDT tests if the public exponent is random?

Thanks!

**Comment by GlennUL** [comment]
Hi @jbrock24 any guidance on this situation? Thanks!

**Comment by jbrock24** [comment]
Hi @GlennUL, apolgogies for the reply timeframe. As far as I can tell, [these](https://github.com/usnistgov/ACVP-Server/blob/68e546cb2af86ba5f08b26fd2ac92ef13b36b54b/gen-val/src/generation/src/NIST.CVP.ACVTS.Libraries.Generation/RSA/Fips186_5/KeyGen/TestGroupGeneratorKat.cs#L17-L18) are the only two conditions in which a KAT wouldn't be created:

```c#
            if (parameters.PubExpMode == PublicExponentModes.Fixed) return Task.FromResult(testGroups);
            if (parameters.KeyFormat == PrivateKeyModes.Crt) return Task.FromResult(testGroups);
```

I will ask how we want to handle this during our dev meeting this afternoon, and will have a fix/method to get this working for you.

**Comment by GlennUL** [comment]
Hi @jbrock24 I just wanted to check in to see if a possible workaround has been figured out.

**Comment by jbrock24** [comment]
@GlennUL We can do a custom vector set for you to handle this. If this is something you'd be interested in, let me know and I will work to begin getting that ready for you.

**Comment by GlennUL** [comment]
Thanks @jbrock24 Do you want me to setup a session on the Demo server so that way you can just drop the custom vector onto the server for us to download and process?

**Comment by jbrock24** [comment]
I'll let you know tomorrow, I'm going to set it up for then, thanks for your patience.

**Comment by jbrock24** [comment]
@GlennUL Please run another through the Demo and I'll process it, thanks!

**Comment by GlennUL** [comment]
Hi @jbrock24 I just set this up on the Demo server under test session 503648 and vsid 2284908.

**Comment by jbrock24** [comment]
Great thanks, I'll get that process moving, appreciated.

**Comment by jbrock24** [comment]
Should have those files available sometime soon, I've forwarded them to be posted for you. I'll let you know when it's accomplished.

**Comment by GlennUL** [comment]
Thanks for the update Joel!

**Comment by jbrock24** [comment]
Check that they're available for download, they **should** be, thanks a lot for your patience.

**Comment by GlennUL** [comment]
I've successfully downloaded the vector. Thanks again for all your assistance and I'll let you know when we need the Production vector.

**Comment by GlennUL** [comment]
Hi @jbrock24 We're ready to proceed with the Production testing. I have created the session on the server under test session  28946. I believe the vsid should be 339007 but I am unable to confirm without pulling in the vector since this test session has multiple keygen vectors being generated in it. If you need anything else please let me know. Thanks!

**Comment by jbrock24** [comment]
Hi @GlennUL Thanks for this, I'll get to this tomorrow and let you know by the afternoon, EST, where we are. Thanks again for your patience.

**Comment by GlennUL** [comment]
Thanks @jbrock24

**Comment by jbrock24** [comment]
@GlennUL What is the best email for me to reach out to you to continue this?

**Comment by livebe01** [comment]
Closing this ticket as it's being handled out of band.
