### ISSUE TITLE
Error returned for ML-KEM FIPS203 encapDecap

### ISSUE THREAD

**Issue by mwcw** [usnistgov/ACVP-Server#319]
**environment**
Demo

**testSessionId**
/acvp/v1/testSessions/500724

**vsId**
/acvp/v1/testSessions/500724/vectorSets/2258924

**Algorithm registration**
```
[
  {
    "acvVersion": "1.0"
  },
  {
    "isSample": false,
    "algorithms": [
      {
        "mode": "encapDecap",
        "functions": [
          "encapsulation",
          "decapsulation"
        ],
        "parameterSets": [
          "ML-KEM-512",
          "ML-KEM-768",
          "ML-KEM-1024"
        ],
        "algorithm": "ML-KEM",
        "revision": "FIPS203"
      }
    ]
  }
]
```

**Endpoint in which the error is experienced**
The demo server

**Expected behavior**
Ultimately returns a set of vectors

**Additional context**
We got the following error message:

```
[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Error encapsulating: Cannot find an implementation class for grain interface: NIST.CVP.ACVTS.Libraries.Orleans.Grains.Interfaces.Pqc.IOracleObserverMLKEMEncapDeferredCaseGrain. Make sure the grain assembly was correctly deployed and loaded in the silo."
  }
]

```

[ml-kem-bad.zip](https://github.com/usnistgov/ACVP-Server/files/14879019/ml-kem-bad.zip)

**Comment by jarnold01** [comment]
Hi @mwcw - we pushed out a hotfix, please give it another go. Thanks!

**Comment by jbrock24** [comment]
We re-queued, it should be already done for you @mwcw.

**Comment by mwcw** [comment]
Thanks I was able to access test vectors.

MW
