### ISSUE TITLE
AES/SHA submission with partial MCT results puts entire vector set in 'error' status

### ISSUE THREAD

**Issue by tobyp** [usnistgov/ACVP-Server#32]
I can't be sure that the partial MCTs are the reason, but I have a strong suspicion. To save time in testing my ACVP test framework, I only run 3 of 100 MCT rounds. When I retrieve results for these uploaded partial responses, I get the error "Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')" on 372084 (AES-CFB128), and "A task was canceled." for the other vector sets.

On the subject of long-running MCTs -- is there some suggestion for how to make these more manageable? I imagine that many embedded implementations are slow enough to make these inconveniently time-consuming. Can the server perform partial validation of only the uploaded rounds? Perhaps only for sample vectors? The number of rounds is not part of the algorithm registration or test group/case parameters, so lowering the number of rounds might be difficult. Does this even make sense for the goals of the MCT?

**environment**
Demo

**testSessionId**
124777

**vsId**
372084 (AES), 372085 (AES), 372108 (SHA), 372109 (SHA), 372110 (SHA)

**Algorithm registration**
```
{"algorithm":"ACVP-AES-CFB128","revision":"1.0","direction":["encrypt","decrypt"],"keyLen":[128,256]}
{"algorithm":"ACVP-AES-ECB","revision":"1.0","direction":["encrypt"],"keyLen":[256]}
{"algorithm":"SHA-1","revision":"1.0","messageLength":[{"min":0,"max":65536,"increment":8}]}
{"algorithm":"SHA2-256","revision":"1.0","messageLength":[{"min":0,"max":65536,"increment":8}]}
{"algorithm":"SHA2-384","revision":"1.0","messageLength":[{"min":0,"max":65536,"increment":8}]}
```

**Endpoint in which the error is experienced**
POST `acvp/v1/testSessions/124777/vectorSets/372108/results` etc.

**Expected behavior**
The specific MCT test cases are marked as failed, but the other test types/groups/cases are processed normally

**Comment by celic** [comment]
Honestly, I think you would get a better result from the server if you provided nothing for that test case. Just list the tcId and nothing else in that object. Otherwise, just upload empty strings for the remainder of the responses. The issue with limiting the number of rounds for `isSample` is that we don't have a way of telling the user how many rounds of the MCT to run, it's not in the group properties. 

While `isSample` is on, you can always request the expected results too to verify yourself. The endpoint should be `GET acvp/v1/testSessions/{tsId}/vectorSets/{vsId}/results/expected`.

**Comment by celic** [comment]
The expected file is always set up so that you may immediately hand it back to us as your submission and you will "pass". You can take the MCT response from that file instead of using your own if you want to do a complete submission in this case.

**Comment by tobyp** [comment]
Thank you for the two suggestions and explanation! Some observations:
- Leaving the entire test group object out of the "testGroups" array results in the MCT test case being marked as "missing"
- Leaving a `{"tgId": 1}`  marks the case as "missing" too
- Leaving a `{"tgId": 1, "tests": [{"tcId": 1234}]}` marks the case as "failed"

In any of these cases, the missing/failed responses can later be (re)submitted using the PUT method to pass the entire vector set :)

This solves my issue.
