### ISSUE TITLE
AES-XTS: Error "General exception. Contact service provider."

### ISSUE THREAD

**Issue by amr-atsec** [usnistgov/ACVP-Server#326]
**environment**
Demo

**testSessionId**
503716

**vsId**
2285478

**Algorithm registration**
        "revision":"2.0",
        "algorithm":"ACVP-AES-XTS",
        "direction":[
          "encrypt",
          "decrypt"
        ],
        "keyLen":[
          256
        ],
        "payloadLen":[
          {
            "min":128,
            "max":65536,
            "increment":128
          }
        ],
        "tweakMode":[
          "number"
        ],
        "dataUnitLen":[
          64000
        ],
        "dataUnitLenMatchesPayload":false

**Expected behavior**
I expect the ACVP server to provide me with test cases. Instead, I receive an error "General exception. Contact service provider." The interesting thing is that when I delete my test vectors and request a fresh batch, the vector set that has this error is always for the same algorithm AES-XTS and no other vector sets have this error. I included the AES-XTS configuration above.

After retying to request test vectors many times, the error does go away and I get test cases, but the error happens frequently enough that this is a problem.

**Comment by livebe01** [comment]
Hi @amr-atsec, if you update the dataUnitLen to include all supported payloadLens, does this error persist?
