### ISSUE TITLE
ML-KEM enc

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP-Server#328]
After checking a sample file, I saw that k is now expected.

Note that I got a pass verdict without the k value.

Note 2, all K value checks fail for me when I provide it.

**Comment by celic** [comment]
Ah did you mean this as a comment on #327 ? We can keep the discussion on one issue to help people track any conversation.

**Comment by smuellerDD** [comment]
Agreed, if you say the random failures are due to this issue - note that I reported random issues for ML-KEM dec as well.

**Comment by celic** [comment]
Closing to move discussion to the other issue.
