### ISSUE TITLE
Approval of PUT (update) metadata submissions in Demo

### ISSUE THREAD

**Issue by mplascencia** [usnistgov/ACVP-Server#33]
**environment**
Demo

**Metadata PUT (update) request**
The pertinent algorithm registration pieces (algorithm tested, capabilities, etc) in json format

request URL
```
https://demo.acvts.nist.gov/acvp/v1/modules/12309 PUT
```

request payload
```
[{
	"acvVersion": "1.0"
}, {
	"description": "Software Algorithms VC1.0 with more details"
}]
```

ACVP response:
```
[
  {
    "acvVersion": "1.0"
  },
  {
    "url": "/acvp/v1/requests/15312",
    "status": "initial"
  }
]
```

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov/acvp/v1/modules/12309 PUT

**Expected behavior**
When testing new metadata object creation (POST) in the demo environment, if there is not an error, the initial request is approved within a couple of minutes automatically.

We have been been testing the update (PUT) of the module metadata object but we have not had any of the initial request URLs come back as approved.  Our initial requests were sent more than 12 hours ago and the request URLs are still marked as "initial".

Our main questions are: 

- Did we submit the requests to update the module metadata correctly?
- Should the demo environment automatically approve the update request if there is not an error in the submission process?

We would like to get our workflow correct before making any updates in prod and we cannot tell at this time if we are making a mistake or not.

Also the protocol spec is not clear on which module properties may be updated after the module is associated with a test session (https://usnistgov.github.io/ACVP/draft-fussell-acvp-spec.html#name-update-a-module).  Are you able to identify which module properties can be updated after association with a test session?

Thank you for your help!

**Additional context**
These are previous attempts to update module metadata that are still "initial"
/acvp/v1/requests/15308
/acvp/v1/requests/15310

**Comment by mplascencia** [comment]
@Kritner @celic Hi, I was just checking to see if there is any feedback that could be provided for this issue.  Thank you!

**Comment by celic** [comment]
Demo has what we call "auto-approve". Any of these requests should be automatically approved. Let me ask around though, we were doing some internal testing last week that may have impacted this setting.

**Comment by celic** [comment]
I see your three requests internally. They all produce an error when I attempt to approve them. Because of this they are not "rejected", they enter into an odd state where they look idle to a user. I'll investigate the error behind this.

**Comment by mplascencia** [comment]
Thank you for looking into this issue!

Do you think the PUT (update) request was malformed?

**Comment by celic** [comment]
It follows the example in the specification exactly, so I would imagine the request is fine, but I'm still looking at this.

**Comment by celic** [comment]
When you made the initial module object, did it have a type? `"hardware"`, `"software"` or `"firmware"`

**Comment by mplascencia** [comment]
It was "type": "Software"

**Comment by celic** [comment]
Fix is going out. The server was mishandling a case where the type wasn't provided.

**Comment by mplascencia** [comment]
Thank you for looking into this issue and providing a fix!

Should the update JSON include the "type" property?

Are there any JSON format adjustments needed for updates in PROD?

**Comment by celic** [comment]
Nope. For a PUT/Update, the only information needed in the JSON is the actual fields that are changing. Everything else will stay the same. This makes it easier to track changes and approve in Prod.

**Comment by celic** [comment]
The fix for this has been deployed to all environments. You should be good to try again. All the pending items for Demo have been approved successfully after the fix was deployed.

**Comment by mplascencia** [comment]
Thank you for providing the fix and updating the environments.  I was able to confirm the existing modules are now approved and new module changes are being auto-approved in demo.
