### ISSUE TITLE
Sample JSON files for SHA2 missing?

### ISSUE THREAD

**Issue by MichaelPaddon** [usnistgov/ACVP-Server#330]
There appear to be no sample JSON files for SHA384, SHA512, SHA512_224, etc.

**Comment by jbrock24** [comment]
@MichaelPaddon Sorry about that, very weird. I just reran and added them, they'll go out with the next hotfix.

**Comment by livebe01** [comment]
Hi @MichaelPaddon, the sample JSON files are now available. See https://github.com/usnistgov/ACVP-Server/tree/master/gen-val/json-files.
