### ISSUE TITLE
ML-KEM enc: server error

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP-Server#333]
**environment**
Demo

**vsId**
2321522 (and others)

After uploading the response, the server answered:

```
[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "General exception. Contact service provider."
  }
]
```

This is the 2nd identical error of KEM encap after trying another vector set earlier.

**Comment by celic** [comment]
Found the error in our code.

Your responses fully passed when I ran them with the fix. :)

**Comment by smuellerDD** [comment]
Thank you 😀
