### ISSUE TITLE
ECDSA SigVer gives componentTest:true test groups when not requested for SHAKE

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP-Server#336]
**environment**
Demo

**testSessionId**
514488

**vsId**
2358750

This test session was requested with componentTest: false for all vector sets. However, the ECDSA sigver test groups have true for componentTest when using SHAKE hash algs.

Might anyone be able to confirm if they have been able to pass ECDSA siggen/sigver testing using SHAKE in general?

Thanks,
Andrew

**Comment by jbrock24** [comment]
Hi @abkarcher, I'll take a look into this, thanks for letting us know.

**Comment by livebe01** [comment]
Hi @abkarcher, do you know if this is a new behavior as of release [v1.1.0.34](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.34)? Or pre-existing issue?

Also, @szendros seems to have been able to test against ECDSA siggen/sigver using SHAKE successfully. See https://github.com/usnistgov/ACVP-Server/issues/301#issuecomment-2133352998

**Comment by abkarcher** [comment]
Hi,

Sorry, I seem to have missed the notification for this. I am not aware if this issue existed prior to .34, I did not notice it until after. 

I am seeing all sorts of failures testing siggen/sigver with a basic implementation, with some specific test groups working fine. I will continue to look into it on my end. 

Thanks,
Andrew

**Comment by livebe01** [comment]
K, thanks Andrew.

**Comment by jbrock24** [comment]
Hi @abkarcher,

This is indeed a bug I added with the last hot fix, I have refactored this out and fixed the bug. It will go out with the next release.

As far as usage goes, this is actually just an issue with it being set incorrecly, but not used. So, in this case, the setting is showing as True, but it's actually False. So, the test data should be fine. 

Thanks,
Joel

**Comment by abkarcher** [comment]
Thanks!

**Comment by livebe01** [comment]
The fix for this is on Demo in release [v1.1.0.35](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.35).

**Comment by livebe01** [comment]
The fix for this is on Prod in release [v1.1.0.35](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.35).
