### ISSUE TITLE
KAS-ECC only generates vectors for the first auxFunction and ignores any others

### ISSUE THREAD

**Issue by tobyp** [usnistgov/ACVP-Server#34]
**environment**
Demo

**testSessionId**
125751

**vsId**
375761

**Algorithm registration**
```{
  "algorithm": "KAS-ECC",
  "revision": "Sp800-56Ar3",
  "prereqVals": [{"algorithm":"DRBG","valValue":"same"},{"algorithm":"SHA","valValue":"same"},{"algorithm":"ECDSA","valValue":"same"},{"algorithm":"HMAC","valValue":"same"}],
  "function": ["keyPairGen","fullVal"],
  "iutId": "012345678",
  "scheme": {
    "onePassDh": {
      "kasRole": ["initiator","responder"],
      "kdfMethods": {
        "oneStepKdf": {
          "auxFunctions": [
            {"auxFunctionName": "SHA2-256"},
            {"auxFunctionName": "SHA2-384"}
          ],
          "fixedInfoPattern": "uPartyInfo||vPartyInfo",
          "encoding": ["concatenation"]
        }
      },
      "l": 512
    }
  },
  "domainParameterGenerationMethods": ["P-256"]
}
```

**Endpoint in which the error is experienced**
GET /acvp/v1/testSessions/125751/vectorSets/375761

**Expected behavior**
Vectors covering all domainParameterGeneration/KDF auxFunction combinations

**Comment by Kritner** [comment]
It's not necessarily "the first" aux function that's selected, it's just not necessarily *all* that are tested each time.  This isn't really a bug, but something could likely be done to have more coverage of the selected registration.  I will try to take care of that sometime soon.

**Comment by tobyp** [comment]
My bad, I got two or three sets and only saw the first aux function instantiated. If the selection is non-deterministic, I might just have gotten "lucky". Thanks for the reply in any case! Is this behavior different on demo/prod, or for sample/non-sample vector sets? How much coverage would be necessary to certify a validation?

**Comment by Kritner** [comment]
You only need the one registration for a validation. The idea is that you register all capabilities of your crypto implementation, and the ACVP server will generate a set of test vectors against any to potentially *all* capabilities within that registration.

**Comment by tobyp** [comment]
There is similar behavior with KTS-IFC (e.g. session 127201 vector set 382800), where I requested OAEP vectors for modulo [2048, 3072 and 4096] and hash algorithms ktsConfiguration.hashAlgs ["SHA2-256", "SHA2-384"], and only got two test groups total - initiator/2048/SHA2-384 and responder/3072/SHA2-256.

I'd be surprised if this was considered sufficient to certify the implementation for 4k OAEP, when that would never be tested at all with these vectors.

**Comment by Kritner** [comment]
A change to group level generation around KAS has been pushed to demo for the [v1.1.0.15](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.15) release.

This change is to use all (rather than a subset) of the registered properties within a registration, without doing a cartesian product of the capabilities.

**Comment by Kritner** [comment]
This change is on prod in release [v1.1.0.15](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.15)
