### ISSUE TITLE
SHAKE-128 JSON test files corrupted

### ISSUE THREAD

**Issue by dspdon** [usnistgov/ACVP-Server#340]
For SHAKE-128, invalid text appears in several JSON test vector files here:
https://github.com/usnistgov/ACVP-Server/blob/master/gen-val/json-files/SHAKE-128-1.0

The invalid text appears in at least these three files:
  internalProjection.json
  prompt.json
  expectedResults.json

An example test case showing the invalid text is copied below.  Could you update these files?

Also, it seems a folder is missing with JSON test vectors for SHAKE-256.

--Don

Snippet from internalProjection.json:

        {
          "tcId": 2,
<<<<<<< HEAD
          "msg": "C0",
          "len": 2,
          "md": "F6B6C4093F0A2CEBA61B9F2C2FEA2CA2",
=======
          "msg": "80",
          "len": 2,
          "md": "9B06E9044324B3E9ADC1739D4FDE097D",
>>>>>>> develop
          "outLen": 128
        },

**Comment by livebe01** [comment]
The merge issues related to the sample SHAKE-128 files should be resolved now

**Comment by dspdon** [comment]
I downloaded the files once again, and now confirm valid format of the content.  Thank you!

**Comment by dspdon** [comment]
Will you be closing this issue, or should I be doing that?
