### ISSUE TITLE
ECDSA failures 

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP-Server#342]
**environment**
Demo

**testSessionId**
518852

We are seeing lots of strange failures on ECDSA siggen and sigver, both revisions 1.0 and 186-5, on client builds that were known to be working prior to the recent informal update.  the detailed results aren't giving much information - 

```
        "tcId": 612,
        "result": "failed",
        "reason": "none",
        "expected": {
          "testPassed": "True"
        },
        "provided": {
          "testPassed": "False"
        }
```

Could someone confirm if any changes were made that would affect the expected inputs/outputs of tests?

Thanks for your time,
Andrew

**Comment by jbrock24** [comment]
Hi @abkarcher, thanks for letting me know, I'll take a look into it.

**Comment by abkarcher** [comment]
After further testing, componentTest: False vector sets seem to work fine, but compontentTest: true tests are where I see issues.

**Comment by jbrock24** [comment]
That's very helpful, thanks!

**Comment by jvdsn** [comment]
@jbrock24 The server recently started giving full messages even when componentTest is set to true. Compare:
```
      {
        "tgId": 1,
        "testType": "AFT",
        "componentTest": true,
        "curve": "P-384",
        "hashAlg": "SHA-1",
        "tests": [
          {
            "tcId": 1,
            "message": "D54F54BBDD49A15D4311BFB96B1F0C00D1E69329",
            "qx": "E952869817933C318AD11877BFC40D82F5F63176E18F6E089E8518102BC71B7CDB17C594E359FB3D0FD1FF85C3D4FC0C",
            "qy": "CC9E75CC447EF842553E2E7E3FD4F33F96743E854F81A240A0A55F890E27E967EADA51A9B30E91B4EF4F99891A49106C",
            "r": "83DAD8B8DCCD1A04BD8077BEC2072AF860C2CB8D597C5B0C68C958FA3CA5056F88CA70859E02148241B9E0B501064AAC",
            "s": "E726EB07C7EBA8C933E332032B14F70E5BB7B8B73EA2BE7E70AE2731E5FAA1FA26DA00A53E8D1A957B50A624442BCBF5"
          },
```
vs
```
      {
        "tgId": 1,
        "testType": "AFT",
        "componentTest": true,
        "curve": "P-192",
        "hashAlg": "SHA-1",
        "tests": [
          {
            "tcId": 1,
            "message": "6D072B588DB925060E55F420C19997669CD7CB997BBFFA4603A336B71FAD71F5D55BB64E588A555FC6F3F219A33655F4FF3163A6300CE6235684E3E318ECFA016E9757178D9798FF7EFBA561E351CAE6864EA319AEDF8D2D7243E6F08AD35A6C54D56A6D1DDB42A34B1186BD3959673C746DB672584ED6D80574F2D03AE31105",
            "qx": "76BDB06827B7FA85B9B69EDE4FFB5028668002656F720E0D",
            "qy": "FCC07AAA01F06D2130DCAA1642BED0512479F44ABCB79B61",
            "r": "A7258FAB54C3A05F5C0E7FBB7C44F430B8D005EBBFF64EAB",
            "s": "61A6DF5FD6F5BFFFC0C68B9B8E1E8068EFE9BD6EFCDF2D9D"
          },
```

**Comment by livebe01** [comment]
We have a fix prepared for this issue. We expect to deploy it via a hotfix release to Demo in the next day or two.

**Comment by livebe01** [comment]
@abkarcher @jvdsn The fix for this is on Demo as of the v1.1.0.35 hotfix that was deployed this morning. Please let us know if this has resolved the issue for you.

**Comment by abkarcher** [comment]
I am seemingly able to pass these tests now. Thanks a bunch!

Andrew

**Comment by jbrock24** [comment]
Great, thanks for your patience! I'll close this out now.
