### ISSUE TITLE
AES-CTR Vector Request file has vsId = 0

### ISSUE THREAD

**Issue by mmccarl** [usnistgov/ACVP-Server#343]
**environment**
Demo

**testSessionId**
tsId 516493

**vsId**
vsId 2370698

**Algorithm registration**
AES-CTR

**endpoint**
 /acvp/v1/testSessions/516493/vectorSets/2370698

when we retrieve the aforementioned vector set, the vsId included in the file is set to 0:

[
    {
      "acvVersion": "1.0"
    },
    {
      "vsId": "0",
      "algorithm": "ACVP-AES-CTR",
      "revision": "1.0",
      "isSample": "1",
      "testGroups": 
  etc...

**Comment by livebe01** [comment]
Hi @mmccarl, Debbie has been in touch with us separately regarding this issue. It should be resolved shortly.
