### ISSUE TITLE
Demo server unresponsive

### ISSUE THREAD

**Issue by GlennUL** [usnistgov/ACVP-Server#346]
Since mid afternoon yesterday the Demo server has been unresponsive to any requests made. Production is responding without any issues.

**Comment by jarnold01** [comment]
Hi @GlennUL - I just ran a test from my acvp client, and checked Demo services, and all seems to be running normally from my vantage point. When you say unresponsive, do you mean you are getting no response at all, or an error?

**Comment by GlennUL** [comment]
Hi @jarnold01 For most requests I'm getting no response however when I try the health check I get an error stating NIST Login Failed Fail to check NIST server health. I was generating vectors yesterday without issue however when I went back to retrieve them around 3pm (PT) I started getting no response.

**Comment by jarnold01** [comment]
Hi @GlennUL - just checked and it looks like the credential you are likely using expired yesterday. I'll reach out via email to get you into the renewal pipeline; look for it shortly.

**Comment by GlennUL** [comment]
Thanks!
