### ISSUE TITLE
SHA LDT test with largetest set to 1 gets full length greater than 1 GB

### ISSUE THREAD

**Issue by dsikkema-atsec** [usnistgov/ACVP-Server#351]
**environment**
demo

**testSessionId**
535738

**vsId**
2506389

**Algorithm registration**
SHA-224 LDT
     {
        "revision":"1.0",
        "algorithm":"SHA2-224",
        "messageLength":[
          {
            "min":0,
            "max":65536,
            "increment":8
          }
        ],
        "performLargeDataTest":[
          1
        ]
      }

**Endpoint in which the error is experienced**
getting demo vectors

**Expected behavior**
With largedata value set to 1, the expected full length was 1 GB

The demo vector returned has a value much larger than that.
        "tgId": 3,
        "testType": "LDT",
        "tests": [
          {
            "tcId": 514,
            "largeMsg": {
              "content": "8099358EC01B12E3",
              "contentLength": 64,
              "fullLength": 8589934592,
              "expansionTechnique": "repeating"
            }
          }
        ]

**Additional context**
Is there a way to get large data set to no larger than 1 GB?

**Comment by livebe01** [comment]
Please see the definition of `largeMsg` structure in [section 6.3](https://pages.nist.gov/ACVP/draft-celi-acvp-sha.html#LD_test) of the SHA2 ACVP algorithm specification.

**Comment by dsikkema-atsec** [comment]
Thank you for the pointer, I am closing this issue as proper length is given
