### ISSUE TITLE
Add error check to KDA HKDF SP800-56Cr1/2 for required setting MacSaltMethods

### ISSUE THREAD

**Issue by jbrock24** [usnistgov/ACVP-Server#358]
No error for missing MacSaltMethods, General Exception. Add requirement and verbose error.

**Comment by jbrock24** [comment]
Fixed, goes out with *37 release.

**Comment by livebe01** [comment]
The fix for this is on Demo in release [v1.1.0.37](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.37).
