### ISSUE TITLE
Noticing substantial response time increase since Nov. 9, 2020 mid afternoon on both environments

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP-Server#36]
**environment**
Demo and Prod

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
N/A

**Endpoint in which the error is experienced**
`GET https://acvts.nist.gov/acvp/v1/vendors`. took **23s**
`GET https://demo.acvts.nist.gov/acvp/v1/vendors` took **26s**
`GET https://demo.acvts.nist.gov/acvp/v1/algorithms` took **17s**
`GET https://acvts.nist.gov/acvp/v1/algorithms` took **30s** before timing out since my HTTP client timeout is set to 30s

**Expected behaviour**
Response times on route calls should not be as high as I'm seeing

**Additional context**
So it looks like starting roughly Nov. 9 in mid afternoon (although this probably isn't exact), the resource routes (vendor, module, etc...) seem to be taking a VERY long time to respond.  They are actually hitting my HTTP client timeout in some cases without responding with the headers.  Listing a vendors, for example is taking upwards of 23 seconds before responding.

**Comment by AlexThurston** [comment]
Yup.  Still seeing it.  Listing vendors seems to range from 2s to 30+ seconds.

**Comment by AlexThurston** [comment]
```
time acvp-cli vendor list > /dev/null
acvp-cli vendor list > /dev/null  0.45s user 0.08s system 12% cpu 4.147 total

time acvp-cli vendor list > /dev/null
acvp-cli vendor list > /dev/null  0.45s user 0.08s system 4% cpu 11.884 total

time acvp-cli vendor list > /dev/null
acvp-cli vendor list > /dev/null  0.46s user 0.08s system 2% cpu 25.813 total

time acvp-cli vendor list > /dev/null
acvp-cli vendor list > /dev/null  0.45s user 0.10s system 4% cpu 12.953 total
```

**Comment by AlexThurston** [comment]
Here's a > 30s timeout:
```
time acvp-cli vendor list > /dev/null
acvp-cli: error: Get "https://demo.acvts.nist.gov/acvp/v1/vendors?limit=20&offset=0": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
acvp-cli vendor list > /dev/null  0.44s user 0.09s system 1% cpu 30.705 total
```

**Comment by Kritner** [comment]
yeah I just did about 50 gets to the vendor listing, most were within 10ms, but i did get two that were 20s+.  I'll see if any of this is reflected in our web-server logs.

**Comment by AlexThurston** [comment]
Even getting a token is taking an exorbitant amount of time.  It took 26s for ACVP to come back to tell me that `TOTP Window has already been used`

And then another 19s before I got a valid token

**Comment by AlexThurston** [comment]
Things seemed to have improved dramatically.  Not sure if this can be attributed to something you changed or not but I thought it was worth letting you know.

**Comment by celic** [comment]
You are correct. A system higher up the stack made some changes that negatively affected performance. They have since reverted. Sorry that this happened, we are trying to work with some of these other teams to help track these issues. User reports here are incredibly helpful, especially with the detail you provided.
