### ISSUE TITLE
[sha3] Merge of ACVP vectors needed

### ISSUE THREAD

**Issue by kriskwiatkowski** [usnistgov/ACVP-Server#360]
**environment**
Both

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
N/A

**Endpoint in which the error is experienced**
N/A

**Expected behavior**
N/A

**Additional context**

Unmerged files were committed. See here:
https://github.com/usnistgov/ACVP-Server/blob/fb44dce5257aba23088256e63c9b950db6967610/gen-val/json-files/SHA3-224-1.0/expectedResults.json#L4838

**Comment by livebe01** [comment]
Thanks for mentioning this. ACVTS no longer supports "SHA3-224",  "revision": "1.0" testing. The "SHA3-224", "revision": "2.0" tests should be used. We'll remove the sample "SHA3-224",  "revision": "1.0" files.

**Comment by kriskwiatkowski** [comment]
Thanks. Yes, removing it is a perfect solution here.

**Comment by livebe01** [comment]
The fix for this is on Demo in release [v1.1.0.37](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.37).

**Comment by livebe01** [comment]
The fix for this is on Prod in release [v1.1.0.37](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.37).
