### ISSUE TITLE
HMAC message length

### ISSUE THREAD

**Issue by amr-atsec** [usnistgov/ACVP-Server#361]
The ACVP server does not allow the user to choose the HMAC message length in a test vector; it is hard-coded to 16 bytes. This affects vendors who have HMAC implementations that do not support arbitrary message lengths, and prevents them from ACVP testing HMAC.

May you please allow the user to choose one or more HMAC message lengths?

**Comment by livebe01** [comment]
Hi @amr-atsec, sure, this is something we can do. What is the timeframe for your needing this feature?

**Comment by livebe01** [comment]
Thanks @amr-atsec. This is something we'd generally like to do for all of our algorithm testing that does not currently support it. I'm going to close this ticket, but if you have any further questions feel free to reach out. I've added this to our internal system for tracking feature requests. If you do find that you need this capability and we haven't had the chance to add it, let us know and we can find a way to make sure that the IUT in question gets tested.
