### ISSUE TITLE
SHA3-224 KATs seem to be incorrect

### ISSUE THREAD

**Issue by kriskwiatkowski** [usnistgov/ACVP-Server#362]
**environment**
Prod

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
SHA3-224 (2.0)

**Endpoint in which the error is experienced**
N/A

**Expected behavior**
N/A

**Additional context**

I'll reuse this PR, maybe two issues can be solved at the same time.

So it also seems to me that KATs for SHA3-224 in the ``gen-val/json-files/SHA3-224-2.0`` folder do not match. Looking at:

https://github.com/usnistgov/ACVP-Server/blob/master/gen-val/json-files/SHA3-224-2.0/prompt.json and https://github.com/usnistgov/ACVP-Server/blob/master/gen-val/json-files/SHA3-224-2.0/expectedResults.json

The first vector is:
```057EF690650D306CA99E49939C0E5FE7A703FB57EE5628C9F9C3A704B27E00193159138A4D6EA3CDA69CEC0AB24032FE3EC8DD2D9EC6A0190B420108DAD90995AAFDD5CF0E9EB084319A1C8E6F320DF8CA81DDBC13AB150526222AFDF4D367C52B5B3EC038FC```

The expected value is:
```
1CEB71FF57FB58D6B27A1F2F471FC6AAE7149E24E26D7563B2B56C91
```

But the "real" SHA3-224 value is for this input is:
```
3459c6f7c53e4102a5fffc252cabfd388eb763b7a235e10cb5b5cb0e
```

**Comment by dspdon** [comment]
Hi Kris

The JSON file specifies input message length of 815 bits, meaning only 7 of the final 8 bits are to be processed.

The digest result published in the JSON file is correct, given an 815 bit input message length.

The result you obtained is also correct, but for a message length of 816 bits.

--Don

**Comment by kriskwiatkowski** [comment]
Ah! This is bit oriented, not byte.
Got ya. Thank you Don.
