### ISSUE TITLE
SHAKE-128 test failure help

### ISSUE THREAD

**Issue by cpu** [usnistgov/ACVP-Server#364]
Hi folks,

Is it possible someone could give some indication of why a particular SHAKE-128 test session failed? It would be wonderful if you could indicate whether it was the AFT, VOT, or MCT test groups that were at fault, or even better, which specific results.

I've spot-checked my SHAKE-128 ACVP implementation's results against expected results from [the demo JSON files](https://github.com/usnistgov/ACVP-Server/tree/master/gen-val/json-files/SHAKE-128-1.0) (where possible, since we don't support `inBit`/`outBit`), and the values produced match expected (e.g. I've positively matched tgId 1 tcId 8 for AFT, tgId 3 tcId 1414 for VOT, and tgId 2 tgId 1392 for MCT) so i'm struggling a little bit trying to determine next steps for debugging.

Since it (to the best of my knowledge) isn't possible to test SHAKE-128 AFT, VOT, or MCT in _isolation_ I'm not even sure if I should direct my attention to a particular test type or not.

I see there are a handful of SHAKE related issues on the repo that are unresolved, but AFAICT none seem pertinent to the capabilities/tests I'm using.

Thanks in advance!

**environment**

Demo.

**testSessionId**
`acvp/v1/testSessions/553123`

**vsId**
`/acvp/v1/testSessions/553123/vectorSets/2630774`

**Algorithm registration**
```json
  {"algorithm":"SHAKE-128","inBit":false,"outBit":false,"inEmpty":false,"outputLen":[{"min":128,"max":4096,"increment":8}],"revision":"1.0"},
```

**Endpoint in which the error is experienced**
`https://demo.acvts.nist.gov/acvp/v1/testSessions/553123/results`

**Expected behavior**

Expected: results to have passed :laughing:

**Comment by jbrock24** [comment]
Hi @cpu - It seems you have failed the MCT testing:
```
    {
      "tcId": 216,
      "result": "failed",
      "reason": "Digest does not match on iteration 1; Digest does not match on iteration 14; Digest does not match on iteration 23; Digest does not match on iteration 36; Digest does not match on iteration 37; Digest does not match on iteration 40; Digest does not match on iteration 52; Digest does not match on iteration 59; Digest does not match on iteration 61; Digest does not match on iteration 67; Digest does not match on iteration 73; Digest does not match on iteration 76; Digest does not match on iteration 78; Digest does not match on iteration 83; Digest does not match on iteration 87"
    },
```

Will continue to look into it, but that's the failure.

**Comment by cpu** [comment]
Thank you, that's a helpful piece of data. I'll focus my debugging accordingly

**Comment by jbrock24** [comment]
No problem, this [documentation segment](https://pages.nist.gov/ACVP/draft-fussell-acvp-spec.html#section-12.17.4) has info on how to obtain the results from the CLI.

**Comment by cpu** [comment]
> No problem, this [documentation segment](https://pages.nist.gov/ACVP/draft-fussell-acvp-spec.html#section-12.17.4) has info on how to obtain the results from the CLI.

:facepalm: Apologies, I didn't realize this information was already available to me. I think I see how I'm intended to access it using the ACVP client I've been using.

I think I can take it from here. Thanks again for pointing me towards the right resources.
