### ISSUE TITLE
Demo server performance?

### ISSUE THREAD

**Issue by cpu** [usnistgov/ACVP-Server#365]
Hi folks,

I've noticed on occasion there can be _very_ slow transaction times with the demo server, both when fetching vectors and for having results verified. In some instances (e.g. `testSessions/553123`) I recorded fetching the vectors taking 97 minutes of wall clock time. It doesn't happen consistently, but when there is a slow period it seems as though cancelling the session and starting another doesn't help.

Is this the sort of performance that should be expected or an outlier? Are there any strategies an end user can deploy to get better results (e.g. operating at off-peak times, tweaking capabilities, etc)?

**environment**
Demo

**testSessionId**
`acvp/v1/testSessions/553123`

**vsId**
N/A

**Algorithm registration**
```json
  {"algorithm":"SHAKE-128","inBit":false,"outBit":false,"inEmpty":false,"outputLen":[{"min":128,"max":4096,"increment":8}],"revision":"1.0"},
```
(One example, I've seen this general performance issue with other algorithms, e.g. EDDSA).

**Endpoint in which the error is experienced**
N/A

**Expected behavior**

Vectors should be fetchable within 1-2 minutes.

**Comment by cpu** [comment]
> From another user, this is likely pretty expected depending on how busy the backend systems are.

Unfortunate. Thanks for the data point/reply.

>  There is a health route you can check to see if the ACVP is detecting that it is running behind on the queue of work that it has which is nice to check when things are slow. It reports a degraded state when it is beyond a threshold of items in the queue (I think it's an hour).

Do you have a reference for the healthcheck endpoint handy? I don't see it mentioned anywhere in [draft-fussell-acvp-spec](https://pages.nist.gov/ACVP/draft-fussell-acvp-spec.html) :thinking: 

> Vectors aren't always available in 1-2 minutes and I don't think there's any documentation saying that they will be :P

Fair, `s/Expected Behaviour/Idealized Behaviour/g` :laughing:

**Comment by jarnold01** [comment]
Hi @cpu , yes what @AlexThurston described is very likely the reason. Our test session queue operates on a "first in first out" basis, and the combination of the amount of vector sets and complexity of the algorithms included creates a reasonable amount of variability in terms of how long it takes to process the submissions. 

Checking the health endpoint (https://demo.acvts.nist.gov/health) is the mechanism that is offered for external users to check to see if there are enough jobs in process to cause degraded performance - to use your verbiage, longer "wall clock" times. I would say, though, that if the health endpoint shows "healthy" but the reality is that it is taking egregiously longer than expected to complete, then that is probably a sign of an internal processing issue, and we would welcome users opening an issue if they believe that to be the case.

Hope this helps.

Thanks,
Jason
