### ISSUE TITLE
cSHAKE-128 hexCustomization registration not respected?

### ISSUE THREAD

**Issue by cpu** [usnistgov/ACVP-Server#366]
Hi folks,

I'm trying to use a capability with `hexEncoding` enabled to get hex encoded cSHAKE-128 customization values in the AFT test type vectors.

The demo server seems to be ignoring that capability and returning the "ASCII" form. 

Am I doing something wrong, or misunderstanding the registration, or is this a server-side bug?

Thanks!

**environment**
Demo

**testSessionId**

`acvp/v1/testSessions/554358`

**vsId**

`/acvp/v1/testSessions/554358/vectorSets/2638062`

**Algorithm registration**
```json
{
  "algorithm": "cSHAKE-128",
  "hexCustomization": true,
  "outputLen": [
    {
      "min": 128,
      "max": 4096,
      "increment": 8
    }
  ],
  "msgLen": [
    {
      "min": 0,
      "max": 65528,
      "increment": 8
    }
  ],
  "revision": "1.0"
}
```

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov/acvp/v1/testSessions/554358/vectorSets/2638062

**Expected behavior**
Since my capability advertised `hexCustomization: true` I expected the `testGroups` to contain `hexCustomization: true`, and for the `tests` in the `testGroup` to have hex encoded customization values. 

Instead I see vectors like the following, with `hexCustomization: false` and `customization` in the tests not hex encoded.

```json
{
    "vsId": 2638062,
    "algorithm": "cSHAKE-128",
    "revision": "1.0",
    "isSample": true,
    "testGroups": [
      {
        "tgId": 1,
        "testType": "AFT",
        "hexCustomization": false,
        "tests": [
          {
            "tcId": 1,
            "msg": "<snipped>",
            "len": 56224,
            "functionName": "",
            "customization": "hK${N5Dt/)p_@bA\u0060\u0026\u002B\u002Bi]1\u0027dfqj_Pt{j]h;WA.;\u003E:Z:Ifu8}hOV6bHZWD\u003E5[JdD:-\u0027!WGi\u003EvnkN#u[|pXlv \u003Ee(5.b3$w_sU6 =\u0060s\u0060U}1_GvyWahAD$]lC{F}lIdV;~0vwku?={w6wo^\u003E1;T!IaSZ7hr$va(7qFt\u0060",
            "outLen": 1752
          },
          <snipped>
```

**Comment by livebe01** [comment]
Hi @cpu, see the description of the `hexCustomization` property in [Table 2](https://pages.nist.gov/ACVP/draft-celi-acvp-xof.html#name-xof-algorithm-capabilities-j). I think that should answer your question.

**Comment by cpu** [comment]
> ASCII strings SHALL be tested regardless of the value within the hexCustomization property.

Thank you. Apologies for missing that.
