### ISSUE TITLE
cSHAKE-128 vectors contain functionNames for algorithm capabilities not advertised

### ISSUE THREAD

**Issue by cpu** [usnistgov/ACVP-Server#367]
Hi again folks,

This is similar to https://github.com/usnistgov/ACVP-Server/issues/366 but relates to the `functionName` field of the returned test AFT vectors.

It's possible that I'm misunderstanding [draft-celi-acvp-xof](https://pages.nist.gov/ACVP/draft-celi-acvp-xof.htm), but my expectation was that since there are [separate algorithm capabilities described](https://pages.nist.gov/ACVP/draft-celi-acvp-xof.html#name-xof-algorithm-capabilities-) for `cSHAKE-*`, `KMAC-*`, `ParallelHash-*` and `TupleHash-*` that if I only sent the capability for `cSHAKE-128` I wouldn't receive vectors with `"functionName": "TupleHash"` or `"functionName": "KMAC"` (for example). In practice the demo server is sending me a variety of function name values in the AFT vectors.

Is this a misunderstanding on my end, a bug, or something else?

**environment**
Demo

**testSessionId**
`acvp/v1/testSessions/554358`

**vsId**
`/acvp/v1/testSessions/554358/vectorSets/2638062`

**Algorithm registration**
```json
{
  "algorithm": "cSHAKE-128",
  "hexCustomization": true,
  "outputLen": [
    {
      "min": 128,
      "max": 4096,
      "increment": 8
    }
  ],
  "msgLen": [
    {
      "min": 0,
      "max": 65528,
      "increment": 8
    }
  ],
  "revision": "1.0"
}
```

**Endpoint in which the error is experienced**
`https://demo.acvts.nist.gov/acvp/v1/testSessions/554358/vectorSets/2638062` GET

**Expected behavior**

I only claim the `cSHAKE-128` algorithm capability to the demo server, so I expect the test vectors returned to all have `"functionName": ""`.

**Additional context**
N/A

**Comment by livebe01** [comment]
Hi @cpu, `"functionName"` provides the value to use for _N_ as defined in Section 3.2 of SP 800-185.
