### ISSUE TITLE
ML-DSA: Test vectors only specify M' rather than individual components

### ISSUE THREAD

**Issue by mlindgren** [usnistgov/ACVP-Server#368]
Relevant files: https://github.com/usnistgov/ACVP-Server/blob/master/gen-val/json-files/ML-DSA-sigGen-FIPS204/internalProjection.json https://github.com/usnistgov/ACVP-Server/blob/master/gen-val/json-files/ML-DSA-sigVer-FIPS204/internalProjection.json

FIPS 204 (ML-DSA) test vectors only provide M’, which is the concatenation of `(modeId || len(ctx) || ctx || OID? || input)`. This is the input to the internal sign/verify functions. But because the individual components are not provided, these test vectors don’t allow implementers to verify that they’ve correctly implemented the higher-level APIs (that is, Sign/Verify as opposed to Sign_internal/Verify_internal).

Additionally, the provided M' examples do not correspond to the format specified in FIPS 204. The first byte of M' should always be a 0 or a 1, but that is not the case in the given test vectors. While there is nothing mathematically preventing M' from being an arbitrary byte vector, requiring that to be supported constrains the internal implementation in a way that reduces efficiency. Specifically, if the internal implementation takes each input in a separate buffer, the inputs can be appended to the SHAKE state without allocating a new (potentially large) buffer and copying memory to it. Taking M' itself as an input typically requires such copying, because the context, message and OID (where applicable) are unlikely to already be in a contiguous buffer.

Finally, without the individual inputs, the correctness of the higher-level Sign/Verify functions cannot be validated.

This issue has also been raised on the PQC forums, e.g. [Unofficial MLDSA KAT vectors](https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/63upUY9hYPI/m/mbO20q2eAQAJ)

Request: please provide official test vectors for ML-DSA which provide each of the high-level Sign/Verify inputs individually.

**Comment by livebe01** [comment]
Hi @mlindgren,

Work is underway to provide sample test vectors and testing for the external functions. See https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/vybKwrXx53k.

The invalid 𝑀 ′ may be intentional? I.e., to test how an implementation of ML-DSA signature verification handles an invalid 𝑀 ′. But it seems that the majority of the messages are invalid. I'll check into that.

-Ben

**Comment by livebe01** [comment]
Okay, the answer is that we made no attempt to make the message values provided in https://github.com/usnistgov/ACVP-Server/blob/master/gen-val/json-files/ML-DSA-sigVer-FIPS204/prompt.json valid outputs from the perspectives of Algorithms 3 and 5.  We did make the messages valid 𝑀 ′ inputs for Algorithm 8 in that, for Algorithm 8, 𝑀 ′ is defined to be `𝑀 ′ ∈ {0, 1}∗`.

**Comment by livebe01** [comment]
I'll close this issue, but let me know if you questions.

-Ben
