### ISSUE TITLE
Demo server: Error doing GET on vector set

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP-Server#369]
**environment**
Demo

**testSessionId**
555726

**vsId**
2650478

**Algorithm registration**
The pertinent algorithm registration pieces (algorithm tested, capabilities, etc) in json format

**Endpoint in which the error is experienced**
/acvp/v1/testSessions/555726/vectorSets/2650478 GET

**Expected behavior**
Return vector set JSON

Instead, returned:
```
[{"acvVersion": "1.0"}, {"error": "Failed to generate. Object reference not set to an instance of an object."}]
```

We have not seen any other instances of this happening that I am aware of, so it could just be a random cosmic radiation bit flip 😄 but wanted to report it anyway. If we see it again I will update here.

Thanks,
Andrew

**Comment by livebe01** [comment]
A random blip, I think. I re-queued the generation for vsId 2650478 and it's ready for you know.

-Ben
