### ISSUE TITLE
Vector sets not yet ready

### ISSUE THREAD

**Issue by sgss1981** [usnistgov/ACVP-Server#370]
**environment**
The environment the issue was experienced (Demo or Prod) 
Demo

**testSessionId**
The test session ID
/acvp/v1/testSessions/558257

**vsId**
The vectorSet ID displaying the issue

Didn't get any VectorSet. The Cisco ACVP client program login successfully but fails to get any Vector set.
Console output bwlow 

[ACVP]: Beginning to download and process vector sets...
[ACVP]: Vector sets not yet ready, server requesting we wait 30 seconds and try again...
[ACVP]: Vector sets not yet ready, server requesting we wait 30 seconds and try again...
[ACVP]: Vector sets not yet ready, server requesting we wait 30 seconds and try again...
[ACVP]: Vector sets not yet ready, server requesting we wait 30 seconds and try again...
[ACVP]: Vector sets not yet ready, server requesting we wait 30 seconds and try again...
[ACVP]: Vector sets not yet ready, server requesting we wait 30 seconds and try again...
[ACVP]: Vector sets not yet ready, server requesting we wait 30 seconds and try again...
[ACVP]: Vector sets not yet ready, server requesting we wait 30 seconds and try again...
[ACVP]: Vector sets not yet ready, server requesting we wait 30 seconds and try again...
[ACVP]: Vector sets not yet ready, server requesting we wait 30 seconds and try again...

**Algorithm registration**
The pertinent algorithm registration pieces (algorithm tested, capabilities, etc) in json format
N/A

**Endpoint in which the error is experienced**
https://[acvpUrl]/acvp/[endpoint] GET
N/A

**Expected behavior**
Vector set should be downloaded but it's not

**Additional context**
None

**Comment by jarnold01** [comment]
In case you didn't already know, I'll also add that the health endpoint is useful in this situation to get an understanding of the current load/processing times in the environment: https://demo.acvts.nist.gov/health
