### ISSUE TITLE
Unclear error/reason for a vector set's state "A task was canceled."

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP-Server#374]
**environment**
DEMO

**testSessionId**
562007

**vsId**
2687522, 2687528

**Algorithm registration**
N/A

**Endpoint in which the error is experienced**
POST /testSessions/{testSessionId}/vectorSets/{vectorSetId}/results

**Expected behaviour**
The vector set in this test session is in a strange state.  Reading the status of the vector set lists it as follows: 
```json
[
    {
        "acvVersion": "1.0"
    },
    {
        "error": "A task was canceled."
    }
]
```
But it is unclear what that means or why it is in that state

When trying to upload response (which match the expected responses exactly), the response is from the API is as follows:
```json
[
    {
        "acvVersion": "1.0"
    },
    {
        "error": "Internal service error. Contact service provider."
    }
]
```

**Additional context**

**Comment by livebe01** [comment]
Hi @AlexThurston, that is a stragne error. I think you may have inadvertently submitted a version of the prompt in place of the expected results. 

For example, this is what we have on record as being submitted for tcId: 1

```json 
{"message":"21A398F48C5ACF295D9412EBA710A4AC9A4E7C08DF8F0B554103B317A3EF1CCA2679990C5CA1BF88CE5684FEF0ECAB46525ED34C4BF9F0BAB0F5954BE29E7FE2","signature":"2D03CEC9751507627038DFF29E9B838CCE5569ED4E4F0B525EFC495F9CE840758B4058E7D6D2F006731391C9EE784C71AAFBACA1DC7859302BBF2C53E8A0E5598449E339DFCCC76CADA589E1D7D97E3B64F093C052028EB0173C158A941C3B5E5C5688A0603214D0AB9BB4F3BB0E3891779C45EC150005D4331EE1496C1E411F","tcId":1}
```

versus what is expected

```json
{
          "tcId": 1,
          "testPassed": false
}
```

-Ben

**Comment by AlexThurston** [comment]
Hey @livebe01,

Interesting, it's entirely possible that the first time a submissions was made, it was done in error with the prompt instead of the response.  

However, shouldn't I still be able to submit responses again given it's a demo test session?

--
Alex

**Comment by livebe01** [comment]
That's true. There was an issue on our end which should now be fixed. Can you re-submitting the results again?

**Comment by livebe01** [comment]
Hi @AlexThurston, can you let us know if we've resolved the issue you reported?

Thank you!

**Comment by AlexThurston** [comment]
All good now. Thanks for the help.
