### ISSUE TITLE
ML-DSA-SigGen and SigVer vectors do not include domain separation

### ISSUE THREAD

**Issue by davidi67** [usnistgov/ACVP-Server#375]
I can reproduce both the ML-DSA-SigGen and ML-DSA-sigVer test vectors but only if the domain separation is omitted (line 10, Algoithm 2 of FIPS.204). 

Should be passed to ML-DSA.Sign_internal
M' = 0x00 || 0x00 || M

But to reproduce the test vectors (committed Aug 16) just the plain message M is passed.

**Comment by livebe01** [comment]
Hi @davidi67,

This is as expected. The ML-DSA test vectors presently target testing the internal interfaces, i.e., Algorithms 6 - 8 of FIPS 204. After the testing for the internal interfaces became available, we received requests to add testing for the external interfaces as well. We should have test vectors that include tests for the external algorithms available [here](https://github.com/usnistgov/ACVP-Server/tree/master/gen-val/json-files) by the end of the year. You can find some preliminary test vectors [here](https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/bV_tuibsCWU).

Best,

Ben
