### ISSUE TITLE
Cannot List Resources (Vendor, Module, etc...)

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP-Server#38]
**environment**
Demo (Prod is working OK)

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
N/A

**Endpoint in which the error is experienced**
`GET https://demo.acvts.nist.gov/acvp/v1/vendors?limit=20&offset=0`

```
 [
    {
        "acvVersion": "1.0"
    },
    {
        "error": "Internal service error. Contact service provider."
    }
]
```

**Expected behaviour**
I should be able to list resources

**Additional context**
This seems to be a consistently reoccurring issue subsequent to backend updates.

**Comment by Kritner** [comment]
Thanks, taking a look

**Comment by Kritner** [comment]
Should be fixed

**Comment by AlexThurston** [comment]
Can confirm.  All good now.  Thanks.
