### ISSUE TITLE
Download Sample Expected results output

### ISSUE THREAD

**Issue by asant57** [usnistgov/ACVP-Server#39]
When attempting to download sample vectors for a algorithm set that has now completed vector download the server returns an internal server error of "Internal service error. contact service provider". however, i believe that this should be the retry vector set that is returned for the test vectors when they are not yet ready.

Returned:
[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Internal service error. Contact service provider."
  }
]

Expected/Proposed:
[
  {
    "acvVersion": "1.0"
  },
  {
    "retry": 30
  }
]

**Comment by Kritner** [comment]
a retry 30 *is* returned under normal circumstances when something is not yet processed.  it sounds like you've run into something else.  

Additional information such as the vector set ID, endpoint you're experiencing the error, etc would be helpful.

**Comment by asant57** [comment]
Server: demo.acvts.nist.gov
Test Session: 127071, 127202
Vector Set ID: 382032, 382825

the test vector set is returning the expected retry response, this is only occurring on the expected results download attempts.

**Comment by Kritner** [comment]
Just to confirm - you're attempting to download the expected answers, prior to successfully retrieving the prompt file?
That is probably something that's not accounted for in the workflow so just wanted to double check I'm understanding the problem.

**Comment by asant57** [comment]
Correct. i am attempting to download the expected results prior to the server sending the requested vectors.

**Comment by livebe01** [comment]
The fix for this is on Demo in https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.23

**Comment by livebe01** [comment]
This change is on prod in release [v1.1.0.23](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.23).
