### ISSUE TITLE
Generation of Vector Sets for RSA via FIPS186-4 taking several days on Demo

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP-Server#4]
**environment**
Demo

**testSessionId**
105365

**vsId**
316459

**Algorithm registration**
[{"acvVersion":"1.0"},{"algorithms":[{"algorithm":"RSA","revision":"FIPS186-4","mode":"sigGen","prereqVals":[{"algorithm":"SHA","valValue":"same"},{"algorithm":"DRBG","valValue":"same"}],"capabilities":[{"sigType":"ansx9.31","properties":[{"modulo":2048,"hashPair":[{"hashAlg":"SHA2-256"},{"hashAlg":"SHA2-384"},{"hashAlg":"SHA2-512"}]},{"modulo":3072,"hashPair":[{"hashAlg":"SHA2-256"},{"hashAlg":"SHA2-384"},{"hashAlg":"SHA2-512"}]}]},{"sigType":"pkcs1v1.5","properties":[{"modulo":2048,"hashPair":[{"hashAlg":"SHA2-224"},{"hashAlg":"SHA2-256"},{"hashAlg":"SHA2-384"},{"hashAlg":"SHA2-512"}]},{"modulo":3072,"hashPair":[{"hashAlg":"SHA2-224"},{"hashAlg":"SHA2-256"},{"hashAlg":"SHA2-384"},{"hashAlg":"SHA2-512"}]}]},{"sigType":"pss","properties":[{"modulo":2048,"hashPair":[{"hashAlg":"SHA2-224","saltLen":0},{"hashAlg":"SHA2-256","saltLen":0},{"hashAlg":"SHA2-384","saltLen":0},{"hashAlg":"SHA2-512","saltLen":0}]},{"modulo":3072,"hashPair":[{"hashAlg":"SHA2-224","saltLen":0},{"hashAlg":"SHA2-256","saltLen":0},{"hashAlg":"SHA2-384","saltLen":0},{"hashAlg":"SHA2-512","saltLen":0}]}]}]},{"algorithm":"RSA","revision":"FIPS186-4","mode":"sigVer","prereqVals":[{"algorithm":"SHA","valValue":"same"},{"algorithm":"DRBG","valValue":"same"}],"pubExpMode":"fixed","fixedPubExp":"010001","capabilities":[{"sigType":"ansx9.31","properties":[{"modulo":2048,"hashPair":[{"hashAlg":"SHA-1"},{"hashAlg":"SHA2-256"},{"hashAlg":"SHA2-384"},{"hashAlg":"SHA2-512"}]},{"modulo":3072,"hashPair":[{"hashAlg":"SHA-1"},{"hashAlg":"SHA2-256"},{"hashAlg":"SHA2-384"},{"hashAlg":"SHA2-512"}]}]},{"sigType":"pkcs1v1.5","properties":[{"modulo":2048,"hashPair":[{"hashAlg":"SHA-1"},{"hashAlg":"SHA2-224"},{"hashAlg":"SHA2-256"},{"hashAlg":"SHA2-384"},{"hashAlg":"SHA2-512"}]},{"modulo":3072,"hashPair":[{"hashAlg":"SHA-1"},{"hashAlg":"SHA2-224"},{"hashAlg":"SHA2-256"},{"hashAlg":"SHA2-384"},{"hashAlg":"SHA2-512"}]}]},{"sigType":"pss","properties":[{"modulo":2048,"hashPair":[{"hashAlg":"SHA-1","saltLen":0},{"hashAlg...[truncated]

**Endpoint in which the error is experienced**
/acvp/v1/testSessions/105365/vectorSets/316459 GET

**Expected behavior**
The test session was created on Friday afternoon - still getting "retry in 30 seconds" message.

**Additional context**
attempted to create a new session in case the aforementioned one was dropped from the queue; that has also been waiting a while now.

Thanks for your time! I am just creating this issue in case it is a result of some problem caused by the recent changes, not complaining about a large queue backlog if thats the reason.

Andrew

**Comment by Kritner** [comment]
Thanks @abkarcher I see the issue, once we can get a new build out to demo it should be resolved.  I'll update this when the change goes out.

**Comment by Kritner** [comment]
Once the change *does* go out you can either re-submit the test session or if you want us to save that particular one let me know, it's currently in a bad state and wouldn't automatically "be fixed" by the new deployment when it goes out.

**Comment by locksmithone** [comment]
Concur. I have one instance of RSA that has been stuck on the demo server
since Friday.

**Comment by Kritner** [comment]
@abkarcher, @locksmithone, @RoyHSYoo, @smueller this should be fixed on demo now. 

The original vector sets are currently in a bad state, so you can either create a new session, or reply back with the IDs that need their state corrected, and I'll work on getting them processed.
