### ISSUE TITLE
Need guidance on KMAC in OneStep KDF.

### ISSUE THREAD

**Issue by dghgit** [usnistgov/ACVP-Server#43]
In table 3 of SP800-56C Rev 2 states "Choice of 160, 224, 256, 384, 512, or L." for H_outputBits and recommends the use of L (which is the length of the key material requested) for efficiency reasons on Page 14.

Given the following:

```json
"kdfConfiguration": {
  "kdfType": "oneStep",
  "l": 1024,
  "saltMethod": "default",
  "fixedInfoPattern": "algorithmId||uPartyInfo||vPartyInfo",
  "fixedInfoEncoding": "concatenation",
  "auxFunction": "KMAC-128"
}
```

and the vector:

```json
{
  "tcId": 1,
  "kdfParameter": {
    "kdfType": "oneStep",
    "salt": "00000000000000000000000000000000",
    "z": "39CB5C7486EEB4CFA379EC16CC23C8D9E0C3FCC941B92B6C8F1658F5929BB48D",
    "l": 1024,
    "algorithmId": "C90F0C695C8372FCB94F0BAF9A86AC67"
  },
  "fixedInfoPartyU": {
    "partyId": "00F00E52832EF7960EBD7A46E2E7F574",
    "ephemeralData": "C4C150F5BD1F35140B5F9AE014D3CD7F600F1B8F6940C3F83AA0B343E8A082A2"
  },
  "fixedInfoPartyV": {
    "partyId": "DB06A47DB74EA7474231502AD9D1D7EE"
  }
},
```

This gives a fixedInfo of
```
c90f0c695c8372fcb94f0baf9a86ac6700f00e52832ef7960ebd7a46e2e7f574c4c150f5bd1f35140b5f9ae014d3cd7f600f1b8f6940c3f83aa0b343e8a082a2db06a47db74ea7474231502ad9d1d7ee
```

and `KMAC128("00000000000000000000000000000000", C || "39CB5C7486EEB4CFA379EC16CC23C8D9E0C3FCC941B92B6C8F1658F5929BB48D" || fixedInfo, 1024, "KDF")`

where C is a 4 byte big endian encoding of the block number (in this case 1)

gives: 

```
80a3dd756f342e8f29dfbb4c9d05f19d1f8ac29246bda54627fc7b064359ff62c3566f148fead0f2053d9637e6ce334b3067e66068da811a2f6197c615c9c13f2c3bb7da0392481fc06c96d81e9a6e38d9d1228e3fd9e88e4891f4bbb1dc59adb3fb2b2af956219b3201c8f7b658089529e36929c568c014d1cc9719991e9861
```

The sample response for the vector is:

```
D6572FACBFC553F16FD7B7D58F95E3E4A24D6C336BF7F9E7171914B7194AAC45C044FA5F754D1F4850AB1BBDA04AAACEED115647C5F9FE6A40A10FD4654E9E6ACBE9C6DB3548DAA376E9E5C1AE30B881A1BE42933D7D3FD6664B9E2F5EEA234870952D2E0608D89269791D6B4E925D5B6B5B60894B1B968CA173080984B225CD
```

What is H_outputBits set to in the server? I tried the other values listed in table 3 and nothing seemed to work. Intuitively I'm attracted to the idea of using L as it's possible to do so, but I'm also concerned that none of the listed options produce the same result as the sample response. I'm wondering if there is some other consideration with KMAC that I have managed to miss (for example KMAC has an indefinite length option for generating output, is that happening somewhere?). Thanks.

**Comment by Kritner** [comment]
When using KMAC we make an assumption that the KMAC output length would be at the output length of the registered `l` value.  Like you said it is *technically* configurable, but for the sake of making the registration simpler without having that additional registration value, I opted for going that route; especially since KAS already has so many registration options.

As far as where we are differing on the values, let me get back to you on that; I need to wrap up some other things then I'll take a look.

**Comment by dghgit** [comment]
Yes, KAS is a "beast". More options than Cthulhu has tentacles... I'd certainly support L as the default - I can imagine some people having to overlay a previous PRF with KMAC so having to chunk it due to restrictions on what they can change, but for anyone doing it from scratch, like us, it's difficult to imagine them choosing to do so.

**Comment by Kritner** [comment]
@dghgit I found an issue in our implementation, we have a hotfix on its way out so I'll get this put in at that time as well.  After fixing the problem we agree on the answer.

**Comment by Kritner** [comment]
This change is on demo and prod in release [v1.1.0.14-1](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.14-1)
