### ISSUE TITLE
TOTP authentication failures

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP-Server#44]
**environment**
Demo

**testSessionId**
various - the one discussed below is 129266

Today I had to request a large amount of test daa.

Quite often I get the following error:
```
ACVPProxy (14:59:31) (acvp-proxy) Error: Process following server response for HTTP return code 403: [
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Access denied! Reason: TOTP failed to verify"
  }
]
```

When invoking the request some time later, it works again. My time is exact and taken from NTP.

See the time stamp in the log message if you want to search your log message.

**Comment by smuellerDD** [comment]
It seems when I have an ongoing session with the server and a second login happens for a separate session (at least 30 seconds later than the first session), I seem to get these TOTP failures reproducibly.

**Comment by celic** [comment]
The server will distinguish between TOTP re-use and a failure to verify, so this error happens because the server determined the TOTP received was not correct.

**Comment by smuellerDD** [comment]
Strange, but why is it not correct? My time is correct. Hm.

**Comment by celic** [comment]
We would need the specific timestamp and the value you computed. I wouldn't expect those to be saved. You can email me directly, or use nfiles with values if you have them. Otherwise there's not much we can do to look at the provided and expected values.

**Comment by mplascencia** [comment]
@celic I am seeing this same "TOTP failed to verify" error quite frequently on the "prod" and "demo" ACVTS servers.  I haven't encountered this error until recently (about the date this issue was posted) and we haven't changed any of our TOTP code in many months.  My local time is in sync with the NIST NTP servers.   Should I email you some debugging information directly?

@smuellerDD Are you still getting these errors?

**Comment by celic** [comment]
Yes please do.

Chris

**Comment by smuellerDD** [comment]
I get these errors frequently. Chris and I have debugged that a bit and we indicated that the ACVP server seems to sometimes have a time warp.

Ciao
Stephan

—
Cui bono?

**Comment by celic** [comment]
We are looking into short-term solutions while we try to find out what is causing the incorrect TOTP values. These won't get deployed until Monday at the earliest though.

**Comment by mplascencia** [comment]
@celic and @smuellerDD Thank you for the update and looking into this issue.

**Comment by smuellerDD** [comment]
Just to let you know: I am now unable to log into the Prod server for about 2 hours due to this issue: between 2 and 4pm MET.

**Comment by smuellerDD** [comment]
A TOTP authentication error occurred for me at 7:19:30 MET.

**Comment by celic** [comment]
On prod or demo?

**Comment by smuellerDD** [comment]
Am Mittwoch, dem 16.12.2020 um 22:23 -0800 schrieb Chris Celi:
> On prod or demo?

Demo.
>

**Comment by smuellerDD** [comment]
I still see the issue on prod as well: authentication on Sat, Dec 19, 09:59:59 MET.

**Comment by jarnold01** [comment]
Hi @smuellerDD - During the last couple of weeks, I was able to confirm (and get fixed) a time sync-related issue on our end (an upstream configuration issue). Please let us know if you continue to receive TOTP auth errors going foward; thanks.

**Comment by smuellerDD** [comment]
Am Montag, dem 04.01.2021 um 11:36 -0800 schrieb Jason Arnold:
> Hi @smuellerDD - During the last couple of weeks, I was able to confirm (and
> get fixed) a time sync-related issue on our end (an upstream configuration
> issue). Please let us know if you continue to receive TOTP auth errors going
> foward; thanks.
> 

Just today I received a string of these TOTP errors - it was around 10 or 11
am EST. But during that time I there seemingly were connection issues in your
environments as I got some timeouts.

Before and after that I have not seen TOTP errors since Christmas.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Montag, dem 04.01.2021 um 20:54 +0100 schrieb Stephan Mueller:
> Am Montag, dem 04.01.2021 um 11:36 -0800 schrieb Jason Arnold:
> > Hi @smuellerDD - During the last couple of weeks, I was able to confirm
> > (and
> > get fixed) a time sync-related issue on our end (an upstream configuration
> > issue). Please let us know if you continue to receive TOTP auth errors
> > going
> > foward; thanks.
> > 
> 
> Just today I received a string of these TOTP errors - it was around 10 or 11
> am EST. But during that time I there seemingly were connection issues in
> your
> environments as I got some timeouts.
> 
> Before and after that I have not seen TOTP errors since Christmas.

Just this morning, I received another TOTP error. But it smells like it is not
related to the TOTP step size / time stamp, but rather some form of timeout.
Here is the log, watch the time stamps:

```
ACVPProxy (07:15:39) (acvp-proxy) Status: Logging into ACVP server
ACVPProxy (07:18:14) (acvp-proxy) Error: Process following server response for
HTTP return code 403: [
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Access denied! Reason: TOTP failed to verify"
  }
]
```

I am waiting 2 1/2 minutes before the server responds. A subsequent attempt
about 5 minutes later fails the same way, but the lag time is about 1/2
minute.

Ciao
Stephan

> 
> Ciao
> Stephan

**Comment by jarnold01** [comment]
Okay thanks for the feedback @smuellerDD - looking into it. The timestamp included in your output is your local time, correct?

**Comment by smuellerDD** [comment]
Am Mittwoch, dem 06.01.2021 um 08:11 -0800 schrieb Jason Arnold:
> Okay thanks for the feedback @smuellerDD - looking into it. The timestamp
> included in your output is your local time, correct?
> 

Ah, yes: MET - European time.

**Comment by AlexThurston** [comment]
I'll throw my observations into the ring here and mention that I am also seeing flaky behaviour when it comes to authentication.  I'm often getting the same response as @smuellerDD is observing as well as an occasional situation where HTTP headers are no delivered within my client's timeout (30 seconds).

**Comment by jarnold01** [comment]
Thanks @AlexThurston , appreciate that feedback. We're digging into it further and doing more internal testing to aid in our troubleshooting and investigation. Stay tuned.

**Comment by jarnold01** [comment]
I just applied a change to both Demo and Prod that should address the TOTP-related authentication errors that we have been able to duplicate and test successfully internally. I'm going to close this issue, but please feel free to re-open it if you continue to notice TOTP-related authentication issues.

**Comment by AlexThurston** [comment]
I don't know if it's related to this change, but I just raised this: https://github.com/usnistgov/ACVP-Server/issues/61

**Comment by smuellerDD** [comment]
I still see these issues: Just this morning around 07:34 MET.

**Comment by jarnold01** [comment]
On Demo or Prod?

**Comment by smuellerDD** [comment]
Am Freitag, dem 08.01.2021 um 04:57 -0800 schrieb Jason Arnold:
> On Demo or Prod?
> 

Prod.

**Comment by smuellerDD** [comment]
Just another observation which may relate to the TOTP timing issue. This morning I am in the process of publishing data to the prod server. In the middle, the server slowed down significantly for a simple GET operation to obtain the certificate. See the time stamps of the logs which indicate one GET per line:

```
ACVPProxy (08:29:55) (acvp-proxy) Status: Test session certificate ID 33545 successfully obtained
ACVPProxy (08:30:00) (acvp-proxy) Status: Test session certificate ID 33544 successfully obtained
ACVPProxy (08:30:38) (acvp-proxy) Status: Test session certificate ID 33543 successfully obtained
ACVPProxy (08:30:55) (acvp-proxy) Status: Test session certificate ID 33542 successfully obtained
```

Before and after it went much faster again. This smells like the same waiting time we observe during login when the authentication sometimes takes a long time.
