### ISSUE TITLE
Test vector generation errors

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP-Server#45]
**environment**
Prod

**testSessionId**
3381

**vsId**
32404

The server failed to generate the vector:

```
[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Failed to generate. Object reference not set to an instance of an object."
  }
]
```

How can I retrieve the test vector without discarding the entire test session?

**Comment by Kritner** [comment]
Hey @smuellerDD I'm not sure what happened here, when I attempted to run the job again it went through fine.

I'll try to find out why it didn't work the first time, but the vector set should be available to you now.

**Comment by smuellerDD** [comment]
Got it, thanks.

Close it at your discretion.
