### ISSUE TITLE
ACVP Server sending non-JSON data?

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP-Server#47]
I currently see a very odd issue I have never encountered before. I am not sure where the error is, so allow me to mention it to see whether or not it is a server issue.

Currently I have a very slow Internet uplink. I yet get to the server to download some 40 HMAC/SHA vectors in parallel. The individual bit stream maybe is 1kb/s, so very slow.

For 5 out of the 40 vectors initially my client received non-JSON data during downloading the test vectors. Unfortunately I was not able to retain the data. After retrying to fetch the test vectors again, I got the right data.

Server: PROD

vsIDs: 35786, 35805, 38506, 35800, 35771

The time that all that happened was between 16:30:19 and 16:31:13 MET.

**Comment by smuellerDD** [comment]
I just got many more of those issues for another separate download. in the time between 16:35:20 and 16:40:20. My log:

ACVPProxy (16:35:20) (vid35829) Error: JSON tokener cannot parse ASCII data
ACVPProxy (16:36:00) (vid35835) Error: JSON tokener cannot parse ASCII data
ACVPProxy (16:37:01) (vid35831) Error: JSON tokener cannot parse ASCII data
ACVPProxy (16:37:27) (vid35840) Error: JSON tokener cannot parse ASCII data
ACVPProxy (16:37:37) (vid35823) Error: JSON tokener cannot parse ASCII data
ACVPProxy (16:37:46) (vid35846) Error: JSON tokener cannot parse ASCII data
ACVPProxy (16:38:03) (vid35865) Error: JSON tokener cannot parse ASCII data
ACVPProxy (16:38:07) (vid35864) Error: JSON tokener cannot parse ASCII data
ACVPProxy (16:38:08) (vid35863) Error: JSON tokener cannot parse ASCII data
ACVPProxy (16:39:03) (vid35843) Error: JSON tokener cannot parse ASCII data
ACVPProxy (16:39:06) (vid35817) Error: JSON tokener cannot parse ASCII data
ACVPProxy (16:39:20) (vid35809) Error: JSON tokener cannot parse ASCII data
ACVPProxy (16:39:29) (vid35837) Error: JSON tokener cannot parse ASCII data
ACVPProxy (16:39:29) (vid35870) Error: JSON tokener cannot parse ASCII data
ACVPProxy (16:39:51) (vid35826) Error: JSON tokener cannot parse ASCII data
ACVPProxy (16:39:55) (vid35834) Error: JSON tokener cannot parse ASCII data
ACVPProxy (16:40:01) (vid35869) Error: JSON tokener cannot parse ASCII data
ACVPProxy (16:40:15) (vid35832) Error: JSON tokener cannot parse ASCII data
ACVPProxy (16:40:20) (vid35836) Error: JSON tokener cannot parse ASCII data
ACVPProxy (16:40:20) (vid35861) Error: JSON tokener cannot parse ASCII data

**Comment by celic** [comment]
We do notice the response time is exceedingly large for some of these vector sets. Our response times should factor in the data transfer rate, and some of these connections were open for many minutes. The server reports successful HTTP codes but those are decided before the transfer begins. With that in mind it is hard to say if the server struggled with the slow connection or the client did.

**Comment by Kritner** [comment]
I think since this hasn't seemingly cropped up since the issue was opened, we can consider it a transient issue. Closing.
