### ISSUE TITLE
Clairification of what goes in this repo versus the other

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP-Server#5]
I just want to clarify what types of issue continue to be raised in the other repository (https://github.com/usnistgov/ACVP).

In the README for this one, it says that issues can be raised here that are about :

> Noticed differences from the protocol specifications

But it also says further down:

> Questions or problems with the specifications, can be raised with issues on the protocol repository

**Comment by Kritner** [comment]
The general idea is that issues related to the actual specification/protocol should go on the https://github.com/usnistgov/ACVP repo, where issues with ***our implementation of the specification/protocol*** should go on this repo https://github.com/usnistgov/ACVP-Server.  It's not necessarily always going to be clear where the issue *should* be opened, but that's the basic idea of it.

FWIW I would imagine most issues would start being opened on this repository, or transfered to it, as the protocol specification is *mostly* stable for the moment.

If they are opened on "the incorrect repository" it's no problem, we can always transfer the issue or leave it where it is.  We mostly wanted to do this to start have some separation between the actual protocol specification, and the NIST implementation of that protocol specification.

**Comment by AlexThurston** [comment]
Perfect.  Thanks for the insight and explanation @Kritner
