### ISSUE TITLE
AES-CTR plaintext value too large

### ISSUE THREAD

**Issue by mniforatos** [usnistgov/ACVP-Server#50]
**Environment**
Both Production and Demo

**testSessionId** (with vsID in parenthesis)
**Prod**: 3722 (vsID: 36462), 3724 (vsID: 36464), 3725 (vsID: 36465), 3726 (vsID: 36466), 3728 (vsID: 36490), 3729 (vsID: 36491)
**Demo**: 131104 (vsID: 404133), 131105 (vsID: 404134), 131106 (vsID: 404135),  131107 (vsID: 404136), 131115 (vsID: 404167), 131120 (vsID: 404176)

**Algorithm registration**
```
[
   {
      "acvVersion":"1.0"
   },
   {
      "algorithms":[
         {
            "algorithm":"ACVP-AES-CTR",
            "revision":"1.0",
            "direction":[
               "encrypt"
            ],
            "incrementalCounter":false,
            "overflowCounter":false,
            "keyLen":[
               128,
               192,
               256
            ],
            "payloadLen":[
               128
            ]
         }
      ]
   }
]
```

Vector sets 3722 and 131104 have both incrementalCounter and overflowCounter set to false.
Sets 3724 and 131105 have both incrementalCounter and overflowCounter set to true.
Sets 3725 and 131106 have incrementalCounter set to true and overflowCounter set to false.
Sets 3726 and 131107 have incrementalCounter set to false and overflowCounter set to true.

**Endpoint in which the error is experienced**
https://acvts.nist.gov/acvp/v1/testSessions
https://demo.acvts.nist.gov/acvp/v1/testSessions

**Expected behavior**
With payloadLen set to 128, I expect the 'pt' length to be at max 128 bits. However, tcId's 31-33 or 31-36 (depending on which options are selected for incrementalCounter and overflowCounter) have a 'pt' length of 32,000 hex characters, far surpassing 128 bits. This is the case for both demo and production servers, with each of the above combinations of incrementalCounter and overflowCounter set. See the first four testSessionId's listed above for both Demo and Prod servers.

**Additional context**
Setting 'performCounterTests' to true didn't change the above as this value defaults to true if not included. The problem doesn't exist when 'performCounterTests' is set to false (see Prod. vsID 36490 and Demo vsID 404167), but that's not what I need for my vendor.

Also, setting 'isSample' to true on the demo server when incrementalCounter was set to true and overflowCounter set to false produced only 3,200 hex characters instead of 32,000. See vsID: 404176.

**Comment by Kritner** [comment]
Perhaps @celic can speak more to this, but the `payloadLen` in this algorithms case has valid values of 1-128 bits, 128 bits being a "required" payload length.   128 bits is only a single block against AES, so does not effectively test against the counter mode implementation.   

The testing against AES-CTR has varying different types of "test groups", one of which increases the payload size significantly past a single AES block of 128 bits, though since AES-CTR is a stream cipher, I would think an IUT would be able to support payloads of any size as long as they meet the block size; it's really just if *partial* blocks are supported that the payload length is used for from the registration.

**Comment by celic** [comment]
`PayloadLen` here refers to the stream cipher aspect of AES-CTR and only affects the partial block testing groups. The assumption is made that an IUT should be able to handle any number of complete blocks. If the harness needs to help with this, then it should. @Kritner has it right.

**Comment by mniforatos** [comment]
Thank you @Kritner and @celic for your quick responses and for the clarification! Does this mean that 32,000 hex characters is the expected length for those 'pt' values? If so, why is there a difference between the sample vectors, which only contain 3,200 hex characters, and the regular vectors? My assumption is because the sample vectors are just that, sample vectors, and the length is shortened for ease and speed, but confirmation would be appreciated.

**Comment by celic** [comment]
Correct. Sample vectors are usually shorter (less test cases). In this case
the plaintext is also shorter. No real rhyme or reason than to make it
faster, but more blocks of AES is still near instantaneous.

**Comment by mniforatos** [comment]
Thanks again for the clarification @celic!
