### ISSUE TITLE
AES FF1 Missing from Specification

### ISSUE THREAD

**Issue by powersmc** [usnistgov/ACVP-Server#51]
**environment**
N/A

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
N/A

**Endpoint in which the error is experienced**
**Programmatic Transitions**: https://csrc.nist.gov/Projects/cryptographic-module-validation-program/programmatic-transitions
**ACVP Page**: https://usnistgov.github.io/ACVP/
**Symmetric Algorithms Page**: https://usnistgov.github.io/ACVP/draft-celi-acvp-symmetric.html

**Expected behavior**
Based on the Programmatic Transitions link, AES FF1 should be implemented on both the demo and production servers.  Using the ACVP Page above, if you follow the link for AES-FF1 it leads you to the Symmetric Block Cipher Algorithms JSON specification page.  This page does not appear to contain any information regarding the "FF1" mode of AES and what options are supported for this mode.

**Additional context**
I have a vendor that's looking to test AES-FF1, but the JSON specification doesn't seem to indicate the supported options for this mode.

**Comment by Kritner** [comment]
Looks like this specification was written in the same time frame of our moving to a new method of writing our specification documents.  I'll try (or anyone else is welcome to) get the documents into our adoc files.

The original PR for AES-FF1 and AES-FF3-1 is here: https://github.com/usnistgov/ACVP/pull/669

I'll try to get to this at some point this week.

**Comment by Kritner** [comment]
I restored this PR's original branch here https://github.com/Kritner/ACVP/tree/FEATURE/SP800-38Gr1  if you'd like to take a look at the generated artifacts until I have a chance to work it into the current version of the specification.
