### ISSUE TITLE
ECDSA vector set issue

### ISSUE THREAD

**Issue by Kritner** [usnistgov/ACVP-Server#52]
Thanks, @Kritner. And our lab user found another two vector sets with the same error when testing with DCDSA. Not sure if they are having the same issue. If not I may need to open up another issue.

> /acvp/v1/testSessions/129146/vectorSets/393177

> /acvp/v1/testSessions/129146/vectorSets/393180

_Originally posted by @AndrewHYang in https://github.com/usnistgov/ACVP-Server/issues/46#issuecomment-741495803_

**Comment by Kritner** [comment]
The data in both of the vector sets response files is malformed:

```json
{
"tcId": 1,
"testPassed = ": "true"
},
```

the above example of bad responses exists in both vector set files.

**Comment by AndrewHYang** [comment]
For the ECDSA, our lab users got the formatting issues resolved. However, they got the error below again from HMAC. Since the previous was closed, I attach here anyway. Is it due to the same issue?

> "error": "A task was canceled."

Example:
Demo server
Test session: /acvp/v1/testSessions/131631
Vector set: /acvp/v1/testSessions/131631/vectorSets/406502

**Comment by Kritner** [comment]
The previous issue being: https://github.com/usnistgov/ACVP-Server/issues/46 correct? I'd prefer to update that issue since it seems related.  I'll bump that issue with the additional information from your previous comment https://github.com/usnistgov/ACVP-Server/issues/52#issuecomment-748687124

If the ECDSA issue resolved? I know it seems like we need to have better handling on when a file is malformed, but that will be a longer term fix, that is at least on our radar.

**Comment by Kritner** [comment]
I'm assuming this is all taken care of, but feel free to reopen and/or bump if not.
