### ISSUE TITLE
Not able to connect/login to nist server

### ISSUE THREAD

**Issue by yvasavi** [usnistgov/ACVP-Server#53]
**environment**
The environment the issue was experienced (Demo or Prod)
Demo

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
The pertinent algorithm registration pieces (algorithm tested, capabilities, etc) in json format
N/A

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov:443/acvp/v1/login

**Expected behavior**

Hello, 
I have just received certificate file in .cer for accessing to demo server.
I tried to login using acvp_app, but unable to get connected due to certificate issue.
can you please advice.

[admin@oak-vsh367 ~]# ./acvp_app --verbose --aes

Using the following parameters:
    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    acvp.nist.gov.crt
    ACV_CERT_FILE:  Riverbed_Ramana_Pillalamarri_Demo.cer
    ACV_KEY_FILE:   riverbed-private1.key

***ACVP [INFO][acvp_http_user_agent_handler:1515]--> HTTP User-Agent: libacvp/1.0;Linux;2.6.32;x86_64;Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz;GCC/8.3.0

***ACVP [STATUS][acvp_login:2497]--> Logging in...
***ACVP [ERR][acvp_curl_http_post:353]--> Curl failed with code 60 (SSL peer certificate or SSH remote key was not OK)

***ACVP [INFO][log_network_status:1080]--> POST Login...
	Status: 0
	Url: https://demo.acvts.nist.gov:443/acvp/v1/login
	Resp: Recieved

***ACVP [ERR][log_network_status:1105]--> Received no response from server.
***ACVP [STATUS][acvp_login:2509]--> Login Send Failed
***ACVP [ERR][acvp_run:3195]--> Failed to login with ACVP server
 
[admin@oak-vsh367 ~]# curl -v --cacert acvp.nist.gov.crt --key riverbed-private1.key --cert Riverbed_Ramana_Pillalamarri_Demo.cer -d '{{"acvVersion":"1.0"}, {"password":<>}}' -H "Content-Type: application/json" https://demo.acvts.nist.gov/acvp/v1/login
*   Trying 52.204.191.193:443...
* TCP_NODELAY set
* Connected to demo.acvts.nist.gov (52.204.191.193) port 443 (#0)
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: acvp.nist.gov.crt
  CApath: none
* TLSv1.2 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Additional context**
I have set the ACV_TOTP_SEED with the specified value

**Comment by celic** [comment]
Maybe @smueller can help out here? Is this related to #44?

**Comment by smuellerDD** [comment]
The log already seems to say what the error is: "TLS alert, unknown CA" - do you have the CA cert installed and your client pointing to it so that your client can validate the ACVP server?

**Comment by yvasavi** [comment]
I do have the CA cert installed and client is pointing to that ACV_CA_FILE=acvp.nist.gov.crt

[admin@oak-vsh367 ~]# ls 
Riverbed_Ramana_Pillalamarri_Demo.cer  acvp.nist.gov.crt  acvp_app  acvp_env  dead.letter  riverbed-private.key  riverbed-private1.key
[admin@oak-vsh367 ~]# printenv | grep ACV
ACV_URI_PREFIX=/acvp/v1/
ACV_CA_FILE=acvp.nist.gov.crt
ACV_TOTP_SEED=2zHiwcWUOAKE6Ivdw6S2jUTO6/Of8ABO/gQ+0lkVMuwF6nfHS3Kfc/wDBkm57Jb+
ACV_SERVER=demo.acvts.nist.gov
ACV_KEY_FILE=riverbed-private1.key
ACV_CERT_FILE=Riverbed_Ramana_Pillalamarri_Demo.cer
ACV_PORT=443
ACV_API_CONTEXT=acvp/
[admin@oak-vsh367 ~]# ls acvp.nist.gov.crt
acvp.nist.gov.crt
[admin@oak-vsh367 ~]# ./acvp_app --aes    

Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    acvp.nist.gov.crt
    ACV_CERT_FILE:  Riverbed_Ramana_Pillalamarri_Demo.cer
    ACV_KEY_FILE:   riverbed-private1.key

***ACVP [STATUS][acvp_login:2497]--> Logging in...
***ACVP [ERR][acvp_curl_http_post:353]--> Curl failed with code 60 (SSL peer certificate or SSH remote key was not OK)

***ACVP [ERR][log_network_status:1105]--> Received no response from server.
***ACVP [STATUS][acvp_login:2509]--> Login Send Failed
***ACVP [ERR][acvp_run:3195]--> Failed to login with ACVP server
[admin@oak-vsh367 ~]# openssl x509 -in acvp-text 
acvp.nist.gov.crt  acvp_app           acvp_env           
[admin@oak-vsh367 ~]# openssl x509 -in acvp-text 
acvp.nist.gov.crt  acvp_app           acvp_env           
[admin@oak-vsh367 ~]# openssl x509 -in acvp.nist.gov.crt -text 
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            38:58:dc:3e:4f:28:09:91:a4:2d:c7:ff:7c:54:ba:a7
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, ST=Maryland, O=National Institute of Standards and Technology, OU=ITL/CSD, CN=ACVP Servers CA
        Validity
            Not Before: Jul 26 11:27:03 2016 GMT
            Not After : Jul 25 11:27:03 2021 GMT
        Subject: C=US, ST=Maryland, O=National Institute of Standards and Technology, OU=ITL/CSD, CN=acvp.nist.gov
        Subject Public Key Info:

**Comment by smuellerDD** [comment]
Am Sonntag, dem 13.12.2020 um 07:24 -0800 schrieb yvasavi:
> I do have the CA cert installed and client is pointing to that
> ACV_CA_FILE=acvp.nist.gov.crt
> 
> [admin@oak-vsh367 ~]# ls 
> Riverbed_Ramana_Pillalamarri_Demo.cer  acvp.nist.gov.crt  acvp_app 
> acvp_env  dead.letter  riverbed-private.key  riverbed-private1.key
> [admin@oak-vsh367 ~]# printenv | grep ACV
> ACV_URI_PREFIX=/acvp/v1/
> ACV_CA_FILE=acvp.nist.gov.crt
> ACV_TOTP_SEED=2zHiwcWUOAKE6Ivdw6S2jUTO6/Of8ABO/gQ+0lkVMuwF6nfHS3Kfc/wDBkm57J
> b+
> ACV_SERVER=demo.acvts.nist.gov

You seem to access the demo server, but you seem to use the production server
CA.

Both have different CAs.

Ciao
Stephan

**Comment by yvasavi** [comment]
Hi Stephan,

Can you please point me to the right CA. I will try and get back to you. 
Also can this happen if DUT is behind web proxy ? I am not sure right now.

Thanks,
Vasavi

**Comment by yvasavi** [comment]
Changing to mozzila_trust_anchors.pem ca certificate solved the issue. Thanks for the pointers.

Thanks,
Vasavi.
