### ISSUE TITLE
KTS RSA OAEP

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP-Server#55]
After now successfully performing KTS RSA OAEP with OpenSSL, I am wondering why the test vector only contains one initiator and one responder with one modulus/hash combo each.

I have requested all moduli 2048 - 8192 and all SHA2 / 3 hashes.

testID 133142 / vsID 412475

**Comment by Kritner** [comment]
This change is on prod in release [v1.1.0.15](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.15)
