### ISSUE TITLE
Fetching vsID verdict after receipt of certificate stalled

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP-Server#57]
When fetching a vsID verdict after the certificate is awarded, the server always responds with a retry:30.

URL: `GET /acvp/v1/testSessions/3409/vectorSets/32965/results HTTP/1.1`

Environment: Prod

certificate: A919

**Comment by Kritner** [comment]
Test session set data is generally removed from the public side of things after it either expires, or is certified.  That being said, was there something you needed from the file for this particular test session, is the issue a matter of a "non infinite retry" message, or both?

**Comment by smuellerDD** [comment]
Am Mittwoch, dem 21.04.2021 um 09:11 -0700 schrieb Russ Hammett:
> Test session set data is generally removed from the public side of things
> after it either expires, or is certified.  That being said, was there
> something you needed from the file for this particular test session, is the
> issue a matter of a "non infinite retry" message, or both?
> 

Just the latter - it is an observation I wanted to share with you. If you say,
this is the intended behavior, fine. But I would rather have expected some
form of error instead of an indefinite retry.

Ciao
Stephan

**Comment by Kritner** [comment]
This change is on demo in release [v1.1.0.18](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.18)

**Comment by Kritner** [comment]
This change has been released to prod in release [v1.1.0.18](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.18).
