### ISSUE TITLE
HKDF issue with SHA1 

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP-Server#58]
**environment**
Demo

Look likes it's fine with other HMAC modes but SHA1, which should be also supported from the spec.

**Algorithm registration**
`{
            "algorithm": "KAS-KDF",
            "mode": "HKDF",
            "revision": "Sp800-56Cr1",
            "fixedInfoPattern": "uPartyInfo||vPartyInfo||l",
            "encoding": [
                "concatenation"
            ],
            "hmacAlg": [
                "SHA1"
            ],
            "macSaltMethods": [
                "default",
                "random"
            ],
            "l": 1024,
            "z": [
                {
                    "min": 224,
                    "max": 65336,
                    "increment": 8
                }
            ]
        }`

**Erro**
'KAS-KDF-HKDF-Sp800-56Cr1: General exception. Contact service provider.'

**Comment by abkarcher** [comment]
Hello,

I also ran into this recently - See https://github.com/usnistgov/ACVP/issues/1082

Thanks,
Andrew

**Comment by AndrewHYang** [comment]
@abkarcher Thanks. I will close this issue then.
