### ISSUE TITLE
HMAC will only generate vector sets for first two keyLen

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP-Server#59]
**environment**
Demo

**testSessionId**
The test session ID

**vsId**
/acvp/v1/testSessions/135504

**Algorithm registration**
"algorithms": [
        {
            "keyLen": [
                8,
                64,
                128,
                192,
                256
            ],
            "macLen": [
                256
            ],
            "algorithm": "HMAC-SHA2-256",
            "revision": "1.0"
        }
    ],

Have been trying different registrations. And it will generate test vectors for the first two keyLen only, no matter have many keyLen we put.

**Comment by Kritner** [comment]
This change is on demo in release [v1.1.0.18](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.18)

**Comment by Kritner** [comment]
This change has been released to prod in release [v1.1.0.18](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.18).
