### ISSUE TITLE
Sha256 test vector question

### ISSUE THREAD

**Issue by Wonil-sys** [usnistgov/ACVP-Server#6]
We use the following 
```
[
  {“acvVersion”:”1.0”},
  “algorithms”:[
  { 
  “Aalgorithm”: “SHA2-256”,
 “Rrevision”: “1.0”,
“MessageLength”: [ {“min”:8, “max”:51200, “increment”:8 } ]
 }
 ]
}
]
```
In this case, we receive a lot of test vectors comare to last year(previous system).
Our system is not a general system like pc, so it is very difficult to upload all the test vector to the chip’s memory at one time.
IF we use these so big test vector, then it make us very ineffient and time consuming work.

So, we tried again using separate request but satisfying SHAVS criteria.
But in this case, NIST DEMO server make erro in case of case 2 (in the following) like 256 bit case should be included to the request.
Actually we separet it to two cases like this. We thought these two cases satisfies SHAVS criteria.

Case 1.
```
  {“acvVersion”:”1.0”},
  “algorithms”:[
  { 
  “algorithm”: “SHA2-256”,
 “revision”: “1.0”,
“messageLength”: [ {“min”:8, “max”:512, “increment”:8 } ]
 }
 ]
}
]
```
Case 2.
```
  {“acvVersion”:”1.0”},
  “algorithms”:[
  { 
  “Aalgorithm”: “SHA2-256”,
 “Rrevision”: “1.0”,
“MessageLength”: [ {“min”:1304, “max”:51200, “increment”:792 } ]
 }
 ]
}
]
```

If you have any valuable comment on this situation, please let us know.
Thank you so much in advance.

**environment**
The environment the issue was experienced (Demo or Prod)

**testSessionId**
The test session ID

**vsId**
The vectorSet ID displaying the issue

**Algorithm registration**
The pertinent algorithm registration pieces (algorithm tested, capabilities, etc) in json format

**Endpoint in which the error is experienced**
https://[acvpUrl]/acvp/[endpoint] GET

**Expected behavior**

**Additional context**

**Comment by Kritner** [comment]
The idea of the ACVP server is not *necessarily* to directly interact with a crypto module; it's more common for it to interact with an intermediate proxy.  

There are a few clients out there like Cisco's [libacvp](https://github.com/cisco/libacvp) and @smueller's [acvpproxy](https://github.com/smuellerDD/acvpproxy).  

The developers of those projects would be much more equipped to talk about how they work, but the basic idea (from my limited understanding) is they do the communication with the ACVP server, and forward tests to and from the crypto modules/implementations, and finally back to the ACVP server.

There isn't an expectation that a chip would have the entirety of a vector set in its memory at a single time, the intention of clients such as the one's previously mentioned is to make it easier to coordinate the testing of a crypto implementation.

Hopefully that makes sense, and I'm sure the folks behind the clients will correct me if I've stated anything incorrectly.

**Comment by celic** [comment]
For the error you are receiving, vector sets have zero knowledge of each other. The tests for SHA will always try to perform the MCTs from the SHAVS. So each vector set will have its own MCTs. Again matching the SHAVS, the MCTs require a specific message length to be available so the server knows the MCTs can be completed. 

We expect clients to deal with these JSON files the same way test harnesses would deal with CAVS files. They can provide a single test case at a time to the IUT at any rate they are comfortable with. The IUT does not need to directly interact with the ACVP server. In the cases @Kritner described, this allows one client to interact with many different cryptographic modules with minimum code updates.

**Comment by smuellerDD** [comment]
Am Dienstag, 15. September 2020, 17:13:47 CEST schrieb Chris Celi:

> In the cases @Kritner described,
> this allows one client to interact with many different cryptographic
> modules with minimum code updates.

The ACVP parser [1] actually handles the crypto module interaction with 
backends where one parser can serve multiple different implementations. The 
ACVP Parser is used to test basically all open source modules out there, but 
also covers support for closed environments like Apple's corecrypto and 
others. This tool was used in very tight spaces.

See the readme in [2] to understand how the proxy gets the data and interacts 
with the ACVP server and the parser just processes one test vector at a time.

[1] https://github.com/smuellerDD/acvpparser

[2] https://github.com/smuellerDD/acvpproxy

Ciao
Stephan
