### ISSUE TITLE
KAS ECC/FCC tests fails for few tcIds and passes for all remaining for similar inputs

### ISSUE THREAD

**Issue by sreedharb-commits** [usnistgov/ACVP-Server#60]
On the snippets that is pasted below from the tests for KAS-ECC, the tests are of the kind where a hash is computed with the ephemeral keys in the input vector (tests 21 to 28 of Input vector snippet) and this computed hash is compared against the hashZIut present in the input vector against each test. If they match a true is written into the response file or a false on mismatch (response file snippet below). In the results generated by NIST, test 21 which writes true has passed, but test 22 writes true because the same harness code which executed for test 21 has generated a matching hash for test 22 also with it’s input keys and has written true in it. If the harness was wrong it should fail test 21 and others also. We also have the same harness code generating mismatched hash for other tests (24 and 28) and writing false and those tests have passed in the NIST result. As we don’t see a difference in the inputs of the failed tests to the passed ones, at this point looking at the harness as a point of failure does not look reasonable.  We have 70 such tests for ECC out of which only 4 have failed due to same reason , where this comparison of hash is done, and a match is found, but NIST says "IUT must detect issue with input pubkey". Similarly we have few failures of KAS-FCC for same kind of inputs where everything else passes for hash comparison. Please suggest on why for test 22 below, NIST ACVP server responds as "IUT should detect issue in ACVP server ephemeral public key"

Input vector snippet

    "tests": [
                {
                    "ephemeralPublicServerX": "0780E3B074F252EF2EFE0536047BC7F5F9CCEFF7C2D10785DED518BEC8596ACE",
                    "ephemeralPublicServerY": "DE675E8B73F6D3B0D7158C56DE92A38792D0E82175D0001F94DD8525F4BAA133",
                    "ephemeralPrivateIut": "DBC2AD135314EE884C7F15EF26027A20438B447D727FCFC74AADC1596A7DA205",
                    "ephemeralPublicIutX": "51B389AE76EFBD96C1B34A89F9CBA8FA559C5F1DED4CDC9B0AEDCA563EE118F0",
                    "ephemeralPublicIutY": "D9A2C981890F46BCA3BEE9AB132B6FE4B070471DA6649CE9363220E07BA839CD",
                    "tcId": 21,
                    "hashZIut": "B06FCFB43E76992EAB939ED8E11D2057DDF29CD03F7CB348601A502890777F09"
                },
                {
                    "ephemeralPublicServerX": "AB7C0107FD79084349EFD2F2FD85F53849F04B0CE20E71512F5A3661D888C4F1",
                    "ephemeralPublicServerY": "CD56EAE880FF29C8CEF071FDF6CDE7A87057C4FBD86D7DF6675BDA221E88AF21",
                    "ephemeralPrivateIut": "FC724FF03209665BDCA94D7ADF6F8A38E69CDC8E842DBAE3D147E46529947655",
                    "ephemeralPublicIutX": "AE36EE91B1C6886BCE45D4BE8FAFAF69820584B9D21D1233BEE9975A51FBC4DE",
                    "ephemeralPublicIutY": "C4CB2D0BA6EAFAFAB96EF3C3FC7434FB2FC73B8559A5F33F8C98012A1C463116",
                    "tcId": 22,
                    "hashZIut": "EE7A257DE06B513A635F47FBA45C80B0FF69DD153DAA1498714C00F01A33BBF5"
                },
                {
                    "ephemeralPublicServerX": "9EFA6E57E11F2292CA367A90BE32842B5DE9950BF227D848ABC97E3EFBA90083",
                    "ephemeralPublicServerY": "B6B0A9508CBC7FD9105DD78F0D9D18611ADC3DF3CBDF15CCAC64C2836FB8EBCD",
                    "ephemeralPrivateIut": "E02418227D7505E154C617BE1954376FBC105A455B0D276921CAECD7EC5851A8",
                    "ephemeralPublicIutX": "E42CB224046FDAD69755C6BF112DC60E413D15A1DB4371ECFF7DA13FB4D5B854",
                    "ephemeralPublicIutY": "A7970F02E79DFFE1A3EBE9236701969B040A0E27A0037255EAF04B1C09AD276F",
                    "tcId": 23,
                    "hashZIut": "28A8E24509B687ECA2A57B4B19F8BC10FD30C289954A1F8136AF8041120DD2B2"
                },
                {
                    "ephemeralPublicServerX": "EAD2768C8D04C122ABE090167D04B0B79B6DA0D5E81D3F76003D8B08E68FE326",
                    "ephemeralPublicServerY": "631369BD92C6D2A14F37735A803F4D8129F5035844EA1E668F5060F238603952",
                    "ephemeralPrivateIut": "B2F6C2DD7D1C992C493617A60FF7913F094C9EC9390D6A938EEE98B02AA60F02",
                    "ephemeralPublicIutX": "C3D9D6A431F2E86EA5F8366E03B71610DF9237525E1F262603018A4F9E421030",
                    "ephemeralPublicIutY": "DA26A3B6858683BDC006689E63D7E538F89516E0E4332762C959FBAA3522E42F",
                    "tcId": 24,
                    "hashZIut": "0417F9235AFBD01F3452E1A032EAA4FB2EF63DF2BC911CCFD90B15A1452E62C9"
                },
                {
                    "ephemeralPublicServerX": "D4472BE225E6EB7C4BE35DEDCD98714D30F73DB367455CA88AC1BCACF55CE0D0",
                    "ephemeralPublicServerY": "28EDEE3E83A875C386DE697195190BADDF508EA71895F446149895B115508D3E",
                    "ephemeralPrivateIut": "A845A596215DCC0CCC8A51DFB1E43E8AA260E8155C5522235A777DF3A4BCC20C",
                    "ephemeralPublicIutX": "DC13047F0B2EDCCE01C51C108ACC5B4FC3A5FBFBA206A6D961865081DAE58689",
                    "ephemeralPublicIutY": "9B0E16BCB216A4185824304CFE81D26CCFF4E3BEF6CBC934ABF4AEC7FC7AEAD1",
                    "tcId": 25,
                    "hashZIut": "AD2B03F7B004D7192860D2760FF4BCD6A30EBF0032A3BEDD92DAEFD169438DF4"
                },
                {
                    "ephemeralPublicServerX": "A6663FE79B6C04815D4FCD7C09CD300754E407FF7D0C4D0E105C2381F8FCC37B",
                    "ephemeralPublicServerY": "FF6ACFB4BB60CE34C599F80370AB16CF401895DC10578E4BC0C69301089EB64A",
                    "ephemeralPrivateIut": "C04AAA741B661928DE6202F24104FAF4DF8383B5618C8766173011914B4579D5",
                    "ephemeralPublicIutX": "5C2BB9F65E77624D19492381C32D32EA8A9352D8ED22F900D1EBA71F0CDD821D",
                    "ephemeralPublicIutY": "DB5F29EEABC56B1579AB8DD83DCB3CC3DA5650C8E9F3398E85FC70B5DAF81662",
                    "tcId": 26,
                    "hashZIut": "DAEBCDF69A9D8F21CAAA3639BF65BA91B2364D35F410FF04B62135320F0D9A4E"
                },
                {
                    "ephemeralPublicServerX": "8608AC75E196FBAAA20C1DB973453412B04243421BBB3A37E65C4646546CC18D",
                    "ephemeralPublicServerY": "52D830BCE8A6483324B28EC77F751185FA75FFC569426A1ACF87B275A0487853",
                    "ephemeralPrivateIut": "232E531B6D008601EBE225A94EAFB59606400C21A263808C760EBBAB5899C790",
                    "ephemeralPublicIutX": "B24CCB09D8876B0847EA75B425AD8014C3C6B49C4E03875C6D0EA2CC26B1A1AC",
                    "ephemeralPublicIutY": "7F50CEF1E65BB2BF5029A748DD77B707D0A0EAD8B5574EE3E2929A4DC207420B",
                    "tcId": 27,
                    "hashZIut": "C39F2724D40B1A13FB348369BD3295C3F89B73647C26BD5D3351EB83B0118F68"
                },
                {
                    "ephemeralPublicServerX": "BC4AD3A3A09763C7286507DC122D868B6FC09C59515A3424216F11E5F1FBC821",
                    "ephemeralPublicServerY": "E5C7DF25EE2861B709D2877FA546A3E1BFBF1F7146B2ACF33CB79A9BE081467D",
                    "ephemeralPrivateIut": "C35D09ADC27CCE12DBFECC80ACCF1EE0DA35DF4828A93D63AC14C3E18A6BD5E4",
                    "ephemeralPublicIutX": "E361FD3A934D1792B971E8075E6341DB7B2E49BBCA1C63AA4E4B702B997D9DFC",
                    "ephemeralPublicIutY": "749C85082CB7AE5DF4D6BB18C459C8A5A5779ED561A46BA7288B2A087AADC50E",
                    "tcId": 28,
                    "hashZIut": "313ED4E980E0A680053C365314CAFCD6E954E101F0A37DEE9609C32A246B20A6"
                },

Response file snippet

"tests":   [{
                            "tcId":    21,
                            "testpassed":   true
                      }, {
                            "tcId":    22,
                            "testpassed":   true
                      }, {
                            "tcId":    23,
                            "testpassed":   true
                      }, {
                            "tcId":    24,
                            "testpassed":   false
                      }, {
                            "tcId":    25,
                            "testpassed":   true
                      }, {
                            "tcId":    26,
                            "testpassed":   true
                      }, {
                            "tcId":    27,
                            "testpassed":   true
                      }, {
                            "tcId":    28,
                            "testpassed":   false

UL NIST server output
       {
            "tcId": 21,
            "result": "passed"
        },
        {
            "tcId": 22,
            "result": "failed",
            "reason": "Incorrect TestPassed result. Test expectation: \"Failure - IUT should detect issue in ACVP server ephemeral public key.\""
        },
        {
            "tcId": 23,
            "result": "passed"
        },
        {
            "tcId": 24,
            "result": "passed"
        },
        {
            "tcId": 25,
            "result": "passed"
        },
        {
            "tcId": 26,
            "result": "passed"
        },
        {
            "tcId": 27,
            "result": "passed"
        },
        {
            "tcId": 28,
            "result": "passed"
        },

Regards
Sreedhar

**Comment by sreedharb-commits** [comment]
Please let me know the answer, is anyone looking into it

**Comment by Kritner** [comment]
It would be helpful to use the github template, as the template offers questions to be answered by the issue submitter so that the team would (likely) have enough information to go on in order to get a response to the submitter without several bouts of back and forth.

It would be helpful to know:

* the environment
* the registration
* the test session id
* the vector set id

I have to guess that this is a registration for the 1.0 testing of KAS, and "partialVal" or "fullVal" KAS functions have been registered within your capabilities.  When those functions are registered, we produce key pairs that should fail either partial and/or full validation - hence the error message being returned in our result file.

If your IUT is not able to do partial or full validation on key pairs that are provided to it, then those functions should not be registered.  We only inject bad key pairs into this version of testing when the registration states the IUT can do said validation.

**Comment by sreedharb-commits** [comment]
I have attached the input vectors, generated responses and the ACVP server results on the response files. Yes the testing was on KAS revision 1.0. We are using the KAS harness of OpenSSL-FIPS 2.0.16. The mode of the test, the role etc are there in the input vector attached. What I did not understand is why the same ACVP server failed just 4 of the 70 test ids in each of the attached vectors, when the kind of input is same for all test ids and same harness code is executed upon them. Why the error "IUT should detect issue in ACVP server ephemeral public key"

**Comment by Kritner** [comment]
> What I did not understand is why the same ACVP server failed just 4 of the 70 test ids in each of the attached vectors, when the kind of input is same for all test ids and same harness code is executed upon them. Why the error "IUT should detect issue in ACVP server ephemeral public key"

Because not all of our tests are constructed with valid inputs, purposefully.  I went into this in my last response, but the test cases you're talking about have *invalid key pairs*.  You have not provided your test session nor vector set id, so I can't confirm the capabilities you've registered with, and nothing has been attached to this issue.

In the test cases that are failing with the reason "IUT should detect issue in ACVP server ephemeral public key", it's because the server has purposefully mangled the key pair to be invalid, and the registered capabilities state that the IUT can detect malformed key pairs, but it is failing to do so; that is the intention of the test.  In those test cases that are failing, the IUT should be returning a `"testPassed": false`.

**Comment by sreedharb-commits** [comment]
ok I had browsed and added the files. Not sure if I missed to click on something to add the files. But below is the detail on the VsId and the registeration details for failed test. So are you saying that because of this registeration, the test must have the capability to detect malformed key pair and in case we do not support that we should change the registeration and test with a different vector?


    "vsId": 409686,
    "algorithm": "KAS-ECC",
    "revision": "1.0",
    "isSample": false,

            "scheme": "ephemeralUnified",
            "parmSet": "ec",
            "curve": "P-256",
            "tgId": 3,
            "testType": "VAL",
            "kasRole": "initiator",
            "kasMode": "noKdfNoKc",
            "hashAlg": "SHA2-256",

**Comment by Kritner** [comment]
> So are you saying that because of this registeration, the test must have the capability to detect malformed key pair and in case we do not support that we should change the registeration and test with a different vector?

Yes, specifically this bit in the registration:

```json
"function": [
  "fullVal"
],
```

This probably isn't articulated in the specification, I'll take a look and update it a bit when I have a chance.

**Comment by sreedharb-commits** [comment]
Can you please suggest on how the registeration should be changed if fullVal is not supported as our IUT does not support the detection of malformed keypair.

**Comment by Kritner** [comment]
Just take out the "function" property and its corresponding array.  The full registration would then be:

```json
{
	"vsId": 409686,
	"algorithm": "KAS-ECC",
	"revision": "1.0",
	"scheme": {
		"ephemeralUnified": {
			"kasRole": [
				"initiator",
				"responder"
			],
			"noKdfNoKc": {
				"parameterSet": {
					"ec": {
						"hashAlg": [
							"SHA2-256"
						],
						"curve": "P-256"
					}
				}
			}
		}
	}
}
```

**Comment by sreedharb-commits** [comment]
Thank you. Since we need to claim SP800-56A-rev3, we are told we need to perform this test as well. So I want to know if the malformed keypair is the public key generated from ephemeralPublicIutX and ephemeralPublicIutY and the privatekey which ephemeralPrivateIut. The math of generator*privatekey = publickey should fail for a malformed pubkey. Is that right? or is it like only pubkey is to be checked whether it is in point or infinity for elliptic curve. Similarly for FCC in case of Diffie hellman the math of publickey modulus safeprime P = 1 modulus safeprime Q should fail. Please let me know if the above interpretation is right.

**Comment by sreedharb-commits** [comment]
When we do the elliptic curve math of  generator*privatekey = publickey from the OpenSSL standard code EC_Check_key() , it matches for the keypair formed by IUT x and y and the IUT private key. This happens for the data in both the passed test and the failed test. I understand if key pair is malformed by even 1 bit, this mathematics should not work. So can you please confirm if the keypair is actually malformed. We also have checks where it is verified whether the public key coordinates are in curve point or infinity. I wonder as to which other test can find the key is malformed.

**Comment by Kritner** [comment]
From the original test case:

```json
{
                "ephemeralPublicServerX": "AB7C0107FD79084349EFD2F2FD85F53849F04B0CE20E71512F5A3661D888C4F1",
                "ephemeralPublicServerY": "CD56EAE880FF29C8CEF071FDF6CDE7A87057C4FBD86D7DF6675BDA221E88AF21",
                "ephemeralPrivateIut": "FC724FF03209665BDCA94D7ADF6F8A38E69CDC8E842DBAE3D147E46529947655",
                "ephemeralPublicIutX": "AE36EE91B1C6886BCE45D4BE8FAFAF69820584B9D21D1233BEE9975A51FBC4DE",
                "ephemeralPublicIutY": "C4CB2D0BA6EAFAFAB96EF3C3FC7434FB2FC73B8559A5F33F8C98012A1C463116",
                "tcId": 22,
                "hashZIut": "EE7A257DE06B513A635F47FBA45C80B0FF69DD153DAA1498714C00F01A33BBF5"
            },
```

and the server response:

```json
Incorrect TestPassed result. Test expectation: "Failure - IUT should detect issue in ACVP server ephemeral public key.
```

The issue is on the *acvp server*s public key, not the keys that are to be used by the IUT.  The ACVP server's public key should fail against the partial ECC validation check done by the IUT, as that point does not exist on the curve.

Regarding the documentation update, that's in PR https://github.com/usnistgov/ACVP/pull/1159
