### ISSUE TITLE
Cannot choose anything other than 100001 for fixedPubExp when registering RSA SigVer

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP-Server#62]
**environment**
Demo

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
```json
{
    "algorithm": "RSA",
    "revision": "FIPS186-4",
    "mode": "sigVer",
    "pubExpMode": "fixed",
    "fixedPubExp": "000001",
    "capabilities": [
        {
            "sigType": "pkcs1v1.5",
            "properties": [
                {
                    "modulo": 4096,
                    "hashPair": [
                        {
                            "hashAlg": "SHA2-512"
                        }
                    ]
                }
            ]
        }
    ]
}
```

**Endpoint in which the error is experienced**
`POST` https://demo.acvts.nist.gov/acvp/v1/testSessions

**Expected behaviour**
Can create a registration with a custom public fixed expoonent

It seems like what I try to register this with an `fixedPubExp` other than `100001`, it fails with the response:
```json
[
    {
        "acvVersion": "1.0"
    },
    {
        "error": "Validation error(s) on JSON payload.",
        "context": [
            "RSA-sigVer-FIPS186-4: Improper E value provided"
        ]
    }
]
```

Are other values allowed or is `100001` that only actual value that can be entered for the `fixedPubExp`?

**Comment by Kritner** [comment]
Can you give an example of another value that fails?  At a glance looks like it needs to be in the range of 2^15...2^255 and an odd value.

**Comment by AlexThurston** [comment]
Doh!  I missed the documentation that says as much here: https://pages.nist.gov/ACVP/draft-celi-acvp-rsa.html#name-rsa-signatureprimitive-mode

That being said, that documentation is saying that it needs to be 65537 to 2^256-1 and odd, but it looks like it's accepting 32768+1 (100001).

**Comment by Kritner** [comment]
Is there a typo in your last message @AlexThurston ? `100001` hex -> decimal = 1,048,577, not 32769, no?

**Comment by AlexThurston** [comment]
Bah, I fat fingered and didn't use my brain.  I'll close this.
