### ISSUE TITLE
GET /testSessions/<testSessionId>/results yields inconsistent data

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP-Server#63]
**environment**
demo/prod

After posting all results of all vsIDs belonging to one test session and receiving a pass verdict, I obtain the test session verdict which also yields a passing verdict.

When re-downloading the vsIDs results via GET vsID/results, the returned data is still the same as before - good.

But a subsequent GET testsessionID/results returns that the test session verdict is now FAILED - this is inconsistent to the initial result data.

Even when the testsession result returns a FAILED verdict for subsequent GET operations, I can successfully request a certificate for the test session. So, the returned test session verdict seems to be wrong.

**Comment by Kritner** [comment]
Sorry @smuellerDD I'm trying to work my way through the issues, but obviously some are falling through the cracks.

Is this `"passed": false` coming through *after* doing a `PUT`? I don't see that as a step in your issue's text, but it seems like that would be one way it could occur on our end.  I can put that fix in in the next release, but doubt that's the cause of the problem if no `PUT` was done on the test session in question.

**Comment by smuellerDD** [comment]
Somehow I must have missed this comment.

I perform the following steps:

1. POST all test responses on each vsID ->passed verdicts

2. GET the test session verdict -> PASS

3. GET the test session verdict again (no additional operations) - > FAIL

**Comment by Kritner** [comment]
Hey @smuellerDD I haven't had any additional luck reproducing this with the steps provided in your [last comment](https://github.com/usnistgov/ACVP-Server/issues/63#issuecomment-808339048), there was an issue fixed as a result of https://github.com/usnistgov/ACVP/issues/1144 which I *thought* that was being described in this issue, but not according to the [last comment](https://github.com/usnistgov/ACVP-Server/issues/63#issuecomment-808339048)

The correction that was done for https://github.com/usnistgov/ACVP/issues/1144 was around what determines "pass" - previously we had statuses of `passed`, `submitted for certification` and `certified` (those aren't the exact definitions, but should convey well enough what they mean).  Prior to the change only the `passed` status would return "pass" from the endpoint, where "submitted for certification" and "certified" would return `!passed`, now all three statuses should return `passed`.

I forgot to add that issue and (what I thought was this issue) to the release notes for the [current release](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.17) until now.  I don't know if you'll be able to reproduce this on demo or not.

**Comment by smuellerDD** [comment]
After testing it again, I do not see the problem any more. Thanks. Closing.

**Comment by Kritner** [comment]
This change is on prod as of release [v1.1.0.17](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.17)
