### ISSUE TITLE
Maximum z of KAS KDF TwoStep

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP-Server#64]
When we set z as `z: [{ min: 224, max: 65536, increment: 8 }]`, we got a reject message as `['KAS-KDF-TwoStep-Sp800-56Cr1: Maximum z must be less than or equal to 65336']`

Shouldn't the maximum be 65536 instead of 65336?

**Comment by Kritner** [comment]
Thanks @AndrewHYang, looks like this applies to all of the KAS KDFs.  I'll get this changed in the next release.

**Comment by Kritner** [comment]
This change is on demo in release [v1.1.0.18](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.18)

**Comment by Kritner** [comment]
This change has been released to prod in release [v1.1.0.18](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.18).
