### ISSUE TITLE
AES-CCM: Decrypt test behavior inconsistent with SP 800-38C

### ISSUE THREAD

**Issue by tsengjk** [usnistgov/ACVP-Server#72]
**environment**
Demo

**testSessionId**
138442

**vsId**
434068

**Algorithm registration**
```
         {
            "tgId": 6,
            "testType": "AFT",
            "direction": "decrypt",
            "keyLen": 256,
            "ivLen": 104,
            "payloadLen": 0,
            "aadLen": 0,
            "tagLen": 128,
            "tests": [
               {
                  "tcId": 51,
                  "key": "DA20BE86F9D69542D7ED06135BFD3E3B2644888190DD36C40CCB9441C93FFD4D",
                  "aad": "",
                  "iv": "C4B976CBCB726E0C47B6EA30F1",
                  "ct": "918833572B67244F4D8792E632B25A47"
               },
```
**Expected behavior**
```
{
            "tgId": 6,
            "tests": [
               {
                  "tcId": 51,
                  "pt": ""
               },
```
I've noticed that for CCM Decryption tests (for example tcID 51 above), there are many cases where the length of the ciphertext _Clen_ is equal to the length of the tag _tagLen_. As seen above, _Clen_ = 16 bytes and _tagLen_ = 16 bytes. When you look at the expected results, you see that for tcID 51, the result is an empty payload string.

In 6.2 of SP 800-38C, step 1 states that if _Clen_ is less than or equal to _Tlen_ (_tagLen_), then you immediately return “INVALID”. Therefore, the correct behavior from a SP 800-38C compliance standpoint would be to return "testPassed" = false instead of an empty plaintext.

Is this a ACVP implementation issue? A typo in SP 800-38C? Or perhaps a misinterpretation?

**Comment by Kritner** [comment]
I'm not actually sure about this one, will probably need to do some more digging. Additionally this is behavior that is mirrored from the CAVS tool days; not that it necessarily means it was correct then either.

Conceivably CCM should work for verification with an empty payload, as the generation function seems to work just fine without one, and without an immediately obvious check for `PLen > 0` on the generation step.  CCM *could* be used simply as a means of confirming a key, with (or without) non associated data through the use of plugging in a key, aData, and empty payload into the function.

**Comment by Kritner** [comment]
I heard back from the author of the SP and we're in agreement that `Clen <= Tlen` in the verification step should actually be `Clen < Tlen`

![image](https://user-images.githubusercontent.com/8814983/114755020-31387100-9d27-11eb-8561-6327c3e582e6.png)

This should be updated in the next revision of the SP, and we will continue allowing for `Clen == Tlen` in ACVP testing.

Additionally, I was pointed to a footnote on page 7 of the SP:

![image](https://user-images.githubusercontent.com/8814983/114755427-9c824300-9d27-11eb-9c3c-4227f2f5c47e.png)

Let me know if you need anything else!
