### ISSUE TITLE
FF1 - Continued errors with larger messages

### ISSUE THREAD

**Issue by rruss-ldos** [usnistgov/ACVP-Server#73]
[ACVP-AES-FF1.417783.expected.txt](https://github.com/usnistgov/ACVP-Server/files/5895390/ACVP-AES-FF1.417783.expected.txt)
[ACVP-AES-FF1.417783.response.txt](https://github.com/usnistgov/ACVP-Server/files/5895391/ACVP-AES-FF1.417783.response.txt)

**environment**
Demo

**testSessionId**
134396

**vsId**
417783

**Algorithm registration**
			{
				"algorithm":"ACVP-AES-FF1",
				"revision":"1.0",
				"direction":[
					"encrypt",
					"decrypt"
				],
				"keyLen":[
					128,
					192,
					256
				],
				"tweakLen":[
					{
						"min":0,
						"max":128,
						"increment":8
					}
				],
				"capabilities":[
					{
						"alphabet":"0123456789",
						"radix":10,
						"minLen":6,
						"maxLen":16383
					},
					{
						"alphabet":"abcdefghijklmnopqrstuvwxyz",
						"radix":26,
						"minLen":5,
						"maxLen":16383
					},
					{
						"alphabet":"0123456789abcdefghijklmnopqrstuvwxyz",
						"radix":36,
						"minLen":4,
						"maxLen":16383
					}
				]
			},

**Endpoint in which the error is experienced**
https://demo.acvts.nist.gov/acvp/v1/testSessions/134396/vectorSets/417783 GET

**Description**
We are experiencing what we believe to be false negatives for FF1 with radix's 26/36 and high message lengths (16k+). Responses to sample vectors have been generated using the vendor's implementation and an independent implementation. These responses do not match the expected results provided for the sample vectors.

This behavior appears to be similar to that described in https://github.com/usnistgov/ACVP/issues/681.

**Comment by Kritner** [comment]
That vector set has already expired due to inactivity.  If you have a specific test case that can provide the original inputs, as well as intermediate values, I can compare to our implementation to see where we differ.

**Comment by rruss-ldos** [comment]
Attached is the request json and corresponding intermediate values for the mismatching test cases (TgId2-TcId27 and TgId3-TcId52).

Thanks

[ACVP-AES-FF1.417783.req.json.txt](https://github.com/usnistgov/ACVP-Server/files/5912567/ACVP-AES-FF1.417783.req.json.txt)
[sample_tgId2_tcId27.txt](https://github.com/usnistgov/ACVP-Server/files/5912552/sample_tgId2_tcId27.txt)
[sample_tgId3_tcId52.txt](https://github.com/usnistgov/ACVP-Server/files/5912554/sample_tgId3_tcId52.txt)

**Comment by Kritner** [comment]
A fix for this has been pushed to demo, found an issue in the padding that occurs in longer payloads.  After correcting the problem we agree on the final result.

**Comment by rruss-ldos** [comment]
The fix appears to have worked. We are now seeing matching results for samples with the higher message sizes.

**Comment by rruss-ldos** [comment]
Would ACVP be able to provide an estimate on when v1.1.015 would be pushed to Production?

**Comment by Kritner** [comment]
Current plan is to get the release out on Friday

**Comment by Kritner** [comment]
This change is on prod in release [v1.1.0.15](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.15)
