### ISSUE TITLE
Unable to retrieve expected results

### ISSUE THREAD

**Issue by jethrogb** [usnistgov/ACVP-Server#78]
**environment**
Demo

**testSessionId**
163187

**vsId**
483504

**Algorithm registration**
```json
{
  "algorithm": "ACVP-AES-FF1",
  "revision": "1.0",
  "direction": [
    "encrypt",
    "decrypt"
  ],
  "keyLen": [
    128,
    192,
    256
  ],
  "tweakLen": [
    {
      "min": 0,
      "max": 16,
      "increment": 16
    }
  ],
  "capabilities": [
    {
      "alphabet": "0123456789",
      "radix": 10,
      "minLen": 6,
      "maxLen": 128
    }
  ]
}
```

**Endpoint in which the error is experienced**
/acvp/v1/testSessions/163187/vectorSets/483504/expected GET

**Expected behavior**
I created a session with `isSample: true` but when trying to obtain the expected results I get a 404

**Comment by Kritner** [comment]
I just took a look at that test session and it wasn't created as a sample test session, could you have nested the `isSample` property under the wrong object?

**Comment by jethrogb** [comment]
Indeed, apparently setting `--sample` on the command line as documented doesn't work and you need manually to put it in the JSON as well. Sorry to waste your time on this.
