### ISSUE TITLE
SP800-56C r1 OneStep general error

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP-Server#8]
**environment**
Demo

**testSessionId**
not yet awarded

**vsId**
N/A

**Algorithm registration**
```
      {
        "prereqVals":[
          {
            "algorithm":"SHA",
            "valValue":"same"
          },
          {
            "algorithm":"HMAC",
            "valValue":"same"
          },
          {
            "algorithm":"DRBG",
            "valValue":"same"
          }
        ],
        "algorithm":"KAS-KDF",
        "mode":"OneStep",
        "revision":"Sp800-56Cr1",
        "l":1024,
        "z":[
          {
            "min":256,
            "max":512,
            "increment":128
          }
        ],
        "auxFunctions":[
          {
            "auxFunctionName":"HMAC-SHA2-256",
            "macSaltMethods":[
              "default",
              "random"
            ]
          },
          {
            "auxFunctionName":"SHA2-256",
            "macSaltMethods":[
              "random"
            ]
          }
        ],
        "fixedInfoPattern":"uPartyInfo||vPartyInfo||literal[affedeadbeef]",
        "encoding":[
          "concatenation"
        ]
      },
```

**Endpoint in which the error is experienced**
POST /acvp/v1/testSessions

```
[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "KAS-KDF-OneStep-Sp800-56Cr1: General exception. Contact service provider."
    ]
  }
]
```

**Comment by smuellerDD** [comment]
Sorry, typo in registration

**Comment by Kritner** [comment]
@smuellerDD what was the typo?  That wasn't a good error response to return from our end, probably dealing with an NRE on the property that wasn't provided.  I'd like to fix that so a more meaningful error message is returned.

**Comment by smuellerDD** [comment]
Am Freitag, 18. September 2020, 21:35:13 CEST schrieb Russ Hammett:

Hi Russ,

> @smuellerDD what was the typo?  That wasn't a good error response to return
> from our end, probably dealing with an NRE on the property that wasn't
> provided.  I'd like to fix that so a more meaningful error message is
> returned.

I sent you a twostep KDF registration with a OneStep mode marker :-)

Ciao
Stephan

**Comment by Kritner** [comment]
ah thanks, I'll put in a fix for that.

**Comment by Kritner** [comment]
A fix for this is on demo BTW (the issue with the transposed registration vs algorithm identifier)

**Comment by Kritner** [comment]
this change is now on production https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.12
