### ISSUE TITLE
FIPS 186-2 legacy sigver rejected

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP-Server#80]
When sending the following request to the server:

```
    "algorithms":[
      {
        "revision":"FIPS186-2",
        "algorithm":"RSA",
        "mode":"legacySigVer",
        "pubExpMode":"random",
        "capabilities":[
...
```

The following answer is returned which seems that the server does not know FIPS 186-2:

```
[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "Unable to map RSA-legacySigVer-FIPS186-2 - index 0 to an internal algorithm id."
    ]
  }
]
```

**Comment by Kritner** [comment]
"legacySigVer" is not a valid mode, this was changed in the (client breaking change) of https://github.com/usnistgov/ACVP/issues/990.  It went from `RSA` / `legacySigVer` / `1.0` to `RSA` / `sigVer` / `FIPS186-2`.  

Was there still a place in the documentation that referred to it as legacySigVer?

**Comment by smuellerDD** [comment]
Well, I must have missed the update in the SPEC. Sometimes it is a bit hard to keep track on such changes.

Confirmed, working.
