### ISSUE TITLE
KAS-HKDF: General Exception

### ISSUE THREAD

**Issue by asant57** [usnistgov/ACVP-Server#84]
**environment**
Demo

**testSessionId**
NULL

**vsId**
NULL

**Algorithm registration**
[
  {
    "algorithm": "KAS-KDF",
    "revision": "Sp800-56Cr1",
    "mode": "HKDF",
    "fixedInfoPattern": "uPartyInfo||vPartyInfo||l",
    "encoding": [
      "concatenation"
    ],
    "hmacAlg": [
      "SHA1",
      "SHA2-224",
      "SHA2-256",
      "SHA2-384",
      "SHA2-512",
      "SHA2-512/224",
      "SHA2-512/256",
      "SHA3-224",
      "SHA3-256",
      "SHA3-384",
      "SHA3-512"
    ],
    "macSaltMethods": [
      "default",
      "random"
    ],
    "l": 1024,
    "z": [
      {
        "min": 224,
        "max": 65336,
        "increment": 8
      }
    ]
  }
]

Server output
{
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "KAS-KDF-HKDF-Sp800-56Cr1: General exception. Contact service provider."
    ]
}

**Endpoint in which the error is experienced**
acvp/v1/testSessions POST

**Expected behavior**
The TestSession is created.

**Additional context**
-

**Comment by Kritner** [comment]
Looks like this was a miss from a change in https://github.com/usnistgov/ACVP/issues/1129, the SHA1 is only partially being rejected for the HKDF testing.  I'll put in a fix for it in the next release to properly return the fact that SHA1 is not valid for HKDF testing.

SHA1 should not have been allowed within the specification either, will be removing it from there as well.

**Comment by Kritner** [comment]
The fix for this is on demo in [hotfix v1.1.0.16-1](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.16-1)

**Comment by Kritner** [comment]
The fix for this is on prod in [hotfix v1.1.0.16-1](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.16-1)
