### ISSUE TITLE
ACVP-AES-CBC ignoring payloadLen

### ISSUE THREAD

**Issue by kettro** [usnistgov/ACVP-Server#87]
**environment**
The environment the issue was experienced (Demo or Prod)
Demo

**testSessionId**
The test session ID
acvp/v1/testSessions/167347

**vsId**
The vectorSet ID displaying the issue
/acvp/v1/testSessions/167347/vectorSets/505689

**Algorithm registration**
The pertinent algorithm registration pieces (algorithm tested, capabilities, etc) in json format
ACVP-AES-CBC

**Expected behavior**
```
"payloadLen": [{
    "min": 4096,
    "max: 8192,
    "increment": 4096
}]
```
To return a vectorset with payloads of length 4096 and 8192. 
The actual returned data is for payloads of 128-bit => 1024-bit.
Other values are respected (eg keyLen)

**Additional context**

**Comment by powersmc** [comment]
Just wanted to add to this thread that this also applies to **ACVP-AES-ECB**.  I have a test session on demo (167867) where I specified a payloadLen of 128 and received vectors where the "pt" values were variable lengths in some instances (in the "AFT" tests)

That being said, I'm not 100% sure if this is a "bug" or just a shortcoming.  In the spec, it's not 100% clear but it seems like payloadLen is only specifically called out for certain modes:
**KW/KWP**: https://pages.nist.gov/ACVP/draft-celi-acvp-symmetric.html#table-5
**CBC-CS/CTR/FF1/FF3**: https://pages.nist.gov/ACVP/draft-celi-acvp-symmetric.html#table-8

And for CBC/ECB it's not included in the table of required/optional parameters:
https://pages.nist.gov/ACVP/draft-celi-acvp-symmetric.html#table-4

So it may actually be the intended behavior that the server is just flat out ignoring "payloadLen" when it's provided for the modes where it's not expected.  That being said, there are definitely use cases _(like in my particular case we're testing an FPGA that can only handle a specific plaintext length)_ where it would be beneficial for this parameter to be usable.

I guess we'll see what NIST has to say.

**Comment by kettro** [comment]
Yeah, it appears that the payload is not part of the specification for these. Perhaps they will consider adding it in a version bump, like they did with AES-XTS?

**Comment by celic** [comment]
The specifications don't have payloadLen for all AES modes. The expectation on those modes is that you can handle any number of blocks. This is not something we plan on updating.
