### ISSUE TITLE
General exception. Contact service provider. Error

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP-Server#88]
**environment**
Demo

**testSessionId**
/acvp/v1/testSessions/167916
/acvp/v1/testSessions/167920

**vsId**
/acvp/v1/testSessions/167916/vectorSets/507555
/acvp/v1/testSessions/167920/vectorSets/507593

Test vectors and samples are all,
`{
    "error": "General exception. Contact service provider."
}`

**Comment by Kritner** [comment]
This issue is occurring because of the empty `macMethods` array within the registration, we should be ignoring it since it doesn't apply to the scheme, but were not.

I'll put in a fix, but in the meantime omitting the empty array should allow the vector set to go through

**Comment by Kritner** [comment]
The fix for this is on demo in [hotfix v1.1.0.16-1](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.16-1)

**Comment by Kritner** [comment]
The fix for this is on prod in [hotfix v1.1.0.16-1](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.16-1)
