### ISSUE TITLE
ACVP Extendable Output Function (XOF) JSON Specification incorrect

### ISSUE THREAD

**Issue by mmccarl** [usnistgov/ACVP-Server#92]
**environment**
Demo

**testSessionId**
none

**vsId**
none

**Algorithm registration**
PARALLELHASH-256 (and other ACVP Extendable Output Function (XOF))

**Endpoint in which the error is experienced**
algorithm registration

**Expected behavior**
XOF vector generation

**Additional context**
The document "ACVP Extendable Output Function (XOF) JSON Specification" (https://pages.nist.gov/ACVP/draft-celi-acvp-xof.txt) indicates that a registration contains the following elements (see table 2):
  - algorithm
  - revision
  - xof
  - hexCustomization
  - inputLen
  - outputLen
  - keyLen
  - macLen

For ParallelHash-256, keyLen and macLen are not necessary (table 3).

The sample code in appendix A provides the following for ParallelHash-128:

   {
     "algorithm": "ParallelHash-128",
     "revision": "1.0",
     "xof": [true, false],
     "hexCustomization": false,
     "outputLen": [
       {
         "min": 256,
         "max": 4096,
         "increment": 1
       }
     ],
     "msgLen": [
       {
         "min": 0,
         "max": 65536,
         "increment": 1
       }
     ]
   }

Note that it includes 'msgLen' instead of 'inputLen'.

I constructed the following registration:

            {
                "hexCustomization": true,
                "outputLen": [
                    {
                        "min": 128,
                        "max": 2048,
                        "increment": 128
                    }
                ],
                "xof": [
                    true,
                    false
                ],
                "msgLen": [
                    {
                        "min": 128,
                        "max": 2048,
                        "increment": 128
                    }
                ],
                "revision": "1.0",
                "algorithm": "PARALLELHASH-256",
                "prereqVals": []
            }

and received the following error:

            {
                    "acvVersion": "1.0"
            },
            {
                    "error": "Validation error(s) on JSON payload.",
                    "context": [
                        "PARALLELHASH-256-1.0: BlockSize Domain was not provided."
                    ]
            }

However, the spec only mentions BlockSize as a member of the test cases in the request vector file generated, not in the registration.

I also tried changing 'msgLen' to 'inputLen' to match the items in table 2, but the error response then becomes:

            {
                    "acvVersion": "1.0"
            },
            {
                    "error": "Validation error(s) on JSON payload.",
                    "context": [
                        "PARALLELHASH-256-1.0: MessageLength Domain was not provided.;BlockSize Domain was not provided."
                    ]
            }

What is the correct registration request for XOF functions?

**Comment by mmccarl** [comment]
@celic can you confirm this issue?

**Comment by celic** [comment]
```
{
  "vsId": 0,
  "algorithm": "PARALLELHASH-128",
  "revision": "1.0",
  "isSample": true,
  "conformances": [],
  "digestSize": [
    128
  ],
  "xof": [
    true,
    false
  ],
  "hexCustomization": false,
  "blockSize": [
    {
      "min": 1,
      "max": 16,
      "increment": 1
    }
  ],
  "outputLen": [
    {
      "min": 256,
      "max": 4096,
      "increment": 1
    }
  ],
  "msgLen": [
    {
      "min": 0,
      "max": 65536,
      "increment": 1
    }
  ]
}
```

This is an example of a correct registration. Some additional fields (should just be vsID, conformances, and digestSize) exist due to our internal system.

**Comment by mmccarl** [comment]
@celic thanks. is blocksize in bit or bytes?  what is the max value supported?

**Comment by celic** [comment]
Bits, and seems like the min/max is 1-128.
