### ISSUE TITLE
403 Forbidden trying to re-submit (previously rejected) validation for completed test session

### ISSUE THREAD

**Issue by abkarcher** [usnistgov/ACVP-Server#93]
**environment**
Prod

**testSessionId**
9062

**Endpoint in which the error is experienced**
/acvp/v1/testSessions/9062 PUT

**Expected behavior**
Receive an updated request URL

**Additional context**
We submitted a validation (EDIT: certification request, not validation) for this session that was rejected due to using inline OEs for an OE that already existed on the server. When I attempt to manually resubmit the validation request (using moduleUrl and oeUrl) I get 

***ACVP [INFO][log_network_status:1232]--> PUT testSession Validation...
	Status: 403
	Url: https://acvts.nist.gov:443/acvp/v1/testSessions/9062
	Resp: (null)
	
Unsure if I am doing something wrong. Usually, if the JWT is incorrect, the message body will indicate that.

Thanks,
Andrew

**Comment by smuellerDD** [comment]
Am Montag, 5. April 2021, 18:18:40 CEST schrieb abkarcher:

Hi abkarcher,

> Unsure if I am doing something wrong. Usually, if the JWT is incorrect, the
> message body will indicate that.

Resubmission on prod is not available.


Ciao
Stephan

**Comment by abkarcher** [comment]
Hi stephan,

Thanks for the response. Just to clarify, is there another process for this that you know of? we had emailed acvts-prod and were told

Rejection resets the test session for resubmission.  Please re-certify TS XXXX using the metadata IDS produced during the approval of XXXXX.

When I access the results of our test session submission, it says all is passed still. 

Thanks,
Andrew

**Comment by smuellerDD** [comment]
Am Montag, 5. April 2021, 18:23:50 CEST schrieb abkarcher:

Hi abkarcher,

> Hi stephan,
> 
> Thanks for the response. Just to clarify, is there another process for this
> that you know of? we had emailed acvts-prod and were told
> 
> "Rejection resets the test session for resubmission.  Please re-certify TS
> XXXX using the metadata IDS produced during the approval of XXXXX."
> 
> When I access the results of our test session submission, it says all is
> passed still.

Simply obtain a new testsession / vsID with the offending tests and rerun it. 
As long as you apply the same meta data during publication, it will be added 
to an existing cert.


> 
> Thanks,
> Andrew


Ciao
Stephan

**Comment by Kritner** [comment]
@smuellerDD It looks like @abkarcher is talking about a rejected certify, not a failed validation on a vector set.

**Comment by abkarcher** [comment]
Yes - sorry if my diction was incorrect!

**Comment by Kritner** [comment]
> Unsure if I am doing something wrong. Usually, if the JWT is incorrect, the message body will indicate that.

The returned body will indicate if the JWT is *expired*, if there are other problems with the JWT provided (like improper claims) we give a less specific message.

Also, we don't have a test session by that ID (9062), was it 6092?

You can validate the JWT has claims over the test session by looking for the tsId within the decoded JWT payload

**Comment by abkarcher** [comment]
Yes, it was 6092, and this issue was not the only place i mis-typed it. :) issue resolved, Sorry for the noise, and thanks for both of your inputs!
