### ISSUE TITLE
SSL/TLS protocol issue

### ISSUE THREAD

**Issue by AndrewHYang** [usnistgov/ACVP-Server#95]
**environment**
Prod

We are having an issue below when trying to connect Prod server
` EOF occurred in violation of protocol `

We didn't change anything of the connection module. The Dev server is still working fine. Is there any update that we missed for the Prod server?

**Comment by celic** [comment]
There was a restart last night due to a service not starting. No notice went out. This should be fixed now.

**Comment by AndrewHYang** [comment]
Got you, thanks
